heroku/cli

plugins.go

Plugin name was not required when using topic commands, causing panic if missing, as the empty string was not caught.
i.e. `heroku plugins:install`
Initially looked at putting code in cli.go, however the line in parseArgs with the loop followed by switch case for checking args has no sensible way to check for the (usually optional) absence of args:
`for i := 0; i < len(args); i++ {`
Another solution might be to add an additional check in cli.go, for the length of additional args (for topics that require it). Empty strings will likely cause further bugs.

Require plugin name

---

update.go

* switch to goreq for simpler download
* removed some messages during update
* ignored errors when renaming files

updater fixes

---

main.go
update.go

solve a bug where updates would fork while iojs was setting up
check if updates are needed just before performing updates

prevent update from forking needlessly

---

cli.go
git.go
login.go
request.go

use HEROKU_HOST to determine login credentials

fix staging authentication

---

cli.go
command.go

I want to be able to have `ctx.app` in the plugins but not enforcing its presence.
I have actions that may or may not require an app.
Is there a different way to do that?

Add wantsApp flag for filling apps but not enforce presence.

---

login.go
main.go
request.go

using oauth codes has problems right now

switch to api v2 for login

---

main.go

The new plugin is named `heroku-cli-addons`. This is causing folks to be missing the `heroku addons` command when the CLI updates.
@dickeyxxx 
cc @heroku/add-ons

Include correct default addons plugin

---

plugins.go

Prefixed setup messaging with `heroku-cli:` so it is clear where it is
coming from. Also removed reference to node so users don't get confused
that node is being installed on their machine. Also so they don't get
confused it's installing node if it is already there.

messaging changes

---

plugins.go

some users have a .staging directory in the node_modules directory
I'm not sure where it comes from, but it can safely be ignored.

ignore '.staging' plugin

---

flag.go

the --debugger flag does not have a char attribute. This causes a bug
where if you run a command like `heroku info -a forker -` it will try to
run it with --debugger.

fix bug with "-" flag

---

plugins.go

if the plugin directory is deleted but still exists in the cache the CLI
will error out when the user tries to run a plugin in it. This simply
checks to see if the referenced plugin directory exists in
~/.heroku/node_modules and if not, installs the plugin before running
it.

reinstall missing plugins

---

gode/packages.go

I have no idea why this was set to AUTO_AUTH. That doesn't seem like it
was ever a config for npm.
Fixes https://github.com/heroku/heroku/issues/1832

fix npm always-auth disable

---

plugins.go

it's so fast anymore it's not useful to show that it is caching

simplify plugins:link output

---

main.go

This allows us to run something like `heroku version` or `heroku update`
wihout installing the built-in plugins. (In case that step is broken for
whatever reason).

install built-in plugins only after running any built in commands

---

plugins.go

it's possible now to not have the directory and have it in the plugin
cache, this causes a panic. We should just return false here.

do not error if plugin does not exist

---

command.go

without this it won't return all the plugins on first run

setup builtin plugins before running commands command

---

gode/packages.go
gode/packages_test.go
io.go
plugin_cache.go
update.go

`npm update` doesn't seem to update for some users. They get this error
for some reason:
```
npm verb outdated not updating heroku-apps because it's currently at the
maximum version that matches its specified semver range
```
The best way I found to fix this was to more directly find outdated
packages and update them by installing the specific, newest version.

force updating of outdated plugins

---

update.go

These can have a longer interval, no reason to block the user if they only use the toolbelt every couple of weeks.

increase blocking updates to 90 day intervals

---

plugins.go
update.go

This change will force an update of the CLI with the updated Go code
after it is updated by re-executing the command with the same arguments.

reexec cli after updating

---

plugins.go

right now they only show if GODE_DEBUG is set. To reproduce the problem, try installing a non-existent package.

show errors from installing packages

---

plugin_cache.go
plugins.go

this fixes the bug that makes `plugins:uninstall` not work as well as making the CLI more consistent with the plugins actually installed and not just in the cache
* sorted output of `heroku plugins` (v4 only)
* ignore plugins that do not actually have a directory in `~/.heroku/node_modules`
* remove plugins from cache after uninstalling

ignore plugins if they do not exist

---

plugins.go

you can reproduce by running `heroku info | head -n1`

ignore EPIPE errors

---

main.go

We are going live today! Pipelines are officially GA, so it seems reasonable that heroku-pipelines becomes a default plugin. We recently updated it to v1.0 to reflect it's stability.

Add heroku-pipelines as a default package

---

gode/packages.go

* User defined npmrc may try and load non-existant modules

Set npm config onload-script=false

---

main.go

Before we merge this in, we need to cut a new release for github.com/heroku/heroku-orgs.

Adds `heroku-orgs` dependency

---

main.go
update.go

running `heroku update` still causes the blocking update to run. This is happening because when the CLI is updated, the update lock file is cleared to force an autoupdate and reexec of the command. Generally this is good, because it will make sure that everything is updated using the new CLI. The problem is when the command is actually update, it will force a blocking update, then run the command which is to update.
This just checks before running a blocking update if the command is to update. If so, there is no need to do the blocking update step.
before:
```
$ heroku update master
Updating Heroku v4 CLI to 4.27.25-3b727e5 (master)... done
heroku-cli: Adding dependencies... done
Updating plugins... no plugins to update.
Updating plugins... no plugins to update.
```
after:
```
$ heroku …
```

fix double updating bug

---

plugins.go

If the plugin fails to parse it formerly would just exit silently and
all plugins would fail to install.
Also, if the plugin output anything on stderr it would try to parse it
and also fail.
This redirects stderr out to the terminal and shows the parsing error if
any.

fix bugs with plugin parsing

---

cli.go

if plugin developers do things like add a -a flag to a command that
has needsApp: true, it can be hard to figure out why the flags aren't
working right

warn about duplicate flags

---

Godeps/Godeps.json
file.go
plugins.go
update.go
vendor/github.com/dickeyxxx/golock/.travis.yml
vendor/github.com/dickeyxxx/golock/lock.go

It seems even though we have a lockfile in place, 2 updates can still
happen at once. This fixes the file renaming to work even if 2 updates
are happening at the same time.

fix race condition with updater

---

plugins.go

@dickeyxxx please review?  this is new behavior and was breaking someones script because it was working before heroku-pipelines was in core and it kept working until v5 went out.

Exit non-zero on plugin existing already

---

package.json

It brings https://github.com/heroku/heroku-orgs/pull/51 which unblocks https://github.com/heroku/api/pull/6207.

Upgrade heroku-orgs

---

package.json

@dickeyxxx could you review?  This adds the `heroku-certs` plugin to core, now all the `certs` commands are implemented in node and `http-sni` functionality is available to everyone.  See https://devcenter.heroku.com/articles/ssl-beta for more info about changes related to `http-sni`

Add heroku-certs 1.1.15 to core

---

package.json

Fixes an issue with users operating with `members:add` in those teams/orgs that are using the invitation flow:
https://github.com/heroku/heroku-orgs/pull/66

Updates heroku-orgs

---

update.go

@dickeyxxx could you review / deploy?  This fixes a bug in `pg:psql` where when the heroku in `/usr/local/lib/heroku/bin/heroku` executes the updated `~/.local/share/heroku/cli/bin/heroku` it does not allow SIGINT to pass through.  This fixes the problem where ctrl-c causes psql to exit rather than canceling the current line.

Swallow SIGINT when exec'ing updated heroku exe

---

package.json

adds `heroku-cli-oauth`, as discussed

add heroku cli oauth

---

package.json

Just released this version. Making it standard.

Bumping heroku-spaces to 2.6.0

---

package.json

@dickeyxxx I saw that you had already bumped up the `heroku-pipelines` version to use the latest `heroku-cli-util` (thanks for doing that!), but this update is to bring the usage of what was added there:
https://github.com/heroku/heroku-pipelines/pull/51

Update heroku-pipelines to use cli.color.pipeline

---

package.json

Bump heroku-spaces to 2.8.0: https://github.com/heroku/heroku-spaces/pull/36.
/cc @heroku/dogwood

Bump heroku-spaces to 2.8.0

---

npm.go

@dickeyxxx could you review? there is a change in npm 3 to 4 where it no longer uses the node that npm was exec'ed with as part of the scripts.  So if users have node 6 in their PATH it will pick that up and use that instead causing issues with `heroku-kafka`.  This basically adds to the PATH in the subcommand so that the right node is found.
```
~/.local/share/heroku/plugins ᐅ ~/.local/share/heroku/cli/lib/node ~/.local/share/heroku/cli/lib/npm/cli.js rebuild
npm WARN lifecycle npm is using /Users/jdowning/.local/share/heroku/cli/lib/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

Add --scripts-prepend-node-path=true to npm args

---

package.json
yarn.lock

Fixes issues with long-running queries.
Not urgent, can go out in next release.

Bump heroku-pg to 2.0.26

---

install.go

@dickeyxxx could you review?
```
IEUser@IE11Win7 MINGW32 ~
$ heroku
!    HTTP Error: http://cli-assets.heroku.com/heroku-cli/channels/beta/win32-386 404 Not Found
IEUser@IE11Win7 MINGW32 ~
```

Fix Go => Node arch differences for 32bit

---

analytics.go

@dickeyxxx could you review?  Still trying to fix H12 errors in heroku-cli-analytics and this seems like the final thing we can fix under our control.  After this I will just chock up the H12s to slow / funky clients.

Always truncate analytics after upload

---

package.json
yarn.lock

This removes the restriction on ssh2-stream added in 73225cd27a63086df792252aabef1a44506b1c00 to fix heroku-ps-exec.

Upgrade heroku-ps-exec to 1.0.5

---

package.json

Minor change to make `heroku ci:debug` behave have the same `CI=true` environment variable as normal test runs. See: https://github.com/heroku/heroku-ci/pull/47.

Bump Heroku CI plugin version to 1.8.3

---

package.json
yarn.lock

Brings https://github.com/heroku/heroku-ci/pull/49.
Alternatively, we could ship this first https://github.com/heroku/heroku-run/pull/33, and then I won't need to open a PR to upgrade `heroku-ci` again. Up to you guys! 
Thank you!

Upgrade heroku-ci

---

package.json
yarn.lock

Bump heroku-pg to 2.2.6, for new commands.

Bump heroku-pg to 2.2.6

---

package.json
yarn.lock

Brings https://github.com/heroku/heroku-run/pull/34.
This would allow us to use `heroku-run` uptstream in heroku-ci: https://github.com/heroku/heroku-ci/blob/master/package.json#L42.
cc @heroku/devex

Upgrade heroku-run to v3.4.16

---

snap/snapcraft.yaml

The `confinement: classic` move broke the snap because PATH is not set up the same way in `confinement: strict` and `confinement: classic` [1]. There was also an issue preventing the use of Node 8.x with the snap (http://pad.lv/1702661). This pull request fixes both (thanks to @sergiusens).
You can test this by running `snapcraft` on an Ubuntu 16.04 or later VM in a checkout of this branch. That will produce a `*.snap` you can install with `sudo snap install --dangerous --classic *.snap`. The `heroku` command should then work without issue, including `heroku local`.
Thanks
1: When using classic confinement, selecting the right binaries is not a clear cut decision. If heroku calls applications that use node, should those applications use node from the snap or from the system? Here we use …

Fix classic confinement of snap package

---

package.json
yarn.lock

Bumps heroku-ci to v1.9.5, which has minor changes, see https://github.com/heroku/heroku-ci/pull/57.

Bump heroku-ci to v1.9.5

---

package.json
yarn.lock

Updates the underlying heroku-exec-util lib to 0.4.0, which implements a keepalive packet.

Upgraded heroku-ps-exec to 2.1.0

---

package.json
yarn.lock

Includes a better shield space error message:
Was:
```
$ h ps:exec
▸    This feature is restricted for Shield Spaces
```
Becomes:
```
$ h ps:exec
▸    This feature is restricted for Shield Private Spaces
```

Upgrade heroku-ps-exec to 2.1.1

---

snap/snapcraft.yaml

This switches the snap to yarn, which fixes running heroku. Previous commits would error out:
```
$ heroku login
▸    'MODULE_NOT_FOUND': Cannot find module '/snap/heroku/x3/lib/node_modules/heroku-cli/lib/legacy'
```

Switch the snap to yarn

---

package.json

Bump heroku-pg version, to make pg:outliers available to everyone.

Bump heroku-pg version

---

package.json

This will pin heroku-cli-util to version 6.2.11 to fix an issue with the `body:` argument to `cli.got` .

Upgrade heroku-ps-exec to 2.2.2

---

src/analytics.ts

The new guard prevents arg/flag options completion from wiping out the analytics for the command it's completing.

fix: autocomplete analytics

---

packages/spaces/commands/vpn/wait.js

VPN provisioning can sometimes take longer than 10 minutes. This increases the wait timeout to 20 minutes to take into account longer VPN provisioning times.
Issue: 
https://github.com/heroku/dogwood/issues/1825

Increase vpn:wait timeout

---

packages/spaces/commands/vpn/connect.js
packages/spaces/index.js
packages/spaces/lib/vpn-connections.js
packages/spaces/test/commands/vpn/connect.js

Existing `spaces:vpn` commands assume there can only ever be a single VPN connection for a space. This begins re-working them for the new UX designed to enable future support for multiple connections, starting with a `vpn:connect` command to set up a VPN connection.
The connect command accepts a name argument and passes it to the new `/vpn-connections` endpoint in API.

spaces: add vpn:connect command

---

packages/spaces/commands/vpn/destroy.js
packages/spaces/lib/vpn-connections.js
packages/spaces/test/commands/vpn/destroy.js

This re-works the `vpn:destroy` command to function properly with the new UX design that allows multiple VPN connections.

space: update vpn:destroy for multiple vpn connections

---

packages/spaces/commands/vpn/index.js
packages/spaces/commands/vpn/info.js
packages/spaces/index.js
packages/spaces/lib/format.js
packages/spaces/lib/peering.js
packages/spaces/lib/vpn-connections.js
packages/spaces/test/commands/vpn/index.js

Continuing from #931, Existing spaces:vpn commands assume there can only ever be a single VPN connection for a space.
This modification adds a new `heroku spaces:vpn:connections` command to list all the connections for a given space.

spaces: add vpn:connections command

---

packages/spaces/commands/vpn/config.js
packages/spaces/commands/vpn/info.js
packages/spaces/commands/vpn/wait.js
packages/spaces/lib/vpn-connections.js
packages/spaces/test/commands/vpn/config.js
packages/spaces/test/commands/vpn/info.js
packages/spaces/test/commands/vpn/wait.js

This adds support for multiple VPN connections to the `spaces:vpn` `:wait`, `:info`, and `:config` commands. Previously the vpn connections were not named, but with the introduction of `GET /vpn-connections/:name-or-id`, the commands need to be updated to support name input.
https://github.com/heroku/dogwood/issues/1903

Update vpn wait / info / config

---

packages/spaces/commands/vpn/wait.js
packages/spaces/test/commands/vpn/wait.js

While working on the Direwolf test, @watsonian discovered that `:wait` was hanging although the VPN was available. This is because it was waiting on `available`, not `active` like it should be since we have removed the state and rely on the `status`
closes https://github.com/orgs/heroku/projects/52#card-11188425

spaces: wait should check that the status is active, not available

---

packages/spaces/commands/vpn/index.js
packages/spaces/test/commands/vpn/index.js

Some internal testing and customer private beta VPN connections don't have names. With the latest CLI commands, however, it's only possible to get the ID of an existing VPN connection by using the JSON output.
This updates the `spaces:vpn:connections` command to show the ID in the name field when it's blank, so that legacy VPN connections can still be interacted with.
Closes https://github.com/heroku/dogwood/issues/1936.

spaces: default name to ID in list if missing

---

packages/pipelines-v5/commands/pipelines/setup.js
packages/pipelines-v5/lib/github-api.js
packages/pipelines-v5/lib/kolkrabbi-api.js
packages/pipelines-v5/test/commands/pipelines/setup.js

When running `heroku pipelines:setup`, there's an error (`No source_blob URL provided.`) because GitHub does not return the expected response headers which should point to a tarball. Instead of using GitHub API, we can use Heroku's internal service to retrieve a url for the same tarball for a repository's branch.

change source_blob url to GET from kolkrabbi

---

packages/spaces/commands/vpn/info.js
packages/spaces/test/commands/vpn/info.js
packages/spaces/test/commands/vpn/wait.js

This fixes:
* The name was not being displayed in `display:info` despite it being shown in the example
* If an ID is used to retrieve a VPN connection, the name will be used in the headers if one is present 
Resolves https://github.com/heroku/dogwood/issues/1937

Display the name in vpn:info

---

packages/pipelines-v5/lib/kolkrabbi-api.js

Follow up to https://github.com/heroku/cli/pull/944 since the return payload doesn't have `body`.
Proof that I tested after my last push 😒

get archive_link from payload instead of body

---

packages/pg-v5/commands/credentials/rotate.js

The shogun API for force rotate credential accepts the parameter 'forced'. Currently, the cli passes 'force' which is ignored.
The tests still pass since the payloads were never verified in the test suites. We tried to fix it but we could not get it to work. We're not sure how the `heroku.post` sends the body payload and the `nock` error messages did not explain what was wrong.

Changes 'force' to 'forced'

---

packages/spaces/commands/vpn/index.js
packages/spaces/test/commands/vpn/index.js

This adds a new message that's printed if no VPN connections exist yet rather than just printing an empty table.

Display 'no VPN connections' message if none exist yet

---

packages/spaces/commands/vpn/destroy.js
packages/spaces/test/commands/vpn/destroy.js

Name is now required for destroying a VPN connection. This:
* Requires it as a parameter
* Uses the name as the confirmation method for destroying a VPN
closes https://github.com/orgs/heroku/projects/52#card-11550177

Update vpn:destroy command to require a name

---

packages/spaces/commands/vpn/connect.js
packages/spaces/commands/vpn/destroy.js
packages/spaces/commands/vpn/index.js
packages/spaces/commands/vpn/info.js
packages/spaces/commands/vpn/wait.js

This removes the `hidden` attributes for vpn commands so that there is top-level help, as well as adds some additional information for the `vpn:connect` - I saw some other commands with useful information so I thought I would add some into it. 
Example:
```
$ heroku help spaces:vpn
create VPN
USAGE
$ heroku spaces:vpn:COMMAND
DESCRIPTION
Private Spaces can be connected to another private network via an IPSec VPN connection allowing dynos to connect to hosts on your private networks and vice versa.
The connection is established over the public Internet but all traffic is encrypted using IPSec.
Example:
$ heroku spaces:vpn:connect --name office --ip 35.161.69.30 --cidrs 172.16.0.0/16,10.0.0.0/24 --space my-space
Creating VPN Connection in space my-space... done
▸    Use spaces:vpn:wait to …
```

spaces: add top-level help for spaces:vpn

---

packages/spaces/commands/vpn/wait.js

a `VPN` is now returned as soon as it's created, no longer making the `422` check in `vpn:wait` necessary
closes https://github.com/heroku/dogwood/issues/1819

remove 422 check from vpn:wait

---

packages/spaces/lib/vpn-connections.js

Ensures paths are properly encoded in the event they contain spaces or special characters
Also noticed that some `deleteVPN` code was still present while i was editing that file so I went ahead and removed that.
https://github.com/orgs/heroku/projects/52#card-11649683

Ensure paths are escaped to account for names used as IDs

---

packages/autocomplete/src/commands/autocomplete/create.ts

fix(autocomplete): filepath completions

---

packages/spaces/commands/vpn/wait.js
packages/spaces/test/commands/vpn/wait.js

This fixes an issue where there would be some "waiting" for a VPN to allocate, even if it has already been allocated. This moves the initial call to get the VPN connection outside of the loop to verify whether it is already active and does not wait the specified `interval` before notifying the user.
resolves https://github.com/heroku/dogwood/issues/2003

Check if connection is already active before waiting

---

packages/spaces/lib/peering.js
packages/spaces/test/commands/peering/index.js

Ref: heroku/api#9146
This PR exposes the AWS region of private space peered VPCs: https://trello.com/c/J4V8MxPX/10-vpc-peering-improvements
+ [x] deployment of https://github.com/heroku/dogwood/pull/1966
+ [x] deployment of https://github.com/heroku/api/pull/9705

Expose AWS region of peered VPC connections in CLI

---

packages/spaces/commands/create.js
packages/spaces/test/commands/create.js

This adds a `--data-cidr` flag that specifies the RFC-1918 CIDR that the space will use when peering with DOD's spaces. This is a part of the new choose your own cidr feature.
Closes https://github.com/orgs/heroku/projects/52#card-12137969
Dependent on: https://github.com/heroku/api/pull/9789

Add --data-cidr flag for space creation

---

packages/ci/src/utils/test-run.ts
packages/ci/test/commands/ci/last.test.ts

Found in ticket https://support.heroku.com/tickets/623553.
When a test run is cancelled, the API request for `/test-nodes` returns an empty array. This patches shows a proper error message in that case.
**Before:**
```bash
› heroku sudo ci:info ID --pipeline my-pipeline
TypeError: Cannot read property 'setup_stream_url' of undefined
at renderNodeOutput (~/.local/share/heroku/client/7.12.3/node_modules/@heroku-cli/plugin-ci/lib/utils/test-run.js:143:27)
at Object.displayTestRunInfo (~/.local/share/heroku/client/7.12.3/node_modules/@heroku-cli/plugin-ci/lib/utils/test-run.js:215:19)
at CiInfo.run (~/.local/share/heroku/client/7.12.3/node_modules/@heroku-cli/plugin-ci/lib/commands/ci/info.js:12:26)
```
**Now:**
```bash
› heroku sudo ci:info ID --pipeline my-pipeline
›   Error: Test run ID …
```

Fix error when testNodes is empty

---

packages/ci/src/utils/source.ts
packages/ci/test/commands/ci/run.test.ts

The new `ci:run` had an untested path for new commits that have not yet been pushed to a repo. It's supposed to create a source and upload the archive (like `ci:debug`).
This fixes the bugs and adds a test to help prevent regressions.

fix(ci): unknown local commit path

---

.circleci/config.yml

this shows increases in the build size as a CI status in github so we can catch PRs that blow up the tarballs

chore: pack tarball in test to enable BuildSize

---

.circleci/config.yml
scripts/bundlesize

gzip compresses slightly different each time

chore: unpack tarball for bundlesize

---

packages/spaces/commands/outbound-rules/add.js
packages/spaces/commands/outbound-rules/index.js
packages/spaces/commands/outbound-rules/remove.js

Per https://github.com/heroku/runtime-issues/issues/294 we don't want
these visible since they are unreleased features

fix(spaces): Hide outbound-rules cli commands

---

packages/pg-v5/commands/pull.js
packages/pg-v5/lib/bastion.js
packages/pg-v5/lib/download.js
packages/pg-v5/lib/fetcher.js
packages/pg-v5/lib/pgbackups.js
packages/pg-v5/lib/psql.js
packages/pg-v5/lib/setter.js
packages/pg-v5/lib/util.js
packages/pg-v5/package.json
packages/pg-v5/test/commands/pull.js
packages/pg-v5/test/lib/psql.js
yarn.lock

Fixes: https://github.com/heroku/cli/issues/1073
I don't know if this really will fix the issue, but I do know that before the environment variables were not being passed down so I am pretty sure this is the issue. The user in the ticket had a non-standard pg path using Postgres.app.

fix: pass env vars down to pg_pull/pg_drop

---

packages/certs-v5/lib/format_date.js

This commit adds an extra step in formatting a given date object
in to a string UTC representation. This extra step is required
as `date-fns/format` uses the local time when converting.
For example, my machine is currently in BST (UTC+1):
```js
const obj = {"expires_at":"2018-10-20T21:24:01Z"}
console.log(dateFns.format(new Date(obj.expires_at), "YYYY-MM-DD HH:mm UTC"))
// 2018-10-20 22:24 UTC
```
This results in misleading CLI output. For example:
```
Name        Endpoint                  Common Name(s)  Expires               Trusted  Type
──────────  ────────────────────────  ──────────────  ────────────────────  ───────  ────────
tokyo-1050  tokyo-1050.herokussl.com  example.org     2013-08-01 22:24 UTC  False    Endpoint
```
Here, although the format claims the timestamp is in UTC, it …

fix(certs-v5): correct certs-v5 timezone handling in date formatting

---

packages/container-registry-v5/commands/login.js
packages/container-registry-v5/commands/pull.js
packages/container-registry-v5/commands/push.js
packages/container-registry-v5/commands/release.js
packages/container-registry-v5/commands/rm.js
packages/container-registry-v5/commands/run.js
packages/container-registry-v5/package.json
packages/container-registry-v5/test/commands/login.js
packages/container-registry-v5/test/commands/logout.js
packages/container-registry-v5/test/commands/pull.js
packages/container-registry-v5/test/commands/push.js
packages/container-registry-v5/test/commands/release.js
packages/container-registry-v5/test/commands/rm.js
packages/container-registry-v5/test/commands/run.js

When docker command fails with exit code 1, the CLI still returns 0, creating issues around scripting.  `error` no longer (if it ever did) accepts and error code value, which is why we're NOT returning 1 for failures.  As a result, `error` has been replaced with a call to `exit`, which accepts an exit code.

fix(container): exit with status code 1 for errors

---

packages/pipelines-v5/commands/pipelines/diff.js
packages/pipelines-v5/test/commands/pipelines/diff.js

`pipelines:diff` fetches the releases and compares them. We shouldn't consider a pending or failed release as currently running on the app. Only succeeded ones.

fix(pipelines-v5): Only consider succeeded releases in pipelines:diff

---

packages/run-v5/lib/colorize.js
packages/run-v5/test/colorize.test.js

This fixes: https://github.com/heroku/cli/issues/1158
If a router line has an extra equals such as `path=/foo?bar=baz` the colorization would parse this and colorize it incorrectly. This inverts the parsing to and then checks to see if there are more than one `=` in a part.

fix(apps-v5): Parse router log path correctly

---

packages/pg-v5/commands/bloat.js
packages/pg-v5/commands/blocking.js
packages/pg-v5/commands/locks.js
packages/pg-v5/commands/vacuum_stats.js
packages/pg-v5/index.js

This integrates some of the most used commands from `heroku-pg-extras`, a separate plugin we maintain.
We often point customers to these commands in support tickets, and there's some minor frustration about having to install an additional plugin each time.
I haven't changed the code, just copied it over. The original code didn't have tests, and this stuff changes very rarely, so I have not added any.
https://trello.com/c/MlPn5g4g/1639-move-some-pg-extras-commands-over-to-the-main-cli

feat(pg): integrate the most used pg-extras commands

---

packages/run-v5/lib/colorize.js
packages/run-v5/test/colorize.test.js

Router logs are currently being joined with comma's so a url log looks like this:
```
path="/foo?start,123&next,456"
```
when it should actually be displayed like this
```
path="/foo?start=123&next=456"
```

fix(run-v5): Join parsed router logs correctly

---

packages/ps/src/commands/ps/wait.ts
packages/ps/test/commands/wait.test.ts

This is a first stab at bringing [ps:wait](https://github.com/uhoh-itsmaciek/heroku-ps-wait/) into the mainline CLI. It's pretty rough because I'm not familiar with oclif plugins or TypeScript and didn't find that much in the way of docs, but it's a start--I hope with some feedback I can turn this into something mergeable.

Bring ps:wait into the mainline ps plugin

---

packages/pg-v5/commands/copy.js
packages/pg-v5/test/commands/copy.js

This commit normalises the casing for both config vars and
attachment names when performing a pg:copy. This is required because
it is possible for config vars and/or attachment names to be of
differing cases, resulting in value fetch against the `config` option
failing.
When the request does not contain the expected keys in JSON,
a 500 is returned from Transferatu without explaining the problem,
resulting in poor user experience. This commit attempts to address
one cause of missing `to_url` and `from_url` keys.

fix(pg-v5) normalise casing for pg:copy

---

packages/spaces/commands/create.js
packages/spaces/test/commands/create.js

Runtime is removing the concept of owner pools from space creation. 
This commit should **not** be merged until changes are first made to spacemgr and API.
https://github.com/heroku/runtime-issues/issues/465
https://github.com/heroku/spacemgr/pull/1257
https://github.com/heroku/api/pull/10468

fix(spaces): remove owner_pool

---

packages/run-v5/lib/colorize.js

Totally my personal opinion on this, but I thought I'd throw it out there to see if anyone else felt the same way. I propose changing the request path color in `heroku logs` from blue to green for better readability on dark terminal backgrounds. This change, in my opinion, is also readable on light backgrounds.
From:
To:
Cheers!

chore(cli): change logs request path color from blue to green

---

packages/redis-v5/commands/promote.js
packages/redis-v5/test/commands/promote.js

If the user is attempting to promote a Redis add-on and there already
*is* a REDIS attachment *and* it's the last attachment for that
add-on, we need to first create an alternate attachment (since
creating a new attachment implicitly detaches what was there before,
and the API won't allow us to remove the last attachment implicitly
like this).
Our approach for doing this is naïve and breaks with private Redis
plans (or really any Redis configuration that has additional config
vars) because we rely on counting config vars.
The right solution is probably to look at attachment count for the
existing add-on attached at REDIS explicitly, but as a quick fix we
just look for config vars ending in '_URL' (rather than the total
count of config vars).

fix: Fix redis:promote for private plans

---

packages/pg-v5/commands/repoint.js
packages/pg-v5/index.js
packages/pg-v5/test/commands/repoint.js

This adds a `pg:repoint` command. The command itself is relatively simple, it hits up an endpoint on the postgres api.

feat(pg-v5): add pg:repoint command

---

packages/redis-v5/commands/maxmemory.js

Add the new policies (allkeys-lfu and volatile-lfu) to the help text of the redis subcommand.
These modes are new in redis version 4 and this version is now the default version for redis.
This option is available from this PR heroku/shogun#11388 and will be merged today.

chore(redis-v5) Add new maxmemory policies to the help text for redis

---

packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/index.js
packages/apps-v5/test/commands/apps/create.js
packages/apps-v5/test/commands/apps/index.js
packages/orgs-v5/commands/members/add.js
packages/orgs-v5/commands/members/index.js
packages/orgs-v5/commands/members/remove.js
packages/orgs-v5/commands/members/set.js
packages/orgs-v5/commands/orgs/open.js
packages/orgs-v5/lib/utils.js
packages/orgs-v5/test/commands/members/add.js
packages/orgs-v5/test/commands/members/index.js
packages/orgs-v5/test/commands/members/remove.js
packages/orgs-v5/test/commands/members/set.js
packages/orgs-v5/test/commands/orgs/open.js
packages/pipelines-v5/commands/pipelines/create.js
packages/pipelines-v5/commands/pipelines/setup.js
packages/pipelines-v5/test/commands/pipelines/create.js
packages/pipelines-v5/test/commands/pipelines/setup.js
packages/spaces/commands/create.js
packages/spaces/commands/index.js
packages/spaces/test/commands/create.js
packages/spaces/test/commands/index.js

Relates to:
* Issue #1245 
* Pull Request [`heroku/heroku-cli-command` \#61](https://github.com/heroku/heroku-cli-command/pull/61)
The fix starts with the [Pull Request \#61 on `heroku/heroku-cli-command`](Pull Request [`heroku/heroku-cli-command` \#61](https://github.com/heroku/heroku-cli-command/pull/61)).
Which prioritizes flags over environment variables for the team flag specifically. The team flag will take priority if set, or falling back to its `default` which will go through and check for:
1. `flags.org` (fixed  in PR to be above env variables)
2. `HEROKU_TEAM`
3. `HEROKU_ORGANIZATION`
The second part of this is where this team flag gets used. If a v5 legacy command has a `needOrg` or `wantsOrg` the *team and org* flags will **both** be [setup as `team` …

fix: team flag prioritized over org flag

---

packages/local/tsconfig.json

The `composite` flag is removed from other oclif templates, but the `local` plugin was generated with it. For consistency we will remove it in this PR.
See for the removal of the `composite` flag from the template: https://github.com/oclif/oclif/pull/247

fix(local): Remove composite flag from tsconfig.json

---

packages/pg-v5/commands/backups/schedules.js
packages/pg-v5/test/commands/backups/schedules.js

Support reported an issue where `pg:backups:schedules` returned an exit code of `1` when there were no schedules present, and pointed out that this isn't really an error since not having any schedules is a valid state.
https://heroku.slack.com/archives/CANLMQU3F/p1564667996111100
This PR tweaks the `schedules` command to simply log the error message rather than throw an error.

fix(pg:backups:schedules): don't throw error when there are no backup schedules present

---

packages/cli/README.md

Lerna has changed their domain: https://github.com/lerna/lerna/issues/2033

chore(cli): Update lerna domain in readme

---

docs/apps.md
packages/apps-v5/README.md
packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/stacks/set.js

Since the Cedar-14 stack is EOL, and there might be some users that follow the examples verbatim, without realising it should not be used.

docs(apps-v5): Update create/stack:set examples to use Heroku-18

---

packages/cli/package.json
yarn.lock

I'm not sure if I need to run `npm install` too

chore(cli): upgrade ps-exec plugin to 2.3.6

---

packages/config/src/commands/config/edit.ts
packages/config/test/commands/config/edit.test.ts

If a user has the following config already set up in heroku:
```
NAME=ALICE
EMAIL=
```
and if they used `heroku config:edit` and saved without making any changes, the
`EMAIL` variable would disappear. This commit updates `config:edit` to preserve
any keys with empty strings as values when saving

fix(config): preserve keys whose value is empty

---

packages/pipelines-v5/commands/pipelines/connect.js

https://heroku.support/770115
Looks like we really only have to validate the repo name, not the pipeline name too.

fix(pipelines-v5): only validate repo name for pipelines:connect

---

packages/pipelines/src/commands/pipelines/promote.ts

There is currently an error being thrown about a missing `chai` dependency. While we could use `chai` for assertions, the code assertions we're making in `pipelines:promote` are the same functions that exist on the core `assert` node module, so we can use that instead.

fix(pipelines): Use assert from node instead of chai

---

docs/ci.md
packages/ci/README.md
packages/ci/src/commands/ci/last.ts

update ci:last examples to use `--pipeline` instead of the deprecated `--app` flag (#1137)

fix(ci): update ci:last examples

---

packages/cli/README.md

During the release process the `oclif-dev readme --multi` command failed to produce docs for a command that was missing a dependency. I think this would have been fixed with a `lerna bootstrap` before hand (and possibly with a `rm -rf node_modules` before hand but I'm leaving that out for now).
The other steps include a couple good things to check before running `lerna publish` since there isn't a way to resume when the command bails.

chore(cli): improve README instructions for releasing

---

docs/pg.md
packages/pg-v5/commands/settings/log_connections.js

This exposes the support for toggling log_connections settings in Heroku Postgres now supported by the Heroku Data Team.

feat(pg-v5): Add exposed pg:setting for toggling logging on connection attempts

---

packages/heroku-cli-plugin-apps/package.json
packages/local/package.json
packages/oauth/package.json
packages/pipelines/package.json
packages/run/package.json
packages/webhooks/package.json
yarn.lock

Typescript 3.5 introduces stricter typing that many of our packages fail. We will update them all together in the future.

fix(cli): pin to typescript 3.3.3333

---

packages/buildpacks/test/mocha.opts
packages/cli/test/mocha.opts
packages/heroku-cli-plugin-apps/test/mocha.opts
packages/oauth/test/mocha.opts
packages/webhooks/test/mocha.opts

mocha timeouts of >10secs keep happening frequently enough causing us to have to rerun CI

chore: increase mocha timeout in all packages to 50s

---

packages/apps/package.json
packages/apps/src/commands/domains/add.ts
packages/apps/test/commands/domains/add.test.ts
yarn.lock

Closes https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007rFIYIA2/view
This PR adds multiple SNI endpoint support to `domains:add` by doing the following things:
- Checking for the `allow-multiple-sni-endpoints` feature flag
- Exposing a `--cert` flag that allows users to specify a cert name when adding a domain to an app with multiple certs
- Exposing an interactive UI for choosing with cert to associate with a domain when the app has multiple certs and no cert has been specified.

feat(domains): add multiple SNI endpoint support to `domains:add`

---

packages/pg-v5/commands/copy.js

The confirmation message when copying databases was ambiguous and needed more clarification.

fix(pg-v5): improve pg:copy confirm message

---

packages/apps/package.json
packages/apps/src/commands/domains/add.ts
packages/apps/test/commands/domains/add.test.ts
yarn.lock

This PR is a follow up to https://github.com/heroku/cli/pull/1412
That PR checked for the multiple sni endpoint feature flag by querying the flag directly. Since this feature flag is not publicly available, the request would straight up fail rather than returning a disabled feature flag, causing the command to exit.
This PR addresses that issue by instead querying the list of feature flags for the given app and first checking if the feature is even included before checking if it's enabled.

feat(domains:add): fix feature flag usage

---

packages/pg-v5/commands/copy.js

Reverts heroku/cli#1422
There are a couple issues with the confirmation message
```
heroku pg:copy app1::HEROKU_POSTGRESQL_BLACK_URL DATABASE_URL -a app2
```
Expected Output:
```
Data from BLACK on ⬢ app1 will then be transferred...
```
Current Output:
```
Data from BLACK on ⬢ app2 will then be transferred...
```
The confirm is just using the app argument, but it should use the attachments app name, as they may differ. 
For postgres URLS (dummy example: `postgres://heroku/otherdb`)
```
heroku pg:copy postgres://heroku/otherdb DATABASE_URL -a app2
```
Expected Output (I think something like this?):
```
Data from otherdb on heroku:5432 will then be transferred...
```
Current Output:
```
Data from database otherdb on heroku:5432 on ⬢otherdb  will then be transferred...
```

Revert "fix(pg-v5): improve pg:copy confirm message"

---

packages/apps/src/commands/domains/add.ts
packages/apps/src/commands/domains/clear.ts
packages/apps/src/commands/domains/index.ts
packages/apps/src/commands/domains/info.ts
packages/apps/src/commands/domains/remove.ts
packages/apps/src/commands/domains/update.ts
packages/apps/src/commands/domains/wait.ts
packages/apps/test/commands/domains/update.test.ts
packages/apps/test/commands/domains/wait.test.ts

This PR is a followup to #1407 
Adds a domains:update command to allow for using different certs.
This command also fixes the issue we had with domains:wait, because we accidentally made hostname required which broke a direwolf test script.
GUS item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007rFIsIAM/view

feat(apps): add domains:update command

---

packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/autocomplete/test/commands/autocomplete/create.test.ts
packages/buildpacks/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/git/package.json
packages/oauth/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/run/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

Bumping typescript to 3.7.5 in all the packages. This was needed for https://github.com/heroku/cli/pull/1439
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007tnkAIAQ/view)

chore: bump typescript in all packages

---

packages/apps-v5/package.json
packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/buildpacks/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/git/package.json
packages/local/package.json
packages/oauth/package.json
packages/orgs-v5/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/run-v5/package.json
packages/run/package.json
packages/spaces/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

Bumps `@heroku-cli/command` to 8.3.0 
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007t6OqIAI/view

chore: bump heroku-cli/command to 8.3.0

---

packages/cli/README.md

In order to publish the package members should have access to the correct npm org.

chore: update README with clearer instructions around publishing

---

packages/apps/test/commands/domains/add.test.ts
packages/apps/test/commands/domains/update.test.ts

Updates tests and commands to account for the slightly different API shape for the `domains` endpoint (changed in https://github.com/heroku/api/pull/11426)

chore(domains): tweak api signature for domains

---

packages/apps-v5/src/commands/apps/stacks/set.js
packages/apps-v5/test/commands/apps/stack/set.js

Apps that have never had a deploy (eg empty apps or those that are used to hold add-ons only) switch stacks instantly without the need for a re-deploy of the app (as of heroku/api#10754).
However when upgrading an app's stack via the CLI, the console output previously always indicated a re-deploy was necessary, even for apps where this is now not true.
This has been seen to cause confusion in support tickets.
As such, the redeploy message is now only shown when the response from API indicates that the upgrade is still pending (ie: when `build_stack`, the requested stack, differs from the `stack`, the current app stack).
The `stacks:set` command has also been updated to use `cli.action()`, to prevent the existing lack of output until the API request returns.
Refs …

fix(apps-v5): Fix the stack upgrade confirmation message for add-on only apps

---

.circleci/config.yml
packages/apps-v5/.circleci/config.yml
packages/auth/.circleci/config.yml
packages/certs/.circleci/config.yml
packages/ci/.circleci/config.yml
packages/config/.circleci/config.yml
packages/git/.circleci/config.yml
packages/oauth-v5/.circleci/config.yml
packages/ps/.circleci/config.yml
packages/run-v5/.circleci/config.yml

Global contexts are less safe. The CLI does not appear to use any environment
variables found in  the `org-global` context so let's not use that.

chore(ci): Remove use of the `org-global` context in circle config

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/commands/certs/index.js
packages/certs-v5/lib/endpoints.js
packages/certs-v5/lib/features.js
packages/certs-v5/test/commands/certs/add.js
packages/certs-v5/test/commands/certs/generate.js
packages/certs-v5/test/commands/certs/index.js
packages/certs-v5/test/commands/certs/info.js
packages/certs-v5/test/commands/certs/remove.js
packages/certs-v5/test/commands/certs/shared.js
packages/certs-v5/test/commands/certs/shared_sni.js
packages/certs-v5/test/commands/certs/shared_ssl.js
packages/certs-v5/test/commands/certs/update.js
packages/certs-v5/test/lib/mock_sni_feature.js

closes https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000081661IAA/view
This PR updates the `certs` commands to correctly handle cases where a private space app has been migrated to use SNI endpoints instead of the legacy SSL endpoints.  This change is largely accomplished by checking for the `allow-multiple-sni-endpoints` flag, since any time that flag is true, the app will be using SNI endpoints and not SSL endpoint (even if it's a private space app).
This PR makes the following changes:
- Remove the `certsAndDomains` function from `endpoints.js` since it wasn't actually being used in a way that was functionally different from `all`
- Updates the `all` function from `endpoints.js` to only request sni endpoints when the multiple sni endpoints flag is enabled
- Adds a mock …

fix(certs-v5): handle private spaces sni migrated apps

---

packages/pg-v5/commands/backups/restore.js

The previous regex used unescaped `.` thus allowing more than it should.
Also, `https://www.dropbox.com` could be anywhere in the URL.
---
Notes:
* https://regex101.com/r/P3Hn9n/1
* there many cases `match()` is used that `test()` should be used

fix(pg-v5): wrong regex.

---

packages/apps-v5/package.json
yarn.lock

Fixes `npm i` warnings about `cross-spawn-async`
Fixes #1212 
Note that IMO this isn't a breaking change as long as Node.js < 8 isn't supported.

chore(apps-v5): update term-img to v4.1.0

---

packages/pg-v5/test/lib/psql.js

When calling psql from a spawned process, we were strictly asserting that all args matched, including our own `process.env`. So if a test failed, the failed assertion message would dump the env. This removes the assertion of the env and just tests that the proper flags were passed to the `psql` command.

fix(ci) Don't assert against env passed into `spawn`

---

packages/run-v5/test/commands/console.js
packages/run-v5/test/commands/detached.js
packages/run-v5/test/commands/logs.js
packages/run-v5/test/commands/rake.js
packages/run-v5/test/commands/run.js
packages/run/test/commands/console.test.ts
packages/run/test/commands/logs.test.ts
packages/run/test/commands/rake.test.ts
packages/run/test/commands/run.test.ts
packages/run/test/commands/run/detached.test.ts

Stop using `heroku-run-test-app` and use `heroku-cli-ci-smoke-test-app` instead.

chore(ci): Consolidate use of real heroku apps in test/

---

.github/PULL_REQUEST_TEMPLATE.md
packages/ci-v5/.gitignore
packages/ci-v5/CHANGELOG.md
packages/git/src/git.ts
packages/git/test/lib/git.js

chore: use `https` when possible

---

packages/pipelines/src/commands/pipelines/promote.ts

`cli.action.start` in `pipelines:promote` is swallowing all error messages. This PR removes `action` in-favor of `log` while we investigate.

fix: use cli.log in pipelines:promote

---

.circleci/config.yml

This was run on branches for testing and is now no longer needed.

chore: only run release_homebrew job on tags

---

packages/addons-v5/commands/addons/open.js

Using `addons:open` with sudo on windows shows `ENOENT: no such file or directory, open 'C:\tmp\heroku-sso.html'`. `/tmp` is not available by default in windows. This change uses [os.tmpdir()](https://nodejs.org/api/os.html#os_os_tmpdir) rather than `/tmp`.

fix(addons-v5): Use os.tmpdir() rather than /tmp for cross-platform support - fixes #1506

---

packages/ci-v5/test/commands/ci/config-get-test.js
packages/ci-v5/test/commands/ci/config-index-test.js
packages/ci-v5/test/commands/ci/config-set-test.js
packages/ci-v5/test/commands/ci/config-unset-test.js
packages/ci-v5/test/lib/heroku-api-test.js
packages/ci-v5/test/lib/utils-test.js

Generator functions that are being used for tests don't get ran by the test runner way that is expected. The test using a generator function doesn't run *and* it also won't fail creating a false positive.
The assertion `expect(true).to.be.false()` should fail within a test but with generator function it doesn't.
[
e1f43a0
](https://github.com/heroku/cli/commit/e1f43a0a3ca37a015a60a8fc776ed05d0b2d3db8)
[
b18f7ce
](https://github.com/heroku/cli/commit/b18f7ce2a0a0ca85af88b7121fd04eb9d3502ca2)
* Use regular or `async` functions or returning a promise should work okay, too.
* If yielding promises is required, use `co.wrap` on the function

fix(ci-v5): update tests using generator functions

---

packages/redis-v5/commands/cli.js

Redis 6 has support for native TLS connections. This PR updates the client connection to use the default port when the addon is using Redis 6 (or greater).

feat(redis-v5): use default port for Redis 6

---

packages/spaces/commands/hosts/index.js
packages/spaces/index.js
packages/spaces/lib/format.js
packages/spaces/lib/hosts.js
packages/spaces/test/commands/hosts/index.js
packages/spaces/test/lib/format.js

This adds a new `heroku spaces:hosts` command to list dedicated hosts of a space. It uses a new endpoint that was deployed to API in https://github.com/heroku/api/pull/11648.  
It is currently hidden because it is under development and is only available for one customer. If another customer happens to find it, it's ok, but just something we want to advertise. 
https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B00000088oJUIAY

feat: add spaces:hosts command

---

.circleci/config.yml

This prevents compliance failing when a release job fails.

chore: split test & release CI workflows

---

.circleci/config.yml

lerna and circleci windows don't get along, so run each packages individually.
lerna hangs circle (even on positive tests runs) until the job fails from timeout.

chore: run windows ci outside of lerna

---

packages/buildpacks/src/buildpacks.ts

Assuming `index` is a number, then this should be a safe replacement.

chore(buildpacks): use `Number.isNan` instead of `isNan`

---

.circleci/config.yml

The windows smoke tests step is causing a bunch of downstream headaches (compliance warning from failed CI, broken releases, etc). We have an epic in planning to address these. For now, as the smoke tests are run in other jobs, lets suspend running them on windows.

chore: skip running cli smoke tests on windows

---

packages/redis-v5/commands/cli.js
packages/redis-v5/test/commands/cli.js

Customers using Redis 6 cannot use `heroku redis:cli` to connect to their service. This is because we do not attempt a TLS connection inside the SSH tunnel. This PR checks for the `prefer_native_tls` flag and initializes a TLS client connection, allowing the customer to properly connect.

fix(redis-v5): update bastionConnect function to use prefer_native_tls when true

---

packages/certs-v5/lib/endpoints.js

Fixes the issue described [here](https://heroku.slack.com/archives/CNB38GLV8/p1594646982051900).
There was an oversight in the logic for checking the multiple-sni-endpoints feature flag that was causing it to return false negatives.  This PR fixes that logic.

fix(certs-v5): fix logic for checking multiple sni flag

---

packages/run/src/commands/run/index.ts

Currently, if you run `heroku run <command>` without already being logged in, the CLI freezes and leaves a dyno hanging. This adds a simple API request prior to starting up a dyno in order to force the login flow if needed.

fix(run): force login first if necessary

---

.circleci/config.yml

Causing compliance failure issues. We are currently not releasing macos builds as we work through the Salesforce Apple Dev release process.

chore: suspend macos releasing

---

packages/redis-v5/commands/cli.js
packages/redis-v5/test/commands/cli.js

If an app has several redis addon attachments from different redis addons (which have different billing entities than the app in question), the Heroku Redis addons service will namespace the config vars on the app based on the attachment name.
For example, if we had two attachments for an app (we'll say this is the response from `GET /apps/:app/addon-attachments` for an app with a name of `app-a`):
```json
[
{
"addon": { "name": "heroku-redis-a" },
"app": { "name": "app-a" },
"name": "REDIS"
},
{
"addon": { "name": "heroku-redis-a" },
"app": { "name": "app-b" },
"name": "REDIS_6"
}
]
```
Then the config vars on `app-a` would look something like:
```json
{
"REDIS_URL": "username:password@example.com",
"REDIS_6_URL": "username-redis-6:password-redis-6@redis-6.example.com"
}
```
However, …

fix(redis-v5): use addon's billing app attachment to look up connection

---

.circleci/config.yml
packages/local/bin/bats-test-runner.js
packages/run/bin/bats-test-runner.js

`bats` is already installed via npm (this was introduced in [#1252][1]),
so we don't need to install it in the CircleCI build file. The CircleCI
build file was also installing the original bats, while the [`local`][2] and
[`run`][3] packages install a [fork from npm][4].
In addition, I switched the command inside the bats runners from `npx
bats` (which will download/install the latest binary if `yarn install`
was not already run), to `yarn bats`, which will always use the version
specified in the lockfile. This is more consistent with how we run other
commands anyway.
[1]: https://github.com/heroku/cli/pull/1252
[2]: https://github.com/heroku/cli/blob/62085d32f8fa3574bbe03bba707f1f576a9858bf/packages/local/bin/bats-test-runner.js
[3]: …

chore: don't install bats twice

---

packages/pipelines/src/commands/pipelines/connect.ts
packages/pipelines/src/commands/pipelines/diff.ts
packages/pipelines/src/commands/pipelines/setup.ts
packages/pipelines/src/commands/reviewapps/disable.ts
packages/pipelines/src/commands/reviewapps/enable.ts
packages/pipelines/src/kolkrabbi-api.ts

Currently the KolkrabbiAPI class only reads the auth token on creation of the class. For most instances this is fine, however, if the auth token is stale, and the cli re auths during the command, Kolkrabbi doesn't get the new auth token. for example, if you run `pipelines:diff` while not authenticated, it will first ask you to login, and then run the command, but fail. The next run, it'll pass. This was brought to light through this support ticket. https://heroku.support/903944

fix(pipelines): Change how kolkrabbi gets the auth token.

---

.circleci/config.yml

Previously, windows CI was failing intermittently holding up releases. Now that we have a decent* working solution, require windows CI to pass before releasing.
*but not perfect

chore: add windows job requirement to releasing

---

packages/apps-v5/package.json
packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/buildpacks/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/git/package.json
packages/local/package.json
packages/oauth/package.json
packages/orgs-v5/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/run-v5/package.json
packages/run/package.json
packages/spaces/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

Bump `@heroku-cli/command` to 8.3.1

chore(cli): bump @heroku-cli/command to 8.3.1

---

lerna.json
package.json
packages/cli/package.json
yarn.lock

- The project was inheriting `lerna@^3.18.0` from [packages/cli/package.json][1] due to [yarn hoisting packages from dependencies from workspaces into the root package](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/). Since `packages/cli` doesn't use `lerna` directly, I moved the `devDependency` for yarn into the root workspace package to be more explicit that we depend on lerna.
- The `lerna` field was removed from `lerna.json` as [`lerna` is no longer required and support was removed in Lerna 3][2].
- The [Release Notes Quip Document][3] was updated to use `yarn lerna` instead of just `lerna`. This technically isn't necessary since [lerna will now use the local version of lerna if available][4], but it's probably better to use the exact version of the CLI whenever possible to …

chore: pin lerna in root package's package.json

---

packages/run/src/commands/run/inside.ts

Hide run:inside as it's not a generally usable command and should be hidden

chore(run): hide run:inside

---

snap/snapcraft.yaml

Currently, in the snapcraft CI it is failing to do the comparison, and failing with a syntax error. Testing locally in a snapcraft
container simulating the snapcraftctl pull step, this should fix it.

chore(cli): tweak snapcraft script

---

snap/snapcraft.yaml

Using `snapcraftctl set-version` should work without needing to set the git tag per the [snapcraft examples](https://snapcraft.io/docs/using-external-metadata#heading--scriptlet). Also, setting the git tag when it's already been set upstream before snapcraft pulls the latest changes causes an error.

chore(cli): remove git tag for snapcraft builds

---

.circleci/config.yml

> If you need reproducible dependencies, which is usually the case with
> the continuous integration systems, you should pass
> `--frozen-lockfile` flag.
from: https://classic.yarnpkg.com/en/docs/cli/install/
This will help prevent problems related to not comitting `yarn.lock` updates by failing the build if running `yarn` in CI causes a change to the yarn.lock file. This should catch `yarn.lock` updates that are required but not comitted

chore: ensure yarn lockfile is stable in CI.

---

.circleci/config.yml

Disables the automated snap release job from being part of the `heroku_cli_release` workflow.

chore(cli): disable automated snap release

---

packages/apps/src/commands/domains/add.ts
packages/apps/src/commands/domains/index.ts
packages/apps/src/lib/multiple-sni-feature.ts
packages/apps/test/commands/domains/index.test.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008d2mEIAQ/view
This PR adds a column to the `domains:list` table that show the domain's associated SNI endpoint if the the Multiple SNI endpoints flag is enabled.

feat(domains): show SNI endpoints in domains list

---

packages/certs-v5/lib/endpoints.js
packages/certs-v5/test/lib/mock_sni_feature.js

https://gus.lightning.force.com/lightning/_classic/%2Fa07B0000008dSIoIAM
Update the endpoint lookup logic to only use SNI endpoints when the multi SNI flag is enabled AND the app is a private space app. This helps to address an API issue with the ssl endpoints addon.

fix(certs-v5): check if an app is a private space app when using SNI endpoints

---

packages/apps/src/commands/domains/add.ts
packages/apps/test/commands/domains/add.test.ts
packages/apps/test/helpers/init.js

This PR updates the logic involved in deciding when to show an SNI endpoint interactive prompt for `domains:add`.
Previously, the API would return an error response indicating that a cert was required, which we'd catch and then use as the trigger for the prompt. However, now that API is no longer performing this check, we now show the cert picker whenever a cert has not been passed AND the app has more than 1 cert on it.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008d2nCIAQ/view

(fix: domains) fix logic for SNI endpoint selection

---

packages/pg-v5/commands/pull.js
packages/pg-v5/test/commands/pull.js

Data recently added an internal-only schema called `_heroku` to Postgres databases that have enabled Data Connectors. The schema privileges are restricted, which results in an error when trying to use `pg:pull`. This PR updates the pull command to always exclude the `_heroku` schema.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000089frJIAQ/view

fix(pg-v5): exclude the internal _heroku schema from pg dump

---

packages/cli/package.json
packages/cli/src/hooks/init/terms-of-service.ts
packages/cli/test/hooks/terms-of-service.test.ts

This should not be released until
10/1/2020
Heroku's terms of service are being covered by Salesforce's  Master Subscription Agreement. This legal change is requiring all users to accept these new terms of service in Dashboard.
This change adds a `std error` message before any command to let users know they should update their terms of service.
Users will only ever see this warning the first time they run a command after updating to this version.
- Clone the Repo
- Check out this branch `git checkout mc/lp/tos-banner`
- run `./bin/run apps`
- See warning banner display before the "apps" output
- Run `./bin/run apps` again
- You should not see the banner
https://gus.my.salesforce.com/a07B0000008XUeBIAW

feat(cli): add warning to accept new terms of service

---

packages/redis-v5/commands/keyspace-notifications.js
packages/redis-v5/index.js
packages/redis-v5/test/commands/keyspace-notifications.js

Creates a new command for Redis.
```
heroku redis:keyspace-notifications HEROKU_REDIS_CPURCELL_GREEN_URL -c 'AKE' -a cp-testing
```
Adds another field to the info command
```
heroku redis:info -a cp-testing
=== redis-cpurcell-aerodynamic-53841 (HEROKU_REDIS_CPURCELL_GREEN_URL)
Plan:                   Premium 0
Status:                 available
Created:                2020-09-10 18:39
Version:                6.0.6
Timeout:                300
Maxmemory:              noeviction
Maintenance:            not required
Maintenance window:     Wednesdays 18:00 to 22:00 UTC
Persistence:            AOF
HA Status:              Available
Requires TLS:           Yes
Keyspace Notifications: AKE
=== redis-cpurcell-spherical-17414 (HEROKU_REDIS_CPURCELL_PUCE_URL)
Plan:                   Premium 0
Status: …
```

feat(redis-v5): add new command to enable keyspace notifications

---

packages/auth/src/commands/auth/2fa/generate-recovery-codes.ts

GUS: https://gus.my.salesforce.com/a07B0000008TzhqIAC
We are moving away from Heroku 2FA to integrating with VaaS (Verification-as-a-Service). Generating recovery codes will happen in VaaS' interface, so we plan to remove the cli command `heroku auth:2fa:generate-recovery-codes`. Our research indicates this is rarely used, so we are not replacing it (see https://gus.lightning.force.com/lightning/r/0D5B000001Bmu1yKAB/view => we concluded it is currently used perhaps once/day).

feat(auth): add a deprecation warning to generate-recovery-codes

---

packages/auth/src/commands/auth/2fa/disable.ts

* Soon, we will roll out a beta where users can have MFA/2FA for their
Heroku Accounts using VaaS (verification as a service), a Salesforce
platform that all clouds are adopting.
* In the next few months, we will migrate all existing Heroku 2FA users
over to VaaS. The login experience will still be very similar for
these users, but they will be verifying themselves via the VaaS redirect
interface rather than on the Heroku home-grown 2FA flow.
* Users who are migrated over may not even know it, so they may attempt
to disable MFA via CLI. While technically we could do some trickery
with the VaaS Admin API to make this possible, the intent of VaaS is
that users go into the VaaS manage page, which is accessible via the
Heroku Dashboard, to do all verifier management.
* This CLI command is …

Add helpful error message for VaaS MFA users

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/lib/endpoints.js
packages/certs-v5/lib/features.js

This PR addresses an issue in the logic for requesting cert resources that was discovered in https://heroku.support/928500.
tl;dr: This PR updates the certs `endpoints` util function to use the new `private-spaces-sni` feature flag rather than using a bunch of roundabout logic that ended up not even really working.
The issue essentially boils down to the fact that we have both `sni-endpoints` and `ssl-endpoints`, each of which are used (or not) depending on various other circumstances (feature flags, private space apps, presence of the legacy SSL addon on the app, etc.).
The CLI originally accounted for this by *always* making requests to both endpoints no matter what and simply combining and filtering the results into a single list. This works in many cases, but breaks in the case where …

fix(certs-v5): fix logic for requesting all cert resources

---

packages/certs-v5/commands/certs/info.js
packages/certs-v5/lib/certificate_details.js
packages/certs-v5/lib/display_table.js
packages/certs-v5/test/commands/certs/index.js

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008dFwjIAE/view
This PR adds two new pieces of functionality:
1. The `certs` command will now show a count of associated domains for each cert in the list
2. The `certs:info` command now has an optional `--show-domains` flag which, when used, will request and display the names of all the domains associated with the cert in question.

feat(certs-v5): add domain info in certs list and info

---

packages/apps/src/commands/domains/update.ts
packages/apps/test/commands/domains/update.test.ts

Closes https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008hTd9IAE/view
This PR un-hides the `domains:update` command and changes the certificate flag name from `cert-id` to `cert` now that we've got the `domains` endpoint accepts both name and ID when associating a cert.
This actual command has been in CLI for a while and has actually been used (successfully) by Herokai, this PR is simply making it more widely available rather than adding any new functionality.

feat(domains): make `domains:update` public

---

packages/pipelines/src/api.ts

This fixes an issue where pipeline promotion fails due to the number of apps returned by the filter API gets cut off at the default (200). This raises that max to 1000.

fix(pipelines): Make sure apps from filter returned doesn't get cut off

---

packages/apps-v5/src/commands/apps/info.js
packages/apps-v5/test/commands/apps/info.js

[W-8376731](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008VarXIAS/view)
This should have been removed long time ago, when [I added this warning](https://github.com/heroku/cli/commit/8c4ed7ee392198d34bc35988e3c1f663c82139fa), but never came back to this: .
Thank you to @BigAlUK for raising this issue in [Slack](https://heroku.slack.com/archives/C012K4TFP61/p1604075283179500)

chore(apps:info): Remove deprecation warning

---

packages/pipelines/src/api.ts

Recent PR introduced a bug when requesting a max in the range header. This fixes the bug by adding 'id..', which is required.

Fix range header bug

---

packages/pg-v5/commands/diagnose.js
packages/pg-v5/lib/util.js
packages/pg-v5/package.json
packages/pg-v5/test/commands/diagnose.js
yarn.lock

Fixes https://heroku.support/934830.
Better explained by @iriberri:
> The problem is that we’ll always get the connection string that’s in the first *_URL config var, ordered alphabetically, instead of explicitly looking for `DATABASE_URL` or any other attachment name (`HEROKU_POSTGRES_ROSE_URL`).
> 
> In [this ticket](https://heroku.support/934830), this conflicted with the config vars we create for PrivateLink setups, which happen to be the first alphabetically. Another ticket we had in the past was the case where a customer had a `DATABASE_S3_URL` manually set up, which was pointing to something unrelated and external, and that config var was picked up before DATABASE_URL because of us getting the first result in the array,

fix(pg-v5): Running diagnose on not default DBs

---

packages/pg-v5/lib/psql.js

This is to address an issue when using a private db for more than 10 minutes, and ctrl+c fails to exit.
https://heroku.support/939668

fix(pg): process.exit when SIGINT is caught

---

packages/auth/src/commands/auth/2fa/generate-recovery-codes.ts

* Must be deployed after 11/22
* Removes functionality and returns error message only
* Month 2 of https://salesforce.quip.com/r2DjA7QLgHsu ("don’t let the
command run & provide a response that points users to new command"
* Next step will be to remove entirely
* https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B0000008gvwKIAQ

feat(auth): Update generate-recovery-codes deprecation message

---

packages/apps/src/commands/domains/add.ts
packages/apps/src/commands/domains/update.ts
packages/certs-v5/commands/certs/add.js
packages/certs-v5/commands/certs/info.js

There is no variant needed for the `heroku domains:update` command any more.
Internal ref: https://github.com/heroku/api/pull/11773

fix(apps domains): No variant needed for domains:update now

---

package.json
packages/pg-v5/commands/psql.js
packages/pg-v5/lib/bastion.js
packages/pg-v5/lib/psql.js
packages/pg-v5/test/lib/psql.js
yarn.lock

https://heroku.support/939668
[W-8530613](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kgP4IAI/view)
In the case that the following events happen:
* `heroku pg:psql` is run on a **private-tier** (not shield) postgres plan  in a **private space** 
* Connection to postgres server times out (leave terminal open for 10-15 minutes to reproduce this)
* When psql reconnects due to timeout
* And user exits program (ctrl+D or types `exit` or `\q` into psql terminal)
* psql exits successfully
Then the heroku CLI process should exit. Before this commit, the process would hang because the tunnel created by the `tunnel-ssh` package does not seem to close itself in this scenario of reconnection. This PR does a bit of refactoring so we can retain a reference to the `tunnel-ssh` …

fix(pg-v5): Properly close ssh connection

---

packages/pg-v5/commands/connection_pooling.js
packages/pg-v5/test/commands/connection_pooling.js

We only support default credential for connection pooling atm. Disallow non-default credentials

fix(pg-v5) only support default credential for connection pooling

---

packages/pg-v5/commands/psql.js
packages/pg-v5/lib/psql.js
packages/pg-v5/test/commands/ps.js
packages/pg-v5/test/lib/psql.js

https://heroku.support/945120
In [PR #1691][1], some refactoring was done to make the way psql is executed more consistent. Unfortunately, this ended up in a regression for commands that were expecting the result of `PSQL.exec` to return a promise that resolved with the result of the psql child_process's stdout stream. Previously `PSQL.exec`'s resolved value would be a string. While the output is displayed, some commands, [like `ps` were looking at the return result of `psql.exec`][2]. Because #1691 made this return `undefined`, rather than a `string`, downstream commands like `ps` or others now error.
This changes the behavior in `packages/pg-v5/lib/psql.js` back to what it was doing before:
- Resolve the promise returned from `psql.exec` with the value of the psql child_process's …

fix(pg-v5): return child process stdout

---

packages/config/src/commands/config/edit.ts

When sharing the output from `config:diff` that does not preserve the CLI coloring, it is difficult to determine _what_ was changed:
```
Config Diff:
IMPORTANT_SETTING=true
IMPORTANT_SETTING=false
```
This PR adds additional context showing the +/- of the diff:
```
Config Diff:
- IMPORTANT_SETTING=true
+ IMPORTANT_SETTING=false
```

feat(config): add +/- context to config:edit output

---

docs/apps.md
packages/apps-v5/README.md
packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/stacks/set.js
packages/apps-v5/test/commands/apps/info.js
packages/apps-v5/test/commands/apps/stack/set.js

Since we're about to make Heroku-20 the default stack, which updates the response from API and so the docs examples here.
Closes [W-8505333](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kEPtIAM/view).

feat(apps-v5): Update create/stack:set examples to use Heroku-20

---

scripts/create-release-pr
scripts/publish-release

Takes the steps outlined in https://salesforce.quip.com/aPLDA1ZwjNlW and creates some scripts that automate some of the steps so we don't have to figure this out manually every time.
Added two scripts:
- `scripts/create-release-pr`
- Creates a new branch (so a pull request can be opened)
- Bumps the version and generates new changelogs using `yarn lerna version`
- Opens a pull request
- `scripts/publish-release`
- Checks that the script is only run on the main branch (`master` at the time of this writing)
- Pulls down the latest Git branches/tags from GitHub
- Creates a new tag based off of the version in `lerna.json`
- Pushes tag to GitHub
- Publishes packages to NPM
- Creates a GitHub release with the correct release notes of things that changed based off of Git commit history
Here's …

build: add release scripts

---

packages/redis-v5/commands/cli.js
packages/redis-v5/test/commands/cli.js

For hobby, the TLS url is exposed in a separate config _TLS_URL. This PR fixes the bug where we are trying to connect over TLS with the plaintext URL for versions supporting TLS.

fix(redis-v5) Use TLS_URL for hobby dev if version supports TLS

---

scripts/create-release-pr
scripts/publish-release

If someone has released the CLI locally, they'll have a tag name for the release that gets pulled from origin. Using `--force` is the only way to override the local tag with the tag from GitHub, which should be the canonical source of truth anyway and not cause conflicts since it should be the same tag.
`git branch --show-current` is only available in Git >= 2.22. Changing this to `git rev-parse --abbrev-ref HEAD` works in all versions and reduces friction when running the release script.

build: Release script fixes

---

docs/git.md
packages/git/src/commands/git/remote.ts

The example of adding a new remote with a custom alias stated that the remote URL was `https://git.heroku.com/example-staging.git`, but the command was pointing to `https://git.heroku.com/example.git`.
I've updated the example to use the same remote URL as the previous example, so that the only difference is the addition of the `--remote` argument.

docs(git): Fix a mistake in git:remote examples

---

packages/apps-v5/src/commands/apps/info.js
packages/apps-v5/test/commands/apps/info.js

[775c679dd069342074cfbb96fea887e72db1c4f7][1] removed the `pipeline` object from the `info` object used to render the display in `apps:info` to fix a deprecation warning. Unfortunately, it seems like this introduced a regression as code that was referencing `info.pipeline` was not updated to use `info.pipeline_coupling`, resulting in runtime exceptions due to trying to access a property off of `undefined`.
Work Item: [W-8780887][2]
[1]: https://github.com/heroku/cli/commit/775c679dd069342074cfbb96fea887e72db1c4f7
[2]: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000094UCiIAM/view

fix(apps-v5): get pipeline stage from `pipeline_coupling`

---

packages/addons-v5/package.json
packages/apps-v5/package.json
packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/buildpacks/package.json
packages/certs-v5/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/container-registry-v5/package.json
packages/git/package.json
packages/local/package.json
packages/oauth-v5/package.json
packages/oauth/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/run/package.json
packages/spaces/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

Bump `@heroku-cli/command` and `@oclif/plugin-legacy` to include the changes to `@heroku-cli/command` made in https://github.com/heroku/heroku-cli-command/pull/79

chore(cli): bump @heroku-cli/command and @oclif/plugin-legacy

---

packages/pg-v5/commands/diagnose.js
packages/pg-v5/test/commands/diagnose.js

Heroku Postgres has some plans that have burstable performance
characteristics
(https://devcenter.heroku.com/articles/heroku-postgres-production-tier-technical-characterization#performance-characteristics).
Whether or not a given resource is bursting, or at risk at throttling,
has previously not been available to end users. This commit changes
this, by providing burst data to the `pg:diagnose` backend for relevant
resources, and returning it in the report.
This commit also adds JSON output support, for when the table output is
not appropriate and to provide some interop with tools like `jq`.
Ref: GUS-W-8906686

feat(pg-v5): add burst checks, json output to diagnose

---

packages/addons-v5/lib/addons_wait.js
packages/addons-v5/package.json
packages/certs-v5/package.json
packages/ci-v5/lib/test-run.js
packages/ci-v5/package.json
packages/pg-v5/lib/pgbackups.js
packages/pg-v5/package.json
yarn.lock

When `co` was removed in [#1746](https://github.com/heroku/cli/pull/1746), we did not remove `co-wait` since it was assumed to have used promises under the hood. It turns out that `co-wait` [returns a function](https://github.com/juliangruber/co-wait/blob/master/index.js#L11) that `co` knew how to call instead. When we switched to `async/await`, we stopped waiting since we didn't call the function returned by `co-wait`. We can remove the `co-wait` dependency by using the JavaScript standard library one-liner of `await new Promise((resolve) => setTimeout(resolve, timeInMS)`.
https://heroku.support/965732

fix(ci-v5,addons-v5,pg-v5,certs-v5): remove co-wait

---

packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/commands/ps/type.js

This PR is to add a total dynos section to `ps:type`. This helps when a large number of custom processes makes it difficult to see the total number of dynos running for an application (without checking through the dashboard). 
Example output below:
```
=== Dyno Types
type   size           qty  cost/mo
─────  ─────────────  ───  ───────
test   Standard-1X    2    50
test1  Standard-1X    3    75
test2  Standard-2X    1    50
web    Performance-M  1    250
=== Dyno Totals
type           total
─────────────  ─────
Standard-1X    5
Standard-2X    1
Performance-M  1
```

feat(ps-v5): Add total dynos table to ps:type output

---

packages/redis-v5/commands/cli.js
packages/redis-v5/test/commands/cli.js

Using `heroku redis:cli` with Heroku Redis Shield plans is not supported. Exit with an error and guide users toward DevCenter for more information.
[W-8974490](https://gus.lightning.force.com/a07B0000008xDSPIA2)

feat(redis-v5): exit if trying to use redis:cli with shield plan

---

scripts/release/homebrew/templates/heroku-node.rb
scripts/release/homebrew/templates/heroku.rb

Bringing in https://github.com/heroku/cli/pull/1769 as a new PR so our internal CI integrations can pass

fix: correct path to node for homebrew install

---

scripts/release/homebrew.js

https://github.com/heroku/cli/commit/7526130c045bcf7ac2f28556ad93e61a3b0d3942 introduced a new build script for Homebrew. It generates the right files
but doesn't commit the changes before pushing :facepalm:.
The SHA256 was also calculated incorrectly due to use of the streaming api. Using `hash.setEncoding('hex')` and using `hash.read` at the end returns the correct SHA256 sum for a file
GUS: [W-8984115][1]
[1]: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008xKCsIAM/view

build: fix homebrew release script by actually comitting changes

---

packages/apps-v5/src/commands/apps/stacks/set.js
packages/apps-v5/test/commands/apps/stack/set.js

Previously the `stack:set` command's output mentioned needing to create a "new release" in order to complete the stack change.
However this is incorrect - a new build needs to be performed, so the wording has been updated accordingly.
In addition, the usage text has been updated so that it matches the actual output from the command.
Closes GUS-W-8797527.

fix(apps-v5): Improve UX of stack:set command output

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/lib/endpoints.js
packages/certs-v5/test/commands/certs/add.js
packages/certs-v5/test/commands/certs/index.js
packages/certs-v5/test/commands/certs/remove.js
packages/certs-v5/test/commands/certs/shared_sni.js

Deprecating the `sni_ssl_cert` variant, which is no longer needed. Not sure if this is the way I should be conditionally setting up the headers -- https://github.com/heroku/cli/pull/1775/files#diff-2cd45100c77a5e44846f941a495e2ed915af0d5fabc5987ed2359b3826c6823bR238-R243 and https://github.com/heroku/cli/pull/1775/files#diff-03a3898d724b1554d1adf274591a483a6cfbaca87146dc91b3a5cec49e4ff760R42-R46
Please advise on the best way to do this, then I'll finish up the other places we make these requests. Thanks!

Remove sni_ssl_cert variant

---

packages/redis-v5/commands/index.js
packages/redis-v5/commands/info.js
packages/redis-v5/lib/shared.js
packages/redis-v5/test/commands/info.js

Some customers are parsing the output of `redis:info` from the CLI in
order to get metadata about their Redis add-ons. In order to ease this
in lieu of a public API endpoint, lets add a JSON output for this
information.
Sample output:
```json
[
{
"addon_id": "01234567-8901-2345-6789-012345678901",
"name": "redis-adjective-123456",
"plan": "hobby-dev",
"created_at": "2021-04-08T11:15:25.989+00:00",
"resource_url": "[REDACTED]",
"info": [
{
"name": "Plan",
"values": [
"Hobby Dev"
]
},
{
"name": "Status",
"values": [
"available"
]
},
{
"name": "Created",
"values": [
"2021-04-08 11:15 "
]
},
{
"name": "Version",
"values": [
"6.0.12"
]
},
{
"name": "Timeout",
"values": [
300
]
},
{
"name": "Maxmemory",
"values": [
"noeviction"
]
},
{
"name": "Maintenance",
"values": [
"not required"
]
},
{ …
```

feat(redis-v5): add JSON output to redis:info

---

.circleci/config.yml
packages/cli/package.json
packages/run-v5/test/init.js
scripts/pack/deb
scripts/postrelease/install_scripts
scripts/release/deb
scripts/release/tarballs
scripts/sign/deb
yarn.lock

ci: update ci workflow

---

packages/apps-v5/src/error_info.js

We've added a new H code in Runtime land - https://devcenter.heroku.com/articles/error-codes#h31-misdirected-request-error

Adding H31

---

packages/redis-v5/commands/cli.js

Users of hobby-dev redis have access to native TLS functionality in versions 6 and higher. If a redis version supports native TLS, we should not warn the user that the connection is insecure.

fix(redis-v5): allow hobby-dev redis:cli use tls connection

---

.circleci/config.yml

This was removed due to comment shuffling in
https://github.com/heroku/cli/pull/1797, but the S3 credentials are
necessary to purge the cloudfront CDN's cache

ci: restore aws credentials to invalidate-cdn-cache job

---

packages/apps-v5/src/commands/apps/rename.js
packages/apps-v5/test/commands/apps/rename.js

Adding a message that SSL certificate provisioning may take a few minutes when renaming an app if the `web_url` is `http` instead of `https`
To verify:
- Tests pass
- Code looks good

fix(apps-v5): add message for SSL Certificate provisioning delay for apps:rename

---

docs/auth.md
packages/auth/README.md
packages/auth/package.json
packages/auth/src/commands/auth/login.ts
yarn.lock

This changes the `auth:login` help to say that logins expire after 30 days instead of 1 year. This matches the code changes in https://github.com/heroku/front_end_auth/pull/243 and https://github.com/heroku/heroku-cli-command/pull/81.
[GUS](https://gus.my.salesforce.com/a07AH000000BD07YAG)

Change CLI login default to 30 days

---

packages/pg-v5/lib/psql.js
packages/pg-v5/test/lib/psql.js

This PR adds an optional arg to `psql.exec` so that the user can specify additional arguments to the psql process.
I am specifically interested in this for providing the `-q` and `-t` args in order to have more consistent query output, but I'm sure it is useful in other ways.

FEAT(packages/pg-v5): Allow additional psql args

---

packages/apps-v5/src/commands/ps/index.js
packages/apps-v5/test/commands/ps/index.js

I'm adding support for a new extended attribute to the API which
includes the execution plane a dyno is currently or intended to be run
on.

feat(apps-v5): add execution plane to dyno list as extended attribute

---

packages/certs-v5/lib/display_table.js
packages/certs-v5/test/commands/certs/index.js
packages/certs-v5/test/stubs/sni-endpoints.js

As requested by Product, display the display_name attribute, if present on any cert, in the certs table.
SOC2:
https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07AH000000OuSuYAK

feat(certs-v5): Add display name to certs table

---

packages/run-v5/lib/dyno.js
packages/run/src/lib/dyno.ts

Right now it is hard to debug SSH connection issues on heroku run.
This will output the ssh debug information if we run the command in debug mode
GUS: [W-9537346
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000PxaKYAS/view)

fix(run-v5) Add Debug ssh flags

---

packages/redis-v5/commands/stats-reset.js
packages/redis-v5/index.js
packages/redis-v5/test/commands/stats-reset.js

This commit adds a command to reset statistics for a specific Heroku
Redis add-on, covering the stats outlined in
https://redis.io/commands/config-resetstat.
This is irreversible, so by default this requires confirmation, and
otherwise uses a `--confirm` flag to override it.
Ref: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000OiyXYAS/view

feat(redis-v5): add redis:stats-reset command

---

packages/pg-v5/lib/fetcher.js
packages/pg-v5/test/lib/fetcher.js

Now that the data team uses multiple control plane not all commands can correctly resolve the add-on.
Before:
```
HEROKU_POSTGRESQL_HOST="control-plane2.heroku.com" HEROKU_POSTGRESQL_ADDON_NAME=heroku-postgresql-meta heroku pg:ps -a shogun
▸    Ambiguous identifier; multiple matching add-ons found: DOD_HVAS_DATABASE, ARCHIVE_DATABASE.
```
After:
```
HEROKU_POSTGRESQL_HOST="control-plane2.heroku.com" HEROKU_POSTGRESQL_ADDON_NAME=heroku-postgresql-meta ./bin/run pg:ps -a shogun
pid  |        state        |             source             |    username    |   running_for    |       transaction_start       | waiting |
<redacted>
```

fix(pg-v5): add an environment variable for which addon service to resolve

---

packages/pg-v5/commands/settings/track_functions.js
packages/pg-v5/index.js

This commit adds the front end to a newly exposed setting for Heroku
Postgres, allowing users to change the value for the GUC
`track_functions`. This allows users to gather statistics for different
types of function invocations, if they so choose.
Ref: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000U0wTYAS/view

feat(pg-v5): Add pg:settings:track-functions

---

packages/redis-v5/README.md
packages/redis-v5/commands/upgrade.js
packages/redis-v5/index.js
packages/redis-v5/test/commands/upgrade.js

This PR adds a new `redis:upgrade` command that permit users to perform in-place upgrades of their Heroku Redis add-on.

feat(redis-v5): add redis:upgrade command

---

packages/pg-v5/commands/copy.js
packages/pg-v5/lib/util.js
packages/pg-v5/test/lib/fetcher.js

For operations such as pg:psql, we have been assuming that the URL parsed `path` method is enough to find the database name. This is incorrect when we pass parameters such as `sslmode`. In general, this problem has been solved with `parsePostgresConnectionString` but not everything uses it.
This fix removes any custom parsing we are doing of URLs and moves to using this function everywhere to avoid inconsistency.
* util.databaseNameFromUrl
* util.getConnectionDetails
* the pg:copy resolver
Without this, `pg:psql` was failing on verify-full URL's but with this patch, it works fine.

fix(pg-v5): Fix databasename for URLs with query element and be more consistent

---

packages/pg-v5/commands/credentials.js

The `--reset` flag no longer works with the `pg:credentials` command. This PR removes the flag.

fix(pg-v5): remove reset flag from pg:credentials

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/commands/certs/update.js

https://heroku.support/1069282
It was brought to our attention in this support ticket that our help documentation is outdated for cert:add and cert:update. Intermediate certificates are no longer allowed without bundling.

fix(docs): update cert:add / cert:update help to reflect changes to intermediate certificates

---

.circleci/config.yml

There's a yarn issue where the latest version of yarn for windows is not being published, resulting in this test failure:
https://app.circleci.com/pipelines/github/heroku/cli/1179/workflows/b638f0e8-4778-4f5a-b6dd-ec0d1e85a1c1/jobs/8444?invite=true#step-102-5
But yarn is being installed as a dependency already so this extra installation step is unnecessary.

fix(ci): fix windows tests

---

packages/container-registry-v5/lib/streamer.js
packages/container-registry-v5/package.json
packages/container-registry-v5/test/streamer.js

Fix for https://heroku.support/1081019
Increase the time we wait for the container logs to be available from 10 seconds to 30 seconds.

fix(container-registry-v5): Increase number of retries when fetching container logs

---

.circleci/config.yml
scripts/sign/deb

We removed the custom ci docker image in #1968 but need this few packages in certain jobs

fix: add missing circle ci apt packages

---

docs/apps.md
packages/apps-v5/README.md
packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/stacks/set.js
packages/apps-v5/test/commands/apps/info.js
packages/apps-v5/test/commands/apps/stack/set.js

The Heroku CLI's help text refers to Heroku-20 in a few of the examples. eg:
```
$ heroku stack:set heroku-20 -a myapp
Setting stack to heroku-20... done
You will need to redeploy myapp for the change to take effect.
Run git push heroku main to trigger a new build on myapp.
```
This updates it to use Heroku-22 instead.
See:
https://github.com/heroku/cli/search?q=heroku-20
GUS-W-10349673

chore Update heroku-20 to heroku-22

---

packages/pg-v5/commands/outliers.js

Following https://devcenter.heroku.com/changelog-items/2446
We need to also include `heroku_ext` here.
Testing on a new db:
```
ds9aic4ustc1f=> SELECT exists(
SELECT 1 FROM pg_extension e LEFT JOIN pg_namespace n ON n.oid = e.extnamespace
WHERE e.extname='pg_stat_statements' AND n.nspname = 'public'
);
exists 
--------
f
(1 row)
ds9aic4ustc1f=> SELECT exists(
SELECT 1 FROM pg_extension e LEFT JOIN pg_namespace n ON n.oid = e.extnamespace
WHERE e.extname='pg_stat_statements' AND n.nspname = 'heroku_ext'
);
exists 
--------
t
(1 row)
ds9aic4ustc1f=> SELECT exists(
SELECT 1 FROM pg_extension e LEFT JOIN pg_namespace n ON n.oid = e.extnamespace
WHERE e.extname='pg_stat_statements' AND n.nspname IN ('heroku_ext', 'public')
);
exists 
--------
t
(1 row)
```

fix (pg-v5): Look for pg_stat_statements in heroku_ext

---

packages/pg-v5/commands/backups/restore.js
packages/pg-v5/commands/reset.js
packages/pg-v5/test/commands/backups/restore.js
packages/pg-v5/test/commands/reset.js

This adds support for a new flag on the `pg:backups:restore` and `pg:reset` commands to specify a list of extensions to pre-install before restoring the backup.

feat(pg-v5): accept a list of extensions to pre-install for pg:backups:restore and pg:reset

---

.circleci/config.yml
.github/workflows/ci.yml
package.json
packages/cli/package.json
packages/pg-v5/test/commands/pull.js
scripts/release/deb
scripts/sign/deb
yarn.lock

This PR ports our current circle ci config to use github actions.
A few notes:
1. The jobs are significantly slower in GHA
2. The order is slightly rearranged to have packing and signing run in parallel to the tests, this helps speed up the suite 10minutes
3. The GHA UI leaves a lot to be desired, it shows ALL jobs even if they are not run on the commit via branch & tag whitelisting
4. I've kept the old CircleCI config for references

chore: switch to github actions for tests

---

packages/certs-v5/test/commands/certs/generate.js

This removes a some unused references to ssl-endpoints.

chore(certs-v5) remove ssl-endpoint references in tests

---

packages/pg-v5/commands/outliers.js
packages/pg-v5/lib/psql.js
packages/pg-v5/test/commands/outliers.js
packages/pg-v5/test/lib/psql.js

Postgres version 13 and newer removed the `total_time` field from `pg_stat_statements` and replaced it with `total_exec_time`. This PR updates the command to fetch the postgres server version, and use an outliers query appropriate for the version.
Testing against an older and a newer postgres database:
```
$ hdev pg:outliers HOBBY_11_URL -a jwadsworth-dev
┌─────────────────┬────────────────┬────────┬─────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│ total_exec_time │ prop_exec_time │ ncalls │  sync_io_time   │                                        query                                        │
├─────────────────┼────────────────┼────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────────── …
```

fix(pg-v5): use a different outliers query for new pg versions

---

packages/addons-v5/index.js

This updates the postgres data plan examples from a previous [PR](https://github.com/heroku/cli/pull/2041/files#diff-2c1fd3b7650cf571b1499c50bbeafe883a36e284941b4478c0344870c2486b83R12) to consistently reflect the new Mini postgres plan rolling out nov 28.
[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000017pSMjYAM/view)

chore(addons-v5): update from hobby-basic to mini plan

---

packages/addons-v5/package.json
packages/addons-v5/test/commands/addons/create.js
yarn.lock

- add oclif/core dependency
- remove oclif/dev-cli and oclif/plugin-legacy dependencies
- replace oclif/config with oclif/core in create.js test file
closes #2089

fix(addons-v5): migrate addons-v5 package to OCLIF/core

---

.github/workflows/ci.yml
scripts/postrelease/change_management
scripts/postrelease/install_scripts
scripts/postrelease/invalidate_cdn_cache
scripts/release/homebrew.js
scripts/utils/_github_setup
scripts/utils/_update_channel.js

[W-12049376](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001CS9owYAD/view)
Replace circle env vars in the release scripts with their gha equivalents.

chore(ci): replace circle env vars with gha env vars in release scripts

---

.github/workflows/ci.yml
packages/addons-v5/package.json
packages/apps-v5/package.json
packages/auth/package.json
packages/buildpacks/package.json
packages/certs-v5/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/config/package.json
packages/container-registry-v5/package.json
packages/git/package.json
packages/oauth-v5/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/ps/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/spaces/package.json
packages/status/package.json
yarn.lock

Use recently published fix for debian builds https://github.com/heroku/dev-cli
Re-enable debian workflows.
Previously failing deb_pack now working. Workflow here: https://github.com/heroku/cli/actions/runs/3440240970/jobs/5738482973

fix: debian builds

---

.github/workflows/ci.yml

[W-12049376](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001CS9owYAD/view)
Set the `AWS_EC2_METADATA_DISABLED` config to true to prevent failing aws request. See issue 5623 on aws/aws-cli.

fix(ci): set AWS_EC2_METADATA_DISABLED to true

---

.github/workflows/ci.yml
packages/apps/package.json
packages/autocomplete/package.json
packages/cli/package.json
packages/local/package.json
packages/oauth/package.json
packages/pipelines/package.json
packages/run/package.json
packages/webhooks/package.json
yarn.lock

Remove all references to @oclif/cli-dev in the repository. 
Successful run of `pack_deb` action here: https://github.com/heroku/cli/actions/runs/3448406902/jobs/5755400031
Removed test code to run test.

fix: debian builds to run in ci round 2

---

packages/run-v5/commands/run.js
packages/run/README.md
packages/run/src/commands/run/index.ts

free/hobby formations can't use a different dyno size, so it's a bad example.
https://devcenter.heroku.com/articles/one-off-dynos#one-off-dyno-type
[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001FMbEbYAL/view)

chore(run): update example for heroku run: use a dyno type that make sense

---

packages/redis-v5/commands/cli.js
packages/redis-v5/test/commands/cli.js

Possibly a duplicate of https://github.com/heroku/cli/pull/2203. I found two issues here:
* For any connections, closing the Redis console with a `QUIT` didn't make the process exit. I believe this is because `io`/readline was still waiting for input. This PR includes a line to close it.
* For connections that go through a bastion (private Redis), the underlying TCP connection was never closed (see notes in our internal investigation notes). Looking at `ssh2` docs, I believe we were missing a `client.end()`.
With these changes:
* Writing QUIT on the Redis console closes the connection and the heroku command exits
* Pressing Ctrl+C closes the connection and the heroku command exits. No second Ctrl+C is required.

fix(redis-v5): Close bastion connection and io interface on Redis connection quit

---

.github/workflows/ci.yml
.github/workflows/snyk.yml

Moving Snyk to a cron job to better enable the move to Yarn 3. [Yarn 3 GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001JcVnJYAV/view).

chore: move snyk to cron job

---

.github/workflows/snyk.yml

Fixing the syntax on the Snyk cron job. [Yarn 3 GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001JcVnJYAV/view).

chore: fix snyk GH Action syntax

---

.github/workflows/snyk.yml

Moves the yarn install command first and adds `--all-projects` to the monitor command. [Yarn 3 GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001JcVnJYAV/view).

chore(snyk): move yarn install first and add --all-products to monitor command

---

packages/apps/src/commands/domains/add.ts
packages/apps/src/commands/domains/clear.ts
packages/apps/src/commands/domains/remove.ts
packages/apps/src/commands/domains/update.ts
packages/apps/src/lib/wait-for-domain.ts
packages/webhooks/src/commands/webhooks/add.ts
packages/webhooks/src/commands/webhooks/remove.ts
packages/webhooks/src/commands/webhooks/update.ts

Using the spinner function directly instead of going through `CliUx.ux.action` allows our tests to pass. This is a better fix than the one we had in place before.
[Apps GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BL6M4YAL/view)
[Webhooks GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BM3KZYA1/view)

fix: use the spinner function from CliUx directly

---

package.json
packages/addons-v5/package.json
packages/apps-v5/package.json
packages/apps/package.json
packages/auth/package.json
packages/buildpacks/package.json
packages/certs-v5/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/container-registry-v5/package.json
packages/git/package.json
packages/local/package.json
packages/oauth-v5/package.json
packages/oauth/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/run/package.json
packages/spaces/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

This work is necessary to run the scripts to release v8 (oclif core migration) of this repo.
[GUS epic](https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QEE000000OzFF2A0/view)
This would also close the ticket to [upgrade Lerna to v5](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001If9SsYAJ/view) and the ticket to [upgrade Lerna to v6](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001If43uYAB/view).

chore: upgrade lerna and remove oclif readme command

---

.github/workflows/ci.yml

Revert previous change to run `pack_deb` and `pack_tarballs` in PRs. They will never pass on release branches because they attempt to install packages we are attempting to release.

fix: Revert previous change to run pack_deb and pack_tarballs in PRs

---

.github/workflows/ci.yml

Issue: https://github.com/heroku/cli/issues/2240#issuecomment-1435325995
Initial solution here: https://github.com/heroku/cli/pull/2245
Downgrade ubuntu from latest to one that uses a compression method debian supports

fix: output linux artifacts that debian can decompress

---

packages/cli/package.json
yarn.lock

This version bump gets us an environment variable our users can add to heroku CLI commands to re-set their version cache. Would allow users to resolve issues like #2234 and #2237.
Once this is released, users can add `HEROKU_FORCE_VERSION_CACHE_UPDATE=true` to any Heroku command, rather than waiting for a set period of time (right now 60 days) for the cache to re-set on its own. This will be useful if we ever have to roll back a CLI release again.
[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001M8kGoYAJ/view)

patch: bump version of oclif/plugin-warn-if-update-available

---

.github/workflows/ci.yml

We are not currently running any of our acceptance tests in the windows environment, so I have removed that test run for now.

chore: remove windows acceptance test run

---

packages/local/src/commands/local/run.ts
packages/local/test/commands/local/run.test.ts

Port 5000 is node-foreman's default starting port. However, that port is commonly bound by MacOS's "AirPlayReceiver". When developers use commands like `heroku local web`, errors like `[ERROR] listen tcp :5000: bind: address already in use` are common as a result. 
The workarounds for this are to either turn off "AirPlayReceiver" in MacOS System Preferences Sharing menu, or specify a `--port` that isn't already in use like this: `heroku local web --port 5001`.
However, by choosing a starting port that is not already occupied for a large subset of users (MacOS Monterrey and greater), we can prevent a few developers from scratching their heads and having to figure this out on their own.
We've already filed a change upstream, which has a bit more context: …

feat(local): change default starting port

---

scripts/publish-release

This PR adds the ability to create releases and publish to NPM from branches with the word "prerelease" in the name. The purpose of this change is to enable us to create and publish prereleases ("beta" releases) prior to merging them to `master`.
[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001MKX4HYAX/view)

chore: add ability to release from prerelease branches

---

.github/workflows/promote-release.yml

CLI release process is still in need of refactoring after oclif core upgrades. This is a temporary solution to promote builds pushed to NPM and S3 from current CI.

feature: new workflow to promote a version pushed to S3

---

packages/auth/src/commands/labs/disable.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OpktHYAR/view
Remove call to a missing function. No longer passing cliUx as arg.

fix(auth): allow `heroku labs:disable spaces-strict-tls`

---

.github/workflows/pack-and-release.yml

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OgQdAYAV/view)
Work started previously here: https://github.com/heroku/cli/pull/2285

fix: allow manual promotion with commitSHA input in GH Actions

---

packages/addons-v5/test/commands/addons/docs.js
packages/addons-v5/test/commands/addons/open.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBKJnYAP/view)
As per our review of unit tests and coverage for the apps-v5 package, this PR does the following:
- N/A
2. Run tests

chore(addons-v5): add code coverage reports

---

packages/orgs-v5/test/commands/access/remove.js
packages/orgs-v5/test/commands/apps/leave.js
packages/orgs-v5/test/commands/orgs/open.js
packages/orgs-v5/test/stub/delete.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBdsYYAT/view)
As per our review of unit tests and coverage for the orgs-v5 package, this PR does the following:
- N/A
2. Run tests

chore(orgs-v5): add code coverage reports

---

packages/buildpacks/.nycrc

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBlbaYAD/view)
As per our review of unit tests and coverage for the buildpacks package, this PR does the following:
- Removed `all` property in `.nycrc` file to remove `src/index.ts` from testing since there is nothing to test in that file
2. Run tests

chore(buildpacks): add code coverage reports

---

packages/status/.gitignore
packages/status/package.json

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBtC8YAL/view)
As per our review of unit tests and coverage for the status package, this PR does the following:
- Adds `nyc` package to add code coverage reports ✅
- N/A
2. Run tests

chore(status): add code coverage reports

---

packages/config/.nycrc

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NC0xzYAD/view)
As per our review of unit tests and coverage for the config package, this PR does the following:
- Removed `all` property in `.nycrc` file to remove `src/index.ts` from testing since there is nothing to test in that file
- The `edit()` method from the `Editor` class has been stubbed and tested. However, `nyc` is not including it as part of test coverage showing the `util.ts` file at 66% Stmts. I have not been able to figure out why that's the case, but the test coverage for the `util.ts` file is at 100% despite showing 66%.
2. Run tests
3. Confirm test coverage report is visible and that it reports …

chore(config): add code coverage reports

---

packages/spaces/commands/topology.js
packages/spaces/test/commands/topology.js
packages/spaces/test/lib/format.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBvIfYAL/view)
As per our review of unit tests and coverage for the spaces package, this PR does the following:
- Updated dynos array sorting logic to use correct method. Previously it was comparing strings when it should be comparing numbers
2. Run tests

chore(spaces): add code coverage reports

---

packages/cli/package.json
yarn.lock

Bumping the version of @oclif/plugin-plugins to a version that includes a fix for the issue some of our users are experiencing where they cannot install some plugins.
Fix: https://github.com/oclif/plugin-plugins/pull/595

chore: update version of @oclif/plugin-plugins

---

packages/pipelines/src/setup/poll-app-setups.ts
packages/pipelines/test/commands/pipelines/connect.test.ts
packages/pipelines/test/commands/pipelines/setup.test.ts
packages/pipelines/test/commands/pipelines/transfer.test.ts

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBlbhYAD/view)
As per our review of unit tests and coverage for the pipelines package, this PR does the following:
- Updated `cli.exit()` from `heroku-cli-util` with `cli.error()` from `oclif/core`
2. Run tests

chore(pipelines): add code coverage reports

---

packages/redis-v5/commands/cli.js
packages/redis-v5/commands/credentials.js
packages/redis-v5/commands/index.js
packages/redis-v5/commands/info.js
packages/redis-v5/commands/keyspace-notifications.js
packages/redis-v5/commands/maintenance.js
packages/redis-v5/commands/maxmemory.js
packages/redis-v5/commands/promote.js
packages/redis-v5/commands/stats-reset.js
packages/redis-v5/commands/timeout.js
packages/redis-v5/commands/upgrade.js
packages/redis-v5/commands/wait.js
packages/redis-v5/index.js
packages/redis-v5/lib/shared.js
packages/redis-v5/package.json
packages/redis-v5/test/commands/cli.js
packages/redis-v5/test/commands/credentials.js
packages/redis-v5/test/commands/info.js
packages/redis-v5/test/commands/keyspace-notifications.js
packages/redis-v5/test/commands/maintenance.js
packages/redis-v5/test/commands/maxmemory.js
packages/redis-v5/test/commands/promote.js
packages/redis-v5/test/commands/stats-reset.js
packages/redis-v5/test/commands/timeout.js
packages/redis-v5/test/commands/upgrade.js
packages/redis-v5/test/commands/wait.js
packages/redis-v5/test/lib/shared.js
packages/redis-v5/test/unwrap.js

Fixes linting errors for the redis-v5 package.
Fulfills part of the [eslint standardization GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBwHTYA1/view)

chore: eslint standardization redis-v5

---

packages/run-v5/commands/console.js
packages/run-v5/commands/logs.js
packages/run-v5/commands/rake.js
packages/run-v5/commands/run.js
packages/run-v5/commands/run/detached.js
packages/run-v5/commands/run/inside.js
packages/run-v5/lib/colorize.js
packages/run-v5/lib/dyno.js
packages/run-v5/lib/helpers.js
packages/run-v5/lib/line_transform.js
packages/run-v5/lib/log_displayer.js
packages/run-v5/package.json
packages/run-v5/test/assert_exit.js
packages/run-v5/test/colorize.test.js
packages/run-v5/test/commands/console.js
packages/run-v5/test/commands/detached.js
packages/run-v5/test/commands/logs.js
packages/run-v5/test/commands/rake.js
packages/run-v5/test/commands/run.js
packages/run-v5/test/lib/helpers.js
packages/run-v5/test/test-helper.js

Fixes linting errors for the run-v5 package.
Fulfills part of the [eslint standardization GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBwHTYA1/view)

chore: eslint standardization run-v5

---

.github/workflows/pack-and-release.yml
scripts/postrelease/install_scripts.js

Continuation of https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001KPfC4YAL/view
Make certain execa is executed from the correct directory

fix: use correct cwd for execa during install scripts upload

---

scripts/postrelease/install_scripts.js

Continuation of https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001KPfC4YAL/view
Used exaca correctly in script.

fix: usage of execa in install_scripts.js

---

package.json
packages/container-registry-v5/lib/sanbashi.js
packages/container-registry-v5/test/commands/index.js
packages/container-registry-v5/test/sanbashi.test.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBwPvYAL/view)
As per our review of unit tests and coverage for the container-registry-v5 package, this PR does the following:
- N/A
2. Run tests

chore(container-registry-v5): add code coverage reports

---

packages/ci/.nycrc
packages/ci/test/commands/ci/index.test.ts
packages/container-registry-v5/lib/sanbashi.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBv2VYAT/view)
As per our review of unit tests and coverage for the ci package, this PR does the following:
- Refactored some tests to increase code coverage ✅
- The logic for `renderList()` needs to be fixed as it's impossible to reach lines 166 - 188. This has impacted `test-run.ts`'s coverage and has been exempt from test coverage report
- Since `git.ts` is a wrapper for git commands, it is not necessary to test this file and has been exempt from the the test coverage report
2. Run tests
3. Confirm test coverage report is visible and that it reports over 85% test coverage of statements for all files except for …

chore(ci): add code coverage reports

---

.github/workflows/publish-pack-upload.yml
scripts/publish-prerelease
scripts/publish-release

The final piece of https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBcPzYAL/view
Uncomment existing GH release code from scripts.
Give automatically created GHA GITHUB_TOKEN permission to push/tag/release and use.
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

fix: enable GH releases in CD

---

.github/workflows/publish-pack-upload.yml
.github/workflows/trigger-release.yml
packages/cli/src/analytics.ts

trigger released based on branch being merged in, not in to.
fix bash logic for determining which release script to run
whitespace in package for release

fix: trigger for release CD

---

scripts/publish-release

Depending on git history, we could show older commits in change log.
[Explanation of ".." vs "..." in git log range](https://stackoverflow.com/questions/18595305/git-log-outputs-in-a-specific-revision-range/18595347#18595347) 
Examples: 
`git log --graph --format="%h %s" "v8.1.3...v8.1.4~1` 
yields 
```
* 31cc2895a fix: enable GH releases in CD (#2361)
* 289c8ec82 chore: set up integration, smoke, and acceptance test runs (#2354)
* 8923de7a1 fix: bugs from CD refactor (#2352)
* 8e386785c chore: add acceptance test for orgs-v5 (#2351)
* 4ccc6bf42 v8.1.3 (#2335)
* b516b331d chore: eslint standardization run-v5 (#2332)
* 6a2bae6ae chore: eslint standardization spaces (#2333)
* 32a562d51 fix: add working directory for install scripts step (#2323)
* 6eacdb4e3 v8.1.2 (#2334)
* 0999b1f2a chore: …
```

fix: correctly use git log range for release notes.

---

.github/workflows/ci.yml
.github/workflows/watch-for-release.yml

use triggering branch short name along with startsWith() instead of contains() for triggers

fix: safeguard against accidental releases

---

.github/workflows/start-gh-release.yml

fix: workflow syntax doesn't allow description key in job

---

packages/ci-v5/lib/api.js
packages/ci-v5/package.json
packages/ci-v5/test/unit/lib/disambiguate.unit.test.js
packages/ci-v5/test/unit/lib/heroku-api.unit.test.js
packages/ci-v5/test/unit/lib/key-by.unit.test.js
yarn.lock

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBtQnYAL/view)
As per our review of unit tests and coverage for the ci-v5 package, this PR does the following:
- Adds `nyc` package to add code coverage reports ✅
- `disambiguate.js` had issues using `inquirer`'s `prompt` function. Given that the pipelines package already thoroughly tests an updated version of `disambiguate` (not on v5), this test/package won't be necessary in the near future. Discard this file from test coverage report.
- `api.js` copied over functions from v5 that are no longer being used. The dead code has been removed. 
2. Run tests
3. Confirm test coverage report is visible and that it reports …

chore(ci-v5): add code coverage reports

---

docs/apps.md
docs/domains.md
packages/apps-v5/README.md
packages/apps-v5/src/commands/apps/rename.js
packages/apps/README.md
packages/apps/src/commands/domains/index.ts

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Nh75OYAR/view)
We are currently updating our future app subdomains to prevent potential attack vectors. While there are no technical changes required in the Heroku CLI for updating the subdomains for newly created apps, this PR does the following:
- Updates subdomains copy in examples to maintain product consistency ✅
- N/A
1. Get copy approval from @SandyPantsLai

chore(cli): update subdomain examples

---

packages/oauth-v5/test/clients.unit.test.js
packages/oauth-v5/test/unit/clients/create.unit.test.js
packages/oauth-v5/test/unit/clients/rotate.unit.test.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBq4aYAD/view)
As per our review of unit tests and coverage for the oauth-v5 package, this PR does the following:
- Fixed and updated broken tests ✅
- N/A
2. Run tests

chore(oauth-v5): add code coverage reports

---

packages/local/package.json
packages/local/src/fork-foreman.ts
packages/local/test/unit/commands/local/version.unit.test.ts

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBiF1YAL/view)
As per our review of unit tests and coverage for the local package, this PR does the following:
- `fork-foreman.ts` will need a refactor. Additional tests have been added, but discard it in the `nyc` coverage report
2. Run tests
3. Confirm test coverage report is visible and that it reports over 85% test coverage of statements for all files except for `fork-foreman.ts`

chore(local): add code coverage reports

---

scripts/release/homebrew.js
scripts/release/homebrew/templates/heroku.rb

For a description of the issue (and notes on how to fix), see https://github.com/heroku/homebrew-brew/issues/30

fix: add version to homebrew template and set version_scheme

---

packages/pg-v5/test/unit/commands/backups/unschedule.unit.test.js
packages/pg-v5/test/unit/commands/links/index.unit.test.js
packages/pg-v5/test/unit/commands/settings/settings.unit.test.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NBzdyYAD/view)
As per our review of unit tests and coverage for the pg-v5 package, this PR does the following:
- `nyc` is technically reading the uncovered lines found in `download.js`. What looks to be the problem is the way the code is written where the callback response is the second argument of the `https.get()` call. Within this second argument exists the logic trying to be accessed. The response callback of an argument cannot be stubbed via `sinon`. Interestingly enough, the existing test for `download.js` does in fact read the lines, however my current theory is that not being able to stub the readable stream causes the test to …

chore(pg-v5): add code coverage reports

---

packages/cli/package.json

v8.2.0-beta prerelease has an error during updates. Looks for a hook that doesn't exit.

fix: use correct path for update hooks

---

packages/cli/package.json
yarn.lock

Move tslib from devDep to deps. Fixes a runtime bug where tslib is not present in release pacakages.
Turns out tslib imports get added to transpiled JS when tsconfig `importHelpers: true`
https://zenzes.me/today-i-learned-tslib-is-not-a-devdependency/

fix: turns out tslib is actually a runtime dependency, not just dev.

---

scripts/create-release-pr

https://gus.lightning.force.com/lightning/r/a07EE00001V8EeJYAV/view
Update yarn.lock in create-release-pr script for packages in this monorepo outside of packages/cli, ie: "@heroku-cli/plugin-certs-v5": "^NEW_VERSION"
Outcome without this fix: https://github.com/heroku/cli/actions/runs/5825041518/job/15795614844?pr=2431

fix: update create-release-pr to work with yarn3

---

scripts/create-release-pr

Move `git add` to after yarn.lock update in create release pr

fix: add yarn.lock update in create release pr

---

packages/cli/bin/run
packages/cli/package.json
packages/cli/src/global_telemetry.ts
packages/cli/src/hooks/init/performance_analytics.ts
packages/cli/test/unit/global_telemetry.unit.test.ts

This PR addresses the [Rollbar exitCode bug](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001XrBukYAF/view)
Notes
- The oclif architecture needs to be updated as `version` and `--help` flags do not trigger oclif's `postrun` lifecycle hook
- This solution ensures that `version` and `--help` flags are accounted for in the telemetry object creation by adding a telemetry object creation function in the oclif `init` lifecycle hook
Follow up
- Update our telemetry system design diagram to reflect these new discoveries

fix(cli): fix rollbar exitCode returning undefined

---

packages/addons-v5/commands/addons/index.js
packages/addons-v5/commands/addons/info.js
packages/addons-v5/commands/addons/plans.js
packages/addons-v5/commands/addons/upgrade.js
packages/addons-v5/lib/create_addon.js
packages/addons-v5/lib/util.js
packages/addons-v5/test/unit/commands/addons.--all.unit.test.js
packages/addons-v5/test/unit/commands/addons.--app.unit.test.js
packages/addons-v5/test/unit/commands/addons/create.unit.test.js
packages/addons-v5/test/unit/commands/addons/info.unit.test.js
packages/addons-v5/test/unit/commands/addons/plans.unit.test.js
packages/addons-v5/test/unit/commands/addons/upgrade.unit.test.js
packages/addons-v5/test/unit/lib/util.unit.test.js
packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/unit/commands/ps/type.unit.test.js
packages/spaces/commands/create.js
packages/spaces/test/unit/commands/create.unit.test.js

This PR adds price per hour and monthly max price to all of the CLI's pricing displays. The commands affected are:
ps:type
spaces:create
addons
addons:info
addons:plans
addons:upgrade
addons:create
- Hourly price is reported using three decimal places
- In the addons-v5 plugin, we get pricing data from the API. in the apps-v5 and spaces packages that information is hard-coded.
I tested pricing displays using our unit tests and test data. In several cases I added new unit tests to ensure that the displays and any pricing display logic was tested thoroughly.
`ps:type`
<details>
</details>
`spaces:create`
<details>
</details>
`addons`
<details>
</details>
`addons:info`
<details>
</details>
`addons:plans`
<details>
</details>
`addons:update` & `addons:create`
With standard pricing
<details> …

refactor: add per hour and max price per month to pricing displays

---

packages/cli/src/global_telemetry.ts
packages/cli/src/hooks/init/version.ts
packages/cli/src/lib/utils/packageParser.ts

This PR fixes a bug caught in our telemetry testing that didn't capture all `version` and `help` cli inputs. A package parser util has also been added as similar logic exists in our `version` function inside our oclif `init` lifecycle hook.

fix(cli): update boolean logic and add package parser util

---

packages/addons-v5/commands/addons/destroy.js
packages/addons-v5/commands/addons/info.js
packages/addons-v5/commands/addons/wait.js
packages/addons-v5/index.js
packages/addons-v5/lib/addons_wait.js
packages/addons-v5/lib/create_addon.js
packages/addons-v5/lib/destroy_addon.js
packages/addons-v5/lib/util.js
packages/addons-v5/package.json
packages/addons-v5/test/fixtures.js
packages/addons-v5/test/unit/commands/addons/destroy.unit.test.js
packages/addons-v5/test/unit/commands/addons/info.unit.test.js
packages/addons-v5/test/unit/commands/addons/wait.unit.test.js
yarn.lock

As part of the effort to EOL Legacy Add-on Partner API, Heroku Ecosystem recently added to Platform API a new feature that allows add-on providers to perform an asynchronous deprovisioning operation on add-on resources.
When an async deprovision is performed the add-on resource is kept on `deprovisioning` state until the add-on provider finishes the process and the resource is deleted.
This work updates addons-v5 project commands to account for such scenario:
- Command `destroy` now accepts an additional `--wait` flag (in the same spirit that `create` accepts it for asynchronous provisioning) and shows specific messages when an asynchronous deprovision is underway.
- Command `wait` is updated to handle asynchronous provisioning or deprovisioning.
- Command `info` was updated to correctly …

feat(addons-v5): handle asynchronous deprovisioning state

---

packages/cli/bin/run
packages/cli/src/global_telemetry.ts

https://app.rollbar.com/a/Heroku-3/fix/item/heroku-cli/161
Add CLI version to Rollbar reports. 
Hopefully fix all bugs where global telemetry isn't intialized.

fix: rollbar version segmentation and telemetry initialization

---

.github/workflows/create-cli-release.yml
.github/workflows/promote-release.yml
.github/workflows/promote.yml
.github/workflows/publish-npm.yml
.github/workflows/start-prerelease.yml
scripts/release/validate-prerelease

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001aPZvVYAW/view)
This PR updates our pre-release workflows to allow for alpha releases. It also updates our start-prerelease workflow for clarity.

chore: enable alpha prereleases

---

packages/cli/src/commands/local/index.ts
packages/cli/test/unit/commands/local/index.unit.test.ts

This is a followup to #2261, where we added a default `--port 5001` for `heroku local web`. This PR expands that same default to `heroku local`. It's really an oversight that the original PR didn't include the changes for `heroku local`.
The same reasoning from #2261 applies:
> Port 5000 is node-foreman's default starting port. However, that port is commonly bound by MacOS's "AirPlayReceiver". When developers use commands like `heroku local web`, errors like `[ERROR] listen tcp :5000: bind: address already in use` are common as a result.<br/><br/>The workarounds for this are to either turn off "AirPlayReceiver" in MacOS System Preferences Sharing menu, or specify a `--port` that isn't already in use like this: `heroku local web --port 5001`.<br/><br/>However, by choosing a starting port …

fix: default to --port 5001 for heroku local

---

packages/apps-v5/src/commands/ps/index.js

A re-do of #2469 so CI can run.

feat(apps-v5): Use colors when showing run dynos in the ps output

---

packages/pg-v5/lib/host.js
packages/pg-v5/test/unit/lib/host.unit.test.js

If `HEROKU_DATA_HOST` is set when running `heroku pg` commands, let's prefer that first.

feat(pg-v5): prefer HEROKU_DATA_HOST when set

---

.github/workflows/promote-release.yml
.github/workflows/promote.yml

Fixes inputs for workflow_call trigger in promote and promote-release workflows.

fix: fix inputs for workflow_call in promote and promote-release

---

.github/workflows/start-prerelease.yml

Needed to add a checkout of the repo in order to run prerelease validation script

fix: checkout repo in order to run prerelease validation script

---

.github/workflows/create-cli-release.yml
.github/workflows/promote.yml
.github/workflows/publish-npm.yml
.github/workflows/start-prerelease.yml
scripts/postrelease/test_release

Mostly removed `fromJSON` calls on strings.
Fix a test in test_release that only passed due to a prior bug that has been fixed.

Fix: syntax fixes for GHA prerelease refactor

---

packages/cli/bin/run
packages/cli/package.json
packages/cli/src/global_telemetry.ts
packages/cli/test/unit/global_telemetry.unit.test.ts
yarn.lock

Fixes #2457. I confirmed with @mars and @zwhitfield3 that we no longer need the dotenv package for telemetry.
To test locally:
1. Add two files to the root of your local cli repo
- .env
- `BASE_ENV_VAR="value for base"`
- read_some_env_vars
- ```
#!/usr/bin/env ruby
puts <<~EOF
⚠️
BASE_ENV_VAR=#{ENV.fetch("BASE_ENV_VAR", :not_set)}
OTHER_ENV_VAR=#{ENV.fetch("OTHER_ENV_VAR", :not_set)}
⚠️
EOF
2. run `yarn` and `yarn build`
3. run the command `./bin/run local:run ./read_some_env_vars --env=/dev/null`
4. You should get the result
```
⚠️
BASE_ENV_VAR=not_set
OTHER_ENV_VAR=not_set
⚠️

fix: remove dotenv as no longer necessary

---

.github/workflows/start-prerelease.yml
scripts/release/validate-prerelease

Remove an extra `$` character that broke branch name validation.
Fix a syntax error in validate-prerelease script.

fix: alpha release fixes

---

packages/pg-v5/lib/util.js
packages/pg-v5/test/unit/lib/host.unit.test.js

A few quick linting fixes for pg-v5

chore: pg-v5 lint fixes

---

packages/pg-v5/commands/links/create.js
packages/pg-v5/commands/links/destroy.js
packages/pg-v5/test/unit/commands/links/create.unit.test.js
packages/pg-v5/test/unit/commands/links/destroy.unit.test.js

Users will now see a detailed error message if they try and setup `pg:links` with an essential-tier database. The `pg:links` feature has never been supported for essential-tier databases and users that would attempt to create links would be greeted with a non-helpful error message.
This PR updates to give users more helpful information and bring the CLI more in-line with our docs.

fix(pg-v5) Disallow pg:links for essential-tier plans

---

.github/workflows/release-homebrew.yml

https://github.com/heroku/cli/actions/runs/6539272126/job/17757726522
Script was being run via bash, changed to node.

fix: explicitly run homebrew release as node script

---

packages/spaces/commands/info.js
packages/spaces/commands/wait.js
packages/spaces/test/unit/commands/info.unit.test.js
packages/spaces/test/unit/commands/wait_test.unit.test.js

Currently for Next Gen Private spaces or when space/nat API call fails, the following spaces command fails without returning any data. This change would fix that , 
```
> heroku spaces:wait telemetry-kiran --json
Waiting for space telemetry-kiran to allocate... ⣟
▸    Could not complete the action. Please try again later.
> heroku spaces:info telemetry-kiran
▸    Could not complete the action. Please try again later.
```
This is the new output 
```
https://github.com/heroku/cli/pull/2526/files
> ./bin/run spaces:wait telemetry-kiran
Waiting for space telemetry-kiran to allocate... ⡿
Waiting for space telemetry-kiran to allocate... done
=== telemetry-kiran
ID:           7d0187ca-814c-4fc2-89d8-c9ff25d4bf47
Team:         heroku-runtime-playground
Region:       Virginia, United States
CIDR: …
```

fix(spaces) heroku space:wait and space:info will not fail if space/space_name/nat is not available

---

.github/workflows/direwolf.yml
scripts/direwolf-test-run

This is the first step in adding direwolf automation to our prerelease workflow. The github action will allow me to test running Direwolf from a github action. Once that is working I will submit a second PR to add a Direwolf test run to our prerelease workflow.

chore: add direwolf automation

---

scripts/create-release-pr

They interfere with doc generation and this should lead to less confusion going forward. 
See https://github.com/heroku/cli/pull/2534

fix: remove any oclif manifests during release PR generation

---

.github/workflows/direwolf.yml

Since we would only want to run our direwolf tests against the staging environment very rarely, this PR removes that option from the workflow to simplify things a bit and get them working. We can add this feature back in the future if we feel like it is necessary.
Successful run here: https://github.com/heroku/cli/actions/runs/6789787983/job/18457763652

fix: set direwolf test to only run against production

---

.github/workflows/start-prerelease.yml

Adds a job to the prerelease workflow to kick off a Direwolf test run.
[work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001bPvgjYAC/view)

chore: add direwolf test run to prerelease workflow

---

.github/workflows/pack-upload.yml
.github/workflows/promote.yml
packages/cli/package.json

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001elI32YAE/view)
Adds steps to pack and upload the windows installer to s3 and then promote it to the current release.

chore: add windows pack, upload, and promote scripts to workflows

---

package.json
packages/cli/package.json
packages/cli/src/commands/apps/create.ts
packages/cli/test/helpers/runCommand.ts
packages/migration/.bin/command-test-migration.mjs
packages/migration/.eslintrc
packages/migration/package.json
packages/migration/src/index.ts
packages/migration/src/node-validators/isCommandMigrationCandidate.ts
packages/migration/src/transforms/heroku-cli-utils/helpers.ts
packages/migration/src/transforms/heroku-cli-utils/transformCliUtils.ts
packages/migration/src/transforms/unit-tests/index.ts
packages/migration/src/transforms/unit-tests/migrations.ts
packages/migration/src/transforms/unit-tests/validators.ts
packages/pg-v5/test/unit/commands/backups/restore.unit.test.js
yarn.lock

Everything but the last commit has been previously reviewed & approved.
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001g49b9YAA/view
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001g4LA4YAM/view
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001ec0nVYAQ/view
Example PR from using codemod for addons:detach that took about 10 minutes with codemods: https://github.com/heroku/cli/pull/2583
**Note**: aliases below still need to be added manually.
```
module.exports = [
Object.assign({command: 'create'}, cmd),
Object.assign({command: 'add', hidden: true}, cmd),
]
```
Example usage:
convert command:
`yarn migrateCommand --files "./packages/addons-v5/commands/addons/detach.js"`
convert command unit test:
`yarn migrateCommandTest --files …

v5 command codemods

---

packages/run-v5/test/integration/run.integration.test.js

Updates a run-v5 integration test to allow them to pass.

test: update run-v5 integration test

---

packages/cli/package.json
packages/run-v5/test/integration/run.integration.test.js
yarn.lock

Fix bug reports of the CLI breaking with errors like: 
```
% heroku addons:detach
/opt/homebrew/Cellar/heroku/8.5.0/lib/client/bin/heroku: line 16: /opt/homebrew/Cellar/heroku/8.5.0/lib/client/bin/../8.7.1-3f5e369/bin/heroku: No such file or directory
```
Fix here: https://github.com/oclif/plugin-update/releases/tag/3.2.1
Bumped to the last version before a major bump of @oclif/plugin-update

fix: bump @oclif/plugin-update to a version that doesn't delete the CLI

---

.github/workflows/pack-upload-windows.yml
.github/workflows/pack-upload.yml
package.json
yarn.lock

This is to make it easier to test the Windows installer workflow. It also upgrades the version of oclif we are using in order to fix an issue with yarn plugins.

chore: move pack windows script to separate workflow and update oclif version

---

packages/addons-v5/test/unit/commands/addons/attach.unit.test.js
packages/migration/src/transforms/unit-tests/migrations.ts

Fix a bug that caused any args in cmd.run({}) object to get dropped if they came after `args`
This case: `return cmd.run({app: 'myapp', args: {addon_name: 'redis-123'}, flags: {as: 'foo'}})` would lead to an output of 
```
return runCommand(Cmd, [
'--app',
'myapp',
'redis-123',
])
```
without this fix.

fix(codemods): test flags transform fix

---

packages/migration/src/transforms/unit-tests/migrations.ts

Before fix: 
`flags: {'show-url': true, thing: true}}` => `runCommand(Cmd, ['--thing'])`
with fix: 
`flags: {'show-url': true, thing: true}}` => `runCommand(Cmd, ['--show-url', '--thing'])`

fix(codemods): handle string literal prop name in flags

---

.github/workflows/empty-stampy-buckets.yml
.github/workflows/get-signed-from-stampy.yml
.github/workflows/promote-windows.yml
.github/workflows/upload-to-stampy.yml

A few updates to the stampy-related github actions.
[Work item 1](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001elgflYAA/view)
[Work item 2
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001elVCoYAM/view)

fix: updates to stampy actions

---

package.json
yarn.lock

Bumping oclif to v4.4.7 in order to capture fixes to the `pack win` command.

chore: bump oclif to v4.4.7

---

packages/pg-v5/commands/credentials/rotate.js
packages/pg-v5/commands/credentials/url.js
packages/pg-v5/test/unit/commands/credentials/rotate.unit.test.js
packages/pg-v5/test/unit/commands/credentials/url.unit.test.js

This updates logic in our `pg:credentials` command to allow for essential tier dbs.

feat(pg): enable credentials url/rotation command for essential tier dbs

---

packages/apps-v5/src/commands/ps/scale.js
packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/unit/commands/ps/scale.unit.test.js
packages/apps-v5/test/unit/commands/ps/type.unit.test.js

When we introduced an internal feature flag to selectively test the new Larger Dynos feature we didn't realize that for regular Heroku users trying to fetch the state of that feature will trigger a Not Found error that wasn't being handled.
Here we correct that problem handling the Not Found error as expected.
[GUS WI](https://gus.lightning.force.com/a07EE00001jlS2XYAU)

Fix error triggered on check for internal feature flag

---

.github/workflows/snyk.yml

Yarn 3 uses `yarn dlx` instead of `yarn global add` for temporary environments.

chore: update snyk install command

---

.github/workflows/snyk.yml

Updating the snyk workflow to hopefully get it right this time.

fix: update snyk workflow to use yarn dlx correctly

---

packages/apps-v5/src/commands/ps/scale.js
packages/apps-v5/test/unit/commands/ps/scale.unit.test.js

Fix for #2636. Allows the `ps:scale` command to handle extra args.

fix: allow ps:scale to handle extra args

---

packages/addons-v5/test/mocha.opts
packages/apps-v5/test/mocha.opts
packages/certs-v5/test/mocha.opts
packages/ci-v5/test/mocha.opts
packages/cli/test/acceptance/smoke.acceptance.test.ts
packages/cli/test/mocha.opts
packages/container-registry-v5/test/mocha.opts
packages/oauth-v5/test/mocha.opts
packages/orgs-v5/test/mocha.opts
packages/pg-v5/test/mocha.opts
packages/redis-v5/test/mocha.opts
packages/run-v5/test/integration/run.integration.test.js
packages/run-v5/test/mocha.opts
packages/spaces/test/mocha.opts

Here we're increasing the Mocha timeouts for async calls to avoid failures on integration and acceptance tests that work spinning up one-off dynos, because our test app was moved from the Common Runtime to one of our Private Spaces and the start up time for one-off dynos on PS exceeds the timeout of one minute.
The terminal configuration also changes between Common Runtime and Private Spaces, changing the line termination from Unix (`\n`) to DOS (`\r\n`).
We changed the tests using `heroku run` command to set the dyno size to `private-s`.
There's no behavior effected for the actual CLI, this only changes a configuration when running tests.
[GUS Work Item](https://gus.lightning.force.com/a07EE00001kXKgUYAW)

fix(tests): Increasing Mocha timeouts

---

packages/cli/src/commands/addons/wait.ts

This adds a type to filtering an addon in `addons:wait`, resolving a potential issue with the `addons_wait` lib.

refactor(container): add type to addons in `addons:wait`

---

.github/workflows/promote-release.yml
.github/workflows/publish-to-fig-autocomplete.yml
packages/addons-v5/package.json
packages/ci-v5/package.json
packages/cli/package.json
packages/cli/test/acceptance/commands-output.ts
packages/container-registry-v5/package.json
packages/oauth-v5/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/spaces/package.json
yarn.lock

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001krB5IYAU/view)
[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001krS81YAE/view)
This PR updates the workflow for the Fig Autocomplete to get the latest config of the Heroku CLI in the form of a PR to Fig Autocomplete's repo when a new version of the Heroku CLI is released.

fix(workflow): update fig autocomplete workflow

---

.github/workflows/empty-stampy-buckets.yml
scripts/stampy/empty-stampy-buckets.js

A couple of quick updates to the empty stampy job.

chore: fix empty stampy workflow

---

packages/pg-v5/commands/credentials.js
packages/pg-v5/test/unit/commands/credentials.unit.test.js

Fix for https://heroku.support/1140923
We are currently using the addon name to query the API for postgres credentials. This breaks after addons are renamed using `addons:rename`. This PR updates the command to use a uuid, a method we largely switched to in 2017. A few commands have yet to be updated, including this one.  
We are waiting on Data to implement support for UUID, until then this PR can not be tested -> https://salesforce-internal.slack.com/archives/C02LKCXMAEM/p1661381725900759

fix(cli): use uuid rather than addon name for pg:credentials

---

.github/workflows/publish-to-fig-autocomplete.yml
packages/cli/package.json
packages/cli/test/acceptance/commands-output.ts
yarn.lock

This PR removes the FIG plugin and updates the Fig Autocomplete workflow.

fix(workflow): remove fig command & update workflow

---

scripts/postrelease/test_release

We have to update our prerelease script to update `status-ui` to `status-ui-staging` as the app name has changed. This should fix our failing prerelease tests.

fix(workflow): update test_release script

---

.github/workflows/devcenter-doc-update.yml

This PR adds an initial workflow for updating devcenter documentation. It does not include the script that generates and updates the documentation yet, but I need to get this workflow merged to `main` so that I can test it on a branch.

chore: add initial workflow for updating devcenter documentation

---

packages/cli/src/commands/local/index.ts
packages/cli/src/commands/local/run.ts
packages/cli/test/unit/commands/local/index.unit.test.ts
packages/cli/test/unit/commands/local/run.unit.test.ts

https://github.com/heroku/cli/issues/2007
`heroku local` and `heroku run` allow users to specify an env file location. If that location is a directory instead, the command fails. This adds logic to ignore `env` file locations that are not files, and warns the user.
1) Pull down branch and run `local web` within an app's directory that has a `.env` that is a directory
2) See that `.env` is ignored and warns the user

bug(local): Ignore env specification when it's not a file

---

packages/certs-v5/package.json
packages/cli/package.json
packages/oauth-v5/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/spaces/package.json
yarn.lock

https://gus.lightning.force.com/lightning/_classic/%2F00TEE000000W7w1
This will upgrade the version of mocha we use to 9.2. Also, this increases our mocha test timeouts, doubling from 3 mins to 6 mins. Hopefully this will be enough for our interaction with space apps. If not.. well, we need to rethink our smoke tests and/or smoke test app.
Tests pass?

chore: update mocha, increase timeout

---

packages/cli/src/global_telemetry.ts
packages/cli/src/hooks/postrun/performance_analytics.ts
packages/cli/src/hooks/prerun/analytics.ts
packages/cli/test/acceptance/smoke.acceptance.test.ts
packages/cli/test/helpers/init.js

This PR improves unit test run performance the following ways:
1. setTimeout is stubbed to be sync with no timeout value. This mainly affects the use of `us.actions.start()` which seems to have a mandatory wait of ~200ms on mac and linux
2. Prevents analytics from bootstrapping before each command is run. This bootstrapping process kicked off file reads and child processes before each command which significantly slowed down tests and caused flappy test on some configurations.

chore(W-15263489): improve unit test performance

---

.github/workflows/test-installed-cli.yml

It looks like our `test-installed-cli` fails when trying to update via `heroku update --version=<some version>`. This PR address that issue by running `heroku update beta` and then checking that the correct version was upgraded in a comparison statement with our expected version output. It is unclear why the previous version doesn't work, short of the github workflow trying to pick up changes that haven't finished processing.

fix(workflow): update test-installed-cli

---

package.json
packages/cli/package.json
yarn.lock

We accidentally introduced a regression when updating some dependencies last week. This PR fixes the `semver` dependency issue causing prereleases and potentially production releases failing to complete their workflows.

fix(cli): update semver dependency

---

packages/certs-v5/package.json
packages/cli/package.json
packages/run-v5/package.json
yarn.lock

Follow-up to work on `heroku-cli-color` to bump versions of things. This should have to observable impact on CLI behavior

chore(deps): Bump @heroku-cli/color to 2.0.1

---

docs/auth.md
packages/certs-v5/package.json
packages/cli/package.json
packages/cli/src/commands/authorizations/create.ts
packages/cli/src/commands/authorizations/info.ts
packages/cli/src/commands/authorizations/revoke.ts
packages/cli/src/commands/authorizations/rotate.ts
packages/cli/src/commands/authorizations/update.ts
packages/cli/src/global_telemetry.ts
packages/cli/test/unit/commands/addons/upgrade.unit.test.ts
packages/cli/test/unit/commands/authorizations/create.unit.test.ts
packages/run-v5/package.json
yarn.lock

This PR merges the latest changes from `main` into the `prerelease/9.0.0-alpha` branch

Merge updates from main

---

scripts/sign/deb

This will fix our debian signing script and allow us to update those credentials.
For a passing pre-release with this fix, see [this run](https://github.com/heroku/cli/actions/runs/8881737320/job/24385316665)

fix: add quotation marks around public key in sign/deb script

---

packages/cli/src/commands/auth/token.ts
packages/cli/test/unit/commands/auth/token.unit.test.ts

This PR makes a minor change to copy.

chore(auth): update warning copy

---

.github/workflows/ci.yml
package.json
packages/addons-v5/package.json
packages/apps-v5/package.json
packages/certs-v5/package.json
packages/ci-v5/package.json
packages/cli/package.json
packages/container-registry-v5/package.json
packages/oauth-v5/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
packages/redis-v5/package.json
packages/run-v5/package.json
packages/spaces/package.json

Separates our unit testing and linting scripts so that linting errors become more obvious in CI.

chore: separate unit testing and linting

---

packages/cli/src/commands/run/inside.ts

This PR removes the `env` flag from the `run:inside` command.
[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001ntdoxYAA/view)

chore(run): remove env flag

---

packages/cli/package.json
yarn.lock

https://github.com/heroku/cli/pull/2787 appears to be broken, so I created a PR to upgrade the package.

chore: Upgrade version of otel semantic conventions to 1.24

---

packages/cli/package.json

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001smLTWYA2/view)
Moves `tsheredoc` from devdependencies to dependencies to fix a bug in the latest alpha release.

fix: move tsheredoc to dependencies

---

packages/cli/package.json
yarn.lock

Here we bump the `@heroku-cli/command` dependency to v11.1.2, which incorporates changes into the API clients that implement checks for account and team delinquency.
[GUS Work Item](https://gus.lightning.force.com/a07EE00001kd011YAA)

Bump version of @heroku-cli/command for delinquency notifications

---

packages/cli/src/commands/ci/config/set.ts
packages/cli/test/unit/commands/ci/config/set.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vT9ipYAC/view)
During oclif migration we added a pipeline flag requirement to `ci:config:set`. However, the command actually accepts `--pipeline` _or_ `--app` and manually errors if provided neither: https://github.com/heroku/cli/blob/prerelease/9.0.0-alpha/packages/cli/src/lib/ci/pipelines.ts#L45 .. I elected to move up that requirement to be declaratively defined with the flag using oclif's `exactlyOne`. This ensures consistent error messaging. We probably should update other commands to do this as well.
1. pull down branch
2. Run `bin/dev ci:config:set` without providing `--app` or `--pipeline`
3. Run  `bin/dev ci:config:set` providing `--app`
4. Run `bin/dev ci:config:set` providing `--pipeline`

fix(cli): Change to require either app or pipeline

---

packages/cli/src/commands/spaces/transfer.ts
packages/cli/src/commands/spaces/trusted-ips/remove.ts

[Gus WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vTP5GYAW/view)
This adds the missing `s` shortcut for a couple `space` commands.
1) Pull down branch
2) Run `bin/dev spaces:trusted-ips:remove -s pretend-space pretend-source`
3) Verify -s works as an alternative to `--space` (it's not necessary for it to be a real space, the error message referencing the space is confirmation enough)

fix(cli): add missing space char shortcut

---

packages/cli/src/commands/spaces/vpn/config.ts
packages/cli/src/commands/spaces/vpn/connect.ts
packages/cli/src/commands/spaces/vpn/destroy.ts
packages/cli/src/commands/spaces/vpn/info.ts
packages/cli/src/commands/spaces/vpn/update.ts
packages/cli/src/commands/spaces/vpn/wait.ts
packages/cli/test/unit/commands/spaces/vpn/wait.unit.test.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vSuraYAC/view)
This PR updates the `spaces:vpn` commands to improve consistency. All of these commands (except`connections`) should require an arg for the name of the vpn connection and _not_ a `--name` flag. This PR also contains updates to the example documentation for these commands that reflects this change and improves consistency.
- Pull down this branch and run `yarn install` and `yarn build`
- Create a vpn connection for a test space (use the instructions from https://github.com/heroku/cli/pull/2873)
- Run `./bin/run spaces:vpn:wait VPN-CONNECTION-NAME -s SPACE-NAME`
- If you run `./bin/run spaces:vpn:wait -n VPN-CONNECTION-NAME -s SPACE-NAME` you should get an error message about the `-n` flag.

fix: update spaces:vpn commands to improve consistency in args and flags

---

packages/cli/src/commands/spaces/transfer.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vj6NdYAI/view)
Adds the char option for the team flag for the `spaces:transfer` command to be more consistent with other commands.

fix: add short char for the team flag on spaces:transfer

---

packages/cli/src/lib/git/git.ts

[Gus WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vh171YAA/view)
This fixes an issue where the `apps:create` emits an error if you don't have a `heroku` git remote in your current working directory. This is because `apps:create` will try to create a `heroku` git remote if you don't have one and, confusingly, there was logic in there that throws a type error when it can't find the `heroku` string in your list of remotes. I'm not sure why this wasn't causing an issue before -- we didn't change this library as part of v9. Perhaps, though, because we migrated `apps:create` to typescript/oclif, the error is surfacing in a way it didn't when it was a legacy javascript command. At any rate, as part of this fix, we no longer throw that type error, and return an empty …

fix(cli): Fix bug with git remote creation

---

packages/cli/src/commands/ci/config/get.ts
packages/cli/src/commands/ci/config/index.ts
packages/cli/src/commands/ci/config/unset.ts
packages/cli/test/unit/commands/ci/config/index.unit.test.ts

Followup to https://github.com/heroku/cli/pull/2907
This improves consistency across our `ci:config` commands, leveraging oclif's `exactlyOne` instead of manually improvised error messaging.

chore(cli): Declaratively require pipeline or app across ci:config commands

---

packages/cli/package.json
yarn.lock

Fixes an issue with installing plugins. I tested this fix locally and was able to install plugins again.

fix: rollback plugin-plugins to 2.4.3

---

packages/cli/src/lib/addons/resolve.ts
packages/cli/src/lib/pg/fetcher.ts

This fix corrects an issue with error handling in the matchesHelper function used with the `pg:psql` command. Testing this is kind of odd, since in both cases we expect the command to fail, just at different points.
To see the original issue:
1. Using the current `beta` release of the CLI (beta.0), run `DEBUG=http heroku psql NONEXISTANT_DB_NAME -a APP_NAME`
2. You should see that the first POST call to the `https://api.heroku.com/actions/addon-attachments/resolve` endpoint returns a 404 not found error and the command fails.
To see the fix:
1. Using this branch, run `yarn` and `yarn build`
2. Run `DEBUG=http ./bin/run psql NONEXISTANT_DB_NAME -a APP_NAME`
3. You should see that the first POST call to the `https://api.heroku.com/actions/addon-attachments/resolve` endpoint returns a 404 …

fix: correct error handling in matchesHelper

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json

Final PR in preparation for prod release. Removes the beta release version from the package.json and lerna.json and removes beta release notes from the changelogs.

chore: remove beta release from package.json and roll back changelogs

---

.github/workflows/cache-invalidation.yml
.github/workflows/promote-release.yml
.github/workflows/promote-windows.yml

This PR moves the cache invalidation job from the promote-release workflow into its own file and allows it to be called both as part of other workflows and independently. Then in adds references to this workflow in the promote-release workflow and the promote-windows workflow.

chore: add separate workflow for cache invalidation

---

packages/cli/src/lib/container/helpers.ts
packages/cli/test/unit/commands/container/push.unit.test.ts
packages/cli/test/unit/commands/container/release.unit.test.ts

When migrating from  a non-container stack to a container stack, the `app.build_stack` is set to `container`. This situation should be allowed in `ensureContainerStack` to avoid an error when `container:*` commands are run.
This should fix https://github.com/heroku/cli/issues/2951

Allow `app.build_stack` to be `container` for `ensureContainerStack`

---

.github/workflows/cache-invalidation.yml

Removes unneeded line from cache-invalidation workflow.

fix: remove 'needs' from cache-invalidation

---

packages/cli/src/commands/apps/transfer.ts
packages/cli/src/commands/ci/index.ts
packages/cli/src/commands/ci/info.ts
packages/cli/src/commands/ci/last.ts
packages/cli/src/commands/ci/rerun.ts
packages/cli/src/commands/ci/run.ts
packages/cli/src/commands/pg/credentials/rotate.ts

[Gus WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001wx9GHYAY/view)
This updates some areas where the `app` flag and `remote` flag aren't working correctly.
1. Pull down branch and build
2. Run commands that are changed within the directory of an app that has the `heroku` remote set

fix(cli): Update app and remote flags

---

packages/cli/package.json
packages/cli/src/commands/addons/create.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts
yarn.lock

This PR enables backwards compatible `v8.x.x` syntax for passing in positional arguments to the `heroku addons:create` command.
2. `yarn` it up
3. Confirm passing positional arguments using old `v8.x.x` syntax via
`./bin/run addons:create -a heroku-cli-test-staging  heroku-postgresql:private-0 --follow DATABASE`
4. Confirm that the addon successfully provisioned a follower database with the positional `--follow` flag
5. Confirm that the deprecation warning is also visible like so:
```
›   Warning: You’re using a deprecated syntax with the [--follow] flag.
›   Add a '--' (end of options) separator before the flags you’re passing through.
›   For example: heroku addons:create -a heroku-cli-test-staging heroku-postgresql:private-0 -- --follow
›   See …
```

chore(cli): enable backwards compatibility syntax for addons:create

---

packages/cli/src/commands/local/run.ts
packages/cli/src/commands/run/index.ts
packages/cli/src/lib/run/helpers.ts
packages/cli/test/integration/run.integration.test.ts
packages/cli/test/unit/commands/local/run.unit.test.ts

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001yRblXYAS/view)
This PR reorders the `argv` elements in a new array using the order that the user inputted. Since this updated logic needs to be applied to both `heroku run` and `heroku local:run`, the logic has been refactored into a utility function.
**NOTE:** I recommend commenting out the commands' functionality after consuming the args as you can see the bug without having to spin up a dyno.
2. `yarn` it up
3. Log `userArgvInputOrder` and `argv` downstream in both commands
5. Run the commands with additional args like so:
`./bin/run run -a testing-deploy -- ./print-args.sh --flag1 val1 --flag1 val2`
6. Confirm that `argv` maintains the sorted array due to the `oclif` dependency. (This is …

fix(run): reorder oclif sorted args

---

packages/cli/src/commands/redis/cli.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001yRuGlYAK/view)
Using the `redis:cli` command to connect to a redis instance using the private plan was failing. This PR implements the fix suggested in #2978.
- Create an app inside of a private space and add a Heroku Redis instance on a private plan
- Run `heroku redis:cli redis_name -a app_name` to see how the command fails
- Pull down this branch and run `yarn && yarn build`
- Run `./bin/run redis:cli redis_name -a app_name` to see the command succeed

fix(redis:cli): remove call to resolve ssh2 in bastionConnect function

---

packages/cli/package.json
yarn.lock

We don't appear to use `aws-sdk` anymore, this removes the dependency.

chore(cli): Remove unused aws-sdk

---

packages/cli/package.json
yarn.lock

this bumps the version of `heroku-cli-command`, hopefully resolving an issue with yargs.

chore(cli): Bump version of heroku-cli-command

---

packages/cli/src/commands/container/push.ts
packages/cli/src/lib/container/docker_helper.ts
packages/cli/test/unit/commands/container/push.unit.test.ts

Fixes https://github.com/heroku/cli/issues/1420
This resolves a bug where if you specify multiple process types in `container:push --recursive` and one of those dockerfiles doesn't actually exist, you get a bad error.
2. Go to a directory where a docker-based app is set up
3. Have `Dockerfile.web` in the directory, but not `Dockerfile.worker`
4. run `$CLI_PATH/bin/run container:push web worker --recursive`
5. See warning message instead of error

fix(cli): fix missing dockerfile error

---

packages/cli/src/commands/container/push.ts
packages/cli/src/lib/container/docker_helper.ts
packages/cli/test/unit/commands/container/push.unit.test.ts
packages/cli/test/unit/lib/container/docker_helper.unit.test.ts

When we migrated the `container:push` command to oclif/core, we added a `--platform` flag that would be passed to Docker. We set it to equal `linux/amd64` because that would allow users using m1 or m2 Macs to push builds to Docker. However, that is causing problems for our users with older Docker applications that don't accept the `--platform` flag (#2967).
This PR adds logic that checks the user's architecture and then only adds the `--platform` flag if the architecture is `arm64`.
Tests require to have a valid Dockerfile to build images, you can use the example app from [this Devcenter article](https://devcenter.heroku.com/articles/container-registry-and-runtime), but the Dockerfile might require a change on the dependencies installation command, adding the flag --break-system-packages …

fix: use linux/amd64 platform only for m1/m2 macs (arm64)

---

packages/cli/src/commands/local/run.ts
packages/cli/src/commands/run/index.ts
packages/cli/src/lib/run/helpers.ts
packages/cli/test/integration/run.integration.test.ts

This PR fixes and issue with the `run` command where arguments after the `--` which collide with the command flag names are duplicated leading to errors.
e.g. `heroku run -e DOMAIN=test -- ruby -e 'puts ENV["ENV_KEY"]'` <-- '-e' is a collision with the command flag alias for `env` and is duplicated and sent to the Dyno by mistake.
**NOTE**: Reverting the sorted args is no longer needed since a direct slice from the `process.argv` is performed. This operation has been removed.

Fix(run): arguments are incorrectly gathered leading to duplicates

---

packages/cli/src/commands/pg/promote.ts
packages/cli/test/unit/commands/pg/promote.unit.test.ts

This PR fixes a regression defect caused by an early return statement. When no `current` database was found, the entire command would return causing the database to not be promoted and no message given to the user. 
1. Checkout this branch and build
2. Add 2 Heroku PG databases and then delete the first one. (this is a shortcut to remove the `DATABASE` attachment
3. Confirm no `DATABSE` attachment exists
4. execute the command `bin/run pg:promote <postgresql_databse_name> -a <app_name>`
5. Verify the output includes `pg:promote succeeded.`
**tickets**
[W-16645361](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020ZeyOYAS/view)
[W-16615296](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020D70gYAC/view)

Fix(pg:promote):  `pg:promote` returns early and does not promote when no database name `DATABASE` exists.

---

packages/cli/src/commands/pg/settings/auto-explain/log-format.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/unit/commands/pg/settings/auto-explain/log-format.unit.test.ts

GUS item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001yRu4CYAS/view
This change will allow the customer to set the auto explain format. To be released with work specified in https://salesforce.quip.com/LKrbARg3mg1g with an announcement. 
- CX Doc: https://docs.google.com/document/d/1qqqHjoFLrI2spkfjl8BTKEd0L49IBYuHlr3R3Cc5-oM/edit?pli=1#heading=h.2ac9dp6vi2kc
```
🕙[ 12:34:41 ] ❯ bin/run pg:settings:auto-explain:log-format postgresql-dbright-crystalline-65397 text -a brahyt-dev
auto-explain.log-format has been set to text for postgresql-dbright-crystalline-65397.
Auto explain log output will log in text format.
2024-08-26T19:36:22.000000+00:00 app[postgres.3188942]: [DBRIGHT_WHITE] [40-2]  Query Text: SELECT setting FROM pg_settings WHERE name = 'data_checksums' …
```

feat(cli) created pg setting auto explain format

---

packages/cli/src/commands/pg/settings/log-min-error-statement.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/unit/commands/pg/settings/log-min-error-statement.test.ts

- CX Doc: https://docs.google.com/document/d/1qqqHjoFLrI2spkfjl8BTKEd0L49IBYuHlr3R3Cc5-oM/edit?pli=1#heading=h.2ac9dp6vi2kc
- GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001zR98CYAS/view
```
🕙[ 13:15:59 ] ➜ bin/run pg:settings:log-min-error-statement postgresql-dbright-crystalline-65397 -a brahyt-dev
log-min-error-statement is set to error for postgresql-dbright-crystalline-65397.
Logs all ERROR, LOG, FATAL, and PANIC level messages. (Default)
```
```
🕙[ 13:16:06 ] ➜ bin/run pg:settings:log-min-error-statement postgresql-dbright-crystalline-65397 panic -a brahyt-dev
log-min-error-statement has been set to panic for postgresql-dbright-crystalline-65397.
Logs only PANIC level messages.
----psql----
dfmiscmbm6bodf=> select 1/0;
ERROR:  division by zero …
```

feat(cli) created pg setting for log min error statements

---

packages/cli/src/commands/pg/settings/explain-data-connector-details.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/unit/commands/pg/settings/explain-data-connector-details.unit.test.ts

- CX Doc: https://docs.google.com/document/d/1qqqHjoFLrI2spkfjl8BTKEd0L49IBYuHlr3R3Cc5-oM/edit?pli=1#heading=h.2ac9dp6vi2kc
- GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020B0xzYAC/view
```
🕙[ 14:05:55 ] ➜ bin/run pg:settings:explain-data-connector-details postgresql-dbright-lively-63921 -h -a brahyt-dev-private
UNICORN, do things
USAGE
$ heroku pg:settings:explain-data-connector-details [DATABASE] [VALUE] -a <value> [-r <value>]
FLAGS
-a, --app=<value>     (required) app to run command against
-r, --remote=<value>  git remote of app to use
DESCRIPTION
UNICORN, do things
```
```
🕙[ 14:05:32 ] ➜ bin/run pg:settings:explain-data-connector-details postgresql-dbright-lively-63921 on -a brahyt-dev-private
explain-data-connector-details has been set to true for …
```

feat(cli) add explain postgres data connectors setting

---

.github/workflows/create-cli-release.yml
.github/workflows/devcenter-doc-update.yml
scripts/postrelease/dev_center_docs

This PR re-enables the automation for updating the [CLI command docs](https://devcenter.heroku.com/articles/heroku-cli-commands) on Devcenter. I have tested it by [running the workflow manually](https://devcenter.heroku.com/admin/articles/diff/4088/v205..v206) and it worked great.
[Internal work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001YgOGhYAN/view)

chore: re-enable CLI command docs auto-update

---

.github/workflows/create-cli-release.yml

Adds the `get-version-channel` job to the `needs` array in the `publish-docs` job.

chore: add get-version-channel to needs in publish-docs job

---

.github/workflows/create-cli-release.yml

This is a potential fix for the publish-docs job being skipped in the [9.3.0 release](https://github.com/heroku/cli/actions/runs/11022514759).

fix: fix logic for publish-docs job

---

cspell-dictionary.txt
packages/cli/src/lib/types/fir.d.ts

Adds fir types to types directory and updates the cspell-dictionary.

chore: add fir types

---

packages/cli/src/commands/spaces/index.ts
packages/cli/test/unit/commands/spaces/index.unit.test.ts

Adds a "Generation" column to the spaces table that indicates which generation a space belongs to (fir, cedar, ...)
1. Pull down this branch locally and run `yarn && yarn build`.
2. Run `./bin/run heroku spaces`. You should get a table with a listing of available spaces. The second-to-last column should be titled "Generation" and it should indicate which generation your spaces belong to.
[Internal work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020r00vYAA/view)

feat: add generation column to spaces command

---

cspell-dictionary.txt
packages/cli/src/commands/telemetry/index.ts
packages/cli/src/lib/types/telemetry.d.ts
packages/cli/test/unit/commands/telemetry/index.unit.test.ts

[Gus WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000215aanYAA/view)
This adds `telemetry` index command which displays your telemetry drains for a space or an app.
There are no endpoints yet, so we can't test it yet.

feat: Add telemetry index command to list telemetry drains

---

packages/cli/src/commands/telemetry/info.ts
packages/cli/test/unit/commands/telemetry/info.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000218rQvYAI/view)
This adds telemetry info command, displaying attributes for a telemetry drain by id.

Add telemetry info command

---

packages/cli/src/commands/local/run.ts
packages/cli/src/commands/run/index.ts
packages/cli/src/lib/run/helpers.ts
packages/cli/test/integration/run.integration.test.ts

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000021bmahYAA/view)
This PR fixes a list of edge cases for argument parsing within `heroku run` and `heroku local:run`. 
1. Reorders the `argv` elements in a new array using the order that the user inputted. Since this updated logic needs to be applied to both `heroku run` and `heroku local:run`, the logic has been refactored into a utility function.
2. Flags before the `--` flag separator are not consumed (fixing flag collisions)
3. Complete commands are now being passed to the respective options for Dyno and `foreman()`
**NOTE:** I recommend commenting out the commands' functionality after consuming the args as you can see the bug without having to spin up a dyno. We will also need to do a refactor for this fix …

fix(run): update args parsing logic

---

packages/cli/src/commands/telemetry/remove.ts
packages/cli/test/unit/commands/telemetry/remove.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000215aXkYAI/view)
Adds `telemetry:remove` command. Will accept an ID for a specific telemetry drain, or `--app` to remove all drains associated with an app or `--space` to remove all drains associated with a space.

Add telemetry remove command

---

packages/cli/src/commands/spaces/info.ts
packages/cli/src/commands/spaces/wait.ts
packages/cli/src/lib/spaces/spaces.ts
packages/cli/src/lib/types/spaces.d.ts
packages/cli/test/fixtures/spaces/fixtures.ts
packages/cli/test/unit/commands/spaces/info.unit.test.ts
packages/cli/test/unit/commands/spaces/wait.unit.test.ts

This PR adds space generation to the output from the `spaces:info` and `spaces:wait` commands.
- Pull down this branch locally and run `yarn && yarn build`
- Run `./bin/run spaces:info test-fir-dev-tools` and verify that the generation is included in the output
- Run `./bin/run spaces:info test-fir-dev-tools --json` and verify that the generation is included in the output
- Run `./bin/run spaces:wait test-fir-dev-tools` and verify that the generation is included in the output
- Run `./bin/run spaces:wait test-fir-dev-tools --json` and verify that the generation is included in the output
[Internal work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020mJ3FYAU/view)

feat: add generation info to spaces:info and spaces:wait commands

---

packages/cli/src/commands/apps/create.ts
packages/cli/src/commands/apps/stacks/set.ts
packages/cli/test/unit/commands/apps/info.unit.test.ts
packages/cli/test/unit/commands/apps/stacks/set.unit.test.ts
packages/cli/test/unit/commands/container/push.unit.test.ts

One of the last steps in the [heroku-24 rollout plan](https://salesforce.quip.com/sMobAV0e0Awa) is to set `heroku-24` as the default stack for new apps. That change (https://github.com/heroku/api/pull/15582) will ship on October 23rd.
This PR updates a few areas of the CLI to match the new default. I don't think it's super important to ship this change exactly on October 23rd. A few days before or after is probably fine.

chore(cli): update help text and tests to reference heroku-24

---

install-standalone.sh

Don't know if anything else is needed here, but this fixes the issue described in #1963 where the install script doesn't work on an M1 Mac even though the tarballs exist now.

fix: add ARCH=arm64 to install script

---

packages/cli/src/commands/container/release.ts

Here we're fixing a regression introduced when the command was migrated to OClif Core (CLI version 9.x), because of the differences between the old way of specifying a UX action and the new one.
The code section that determines the _old_ release version needs to run before the create release action. It was being run after the creation because the command was written in a way where the actual action (create release request) was assigned to a function, the old version was fetched and then the UX action was called passing the function as the block to be executed. When migrating, the action call was splat in its `start` and `stop` calls around the request, but the release version fetching wasn't moved before the action call.
[GUS Work Item](https://gus.lightning.force.com/a07EE0000236DX3YAM)

fix(cli): Fixing regression for 'container:release' command

---

packages/cli/src/commands/ps/restart.ts
packages/cli/src/commands/ps/stop.ts
packages/cli/src/commands/spaces/create.ts
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/unit/commands/ps/restart.unit.test.ts
packages/cli/test/unit/commands/ps/stop.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000022n0coYAA/view)
This reworks `ps:stop` and `ps:restart` to work with new fir-compatible APIs. Aligning with `heroku logs`, we will now require explicit flags for dyno name, `--dyno`, and dyno type, `--type`. We'll continue supporting passing DYNO as an argument as a deprecated arg.
With a fir app,
2. Find the name of a dyno and its type by running `heroku ps -a APP_NAME`
3. `./bin/run ps stop --dyno DYNO_NAME`
4. `./bin/run ps restart --dyno DYNO_NAME`
5. `./bin/run ps stop --type DYNO_TYPE`
6.  `./bin/run ps restart --type DYNO_TYPE`
7. Do 3-6 with a cedar app

update dyno restart and stop with fir support

---

.github/workflows/create-cli-release.yml
.github/workflows/ctc.yml
scripts/postrelease/change_management

[W-15021692](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001jwMBjYAM/view) **CLI: Add automated CTC check to the CLI release workflows**
Picking up this work from where Angel left it last.

Refresh CTC workflow

---

packages/cli/src/commands/logs.ts
packages/cli/src/commands/ps/restart.ts
packages/cli/src/commands/ps/stop.ts
packages/cli/src/commands/ps/type.ts
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/unit/commands/logs.unit.test.ts
packages/cli/test/unit/commands/ps/restart.unit.test.ts
packages/cli/test/unit/commands/ps/stop.unit.test.ts
packages/cli/test/unit/commands/ps/type.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000024ZVf9YAG/view)
This updates text based on cx feedback. It includes standardizing `ps:stop`, `ps:restart`, and `logs` on `--process-type` and `--dyno-name`.
1. Pull down branch and `yarn build`
2. Run `heroku logs`, `heroku ps:stop` and `heroku ps:restart` with new flag names.

Update help text and dyno type/process type flag names

---

packages/cli/src/commands/telemetry/add.ts
packages/cli/src/commands/telemetry/index.ts
packages/cli/src/commands/telemetry/remove.ts
packages/cli/test/unit/commands/telemetry/add.unit.test.ts
packages/cli/test/unit/commands/telemetry/index.unit.test.ts
packages/cli/test/unit/commands/telemetry/remove.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000024eNQWYA2/view)
This updates our OTel command implementations to work with the just published APIs. Notably, the APIs at the moment seem to require IDs instead of names, which is not ideal. Our CLI interface almost always expects the name of a resource, not the ID (if a name exists for the resource, of course). So, for now, we have to make an extra API request to get that name. I also added a "You have no telemetry drains" message for the `telemetry` index list command.
1. Pull down branch and `yarn build`
2. `./bin/run telemetry ...` with an app or space
3. see the "you have no drains" message
4. `./bin/run telemetry:add ...` with an app or space
5. `./bin/run telemetry ...` with the app or space using the same app …

Update commands to work with published APIs

---

packages/cli/src/commands/ps/autoscale/enable.ts
packages/cli/test/unit/commands/ps/enable.unit.test.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000201VQxYAM/view)
- pull down this branch and run `yarn && yarn build`
- Using a fir app with a dyno, run `./bin/run ps:autoscale:enable -a APP_NAME --min 1 --max 3`
- You should get an error message that reads "Autoscaling is unavailable for apps in this space. See https://devcenter.heroku.com/articles/generations."

feat: add fir-specific error message for autoscale:enable

---

packages/cli/src/commands/releases/index.ts
packages/cli/src/commands/releases/info.ts
packages/cli/src/commands/releases/rollback.ts
packages/cli/src/lib/releases/releases.ts
packages/cli/src/lib/releases/status_helper.ts
packages/cli/test/unit/commands/releases/index.unit.test.ts
packages/cli/test/unit/commands/releases/info.unit.test.ts
packages/cli/test/unit/commands/releases/rollback.unit.test.ts

[GUS WI 1](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000024xGDsYAM/view)
[GUS WI 2](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000024wRJaYAM/view)
With fir APIs, a new attribute, `eligible_for_rollback`, has been introduced to determine if that release can be rolled back to. This PR:
1. Updates `releases:info` to display the value explicitly
2. Updates `releases` to display `expired` status when a release is expired
3. Updates `releases:rollback` to filter based on rollback eligibility
4. Updates color of `v` label in `releases` to account for `expired` status
There aren't any releases created that are expired (yet?), but running `releases`, `releases:info`, and `releases:rollback` on an app to ensure no regressions introduced is good.

Update release commands to work with eligibility attribute.

---

packages/cli/src/commands/spaces/create.ts
packages/cli/src/commands/spaces/trusted-ips/add.ts
packages/cli/src/commands/spaces/trusted-ips/index.ts
packages/cli/src/commands/spaces/trusted-ips/remove.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000021CssvYAC/view)
`inbound-ruleset` is part of v3. This switches API calls away from the `3.dogwood` variant to v3.

Move trusted-ip commands to use v3.

---

packages/cli/src/commands/ps/index.ts
packages/cli/src/lib/types/app_process_tier.ts
packages/cli/src/lib/types/dyno_extended.d.ts
packages/cli/test/unit/commands/ps/index.unit.test.ts

Here we introduce changes to correctly parse dyno names for both Cedar & Fir generation apps, updating requests to use the `3.sdk` variant.
[GUS Work Item](https://gus.lightning.force.com/a07EE00001wVfD5YAK)

Handle dyno name parsing for Fir apps

---

packages/cli/src/commands/addons/create.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000024oOrVYAU/view)
This PR adds a disclaimer when creating inference models using `heroku addons:create`
1. Pull down branch & `yarn` it up
2. Confirm disclaimer is present when creating an inference model instance via `./bin/run addons:create heroku-inference-staging:claude-3-5-sonnet -a heroku-cli-test-staging`
3. Destroy addon for clean up via `./bin/run addons:destroy <INFERENCE_MODEL_ID> -a heroku-cli-test-staging`

feat(addons): add inference disclaimer

---

packages/cli/package.json
yarn.lock

Updates the v10 branch to use the ps-exec plugin beta version for testing.
- pull down this branch and run `yarn` and `yarn build`
1. If you haven't already make sure you have a fir app with a dyno and a cedar app with a dyno created and ready for testing
1. Pull down this branch and run `yarn` and `yarn build`
Using your fir app:
1. Run `./bin/run ps:exec 'node -i' -a YOUR_FIR_APP`
- Validate that the command exits and you see an error message that says "This command is unavailable for this app. Use `heroku run:inside` instead. See https://devcenter.heroku.com/articles/run-tasks-in-an-existing-dyno."
2. Run `./bin/run ps:forward 8080 -a YOUR_FIR_APP`
- Validate that the command exits and you see an error message that says "This command is unavailable for this app.  See …

feat: update plugin-ps-exec to latest beta

---

.github/workflows/create-cli-release.yml

🤞 this fixes the issue with our publish-docs job. This fix is in response to this error we are seeing when running this job:

chore: read isStableRelease from JSON in publish-docs job

---

packages/cli/package.json
packages/cli/src/commands/buildpacks/index.ts
packages/cli/src/lib/buildpacks/buildpacks.ts
packages/cli/test/unit/commands/buildpacks/index.unit.test.ts
yarn.lock

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000021TcXhYAK/view)
With fir, buildpack data is now configured via project.toml and the active state of what buildpacks are installed for an app is not stored explicitly in Platform API. For the `buildpacks` command, we'll now display that state as derived from the oci image from the latest release of an app.
1. pull down this branch and `yarn build`
2. `./bin/run buildpacks --app APP` where APP is a cedar app
3. see no difference from what is in production
4. `./bin/run buildpacks --app APP` where APP is a fir app
5. See that it does not fail, and displays the relevant cnb buildpack(s)

Get buildpacks from latest release for fir apps

---

packages/cli/src/commands/pipelines/diff.ts
packages/cli/src/commands/pipelines/promote.ts
packages/cli/src/lib/api.ts
packages/cli/src/lib/pipelines/ownership.ts
packages/cli/src/lib/pipelines/render-pipeline.ts
packages/cli/test/unit/commands/pipelines/diff.unit.test.ts

Here we add Fir pipelines support to command `pipelines:diff` requiring to read the Github commit SHA from the release OCI image, instead of the slug used for Cedar apps.
It was required to introduce some new interfaces based on the Fir types on a shared library and that made necessary to update other usages of the same functions in other `pipelines` topic commands, but changes are minimal.
- Fetch this branch, run `yarn` and `yarn build`.
- Run `heroku pipelines:diff -a particleboard-staging`. There shouldn't be any errors and it should be up to date with `particleboard-production`.
- Repeat using `./bin/run pipelines:diff -a particleboard-staging`. The output should be exactly the same, no errors.
- Run `heroku pipelines:diff -a my-ruby-gsg-staging`. It errors out stating that no …

feat(cli): Add Fir support to 'pipelines:diff'

---

packages/cli/src/commands/telemetry/add.ts
packages/cli/test/unit/commands/telemetry/add.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000025UeKGYA0/view)
Currently, if the working directory is a heroku remote defined, a user cannot add a space telemetry drain. This is because `--space` and `--app` are defined as exclusive, and `Flags.app` will automatically pick up the local heroku remote if it can. This PR changes the `app` flag to a `string`. This means this command will _not_ pick up the local remote even if `--space` is not provided.
1. pull down this branch and `yarn build`
2. `./bin/run telemetry:add --space some-space fakerandomtext --endpoint url.com --transport http`
3. you should not see a `--space cannot also be provided when using --app` error

fix: bug with telemetry:add

---

.github/workflows/devcenter-doc-update.yml
.github/workflows/pack-upload.yml

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000020GZIaYAO/view)
This updates the `actions/upload-artifact` and `actions/download-artifact` actions we rely on to v4. The new versions have been successfully tested with the 9.5.1-beta.0 prelease, https://github.com/heroku/cli/tree/prerelease/9.5.1-beta. This PR also removes the redundant `Upload md file as artifact` action now that we have confidence in our normal oclif dev docs upload.

Update artifact download/uplaod to v4, remove extra docs md upload

---

.github/workflows/create-cli-release.yml
.github/workflows/devcenter-doc-update.yml
.github/workflows/pack-upload.yml
CHANGELOG.md
docs/addons.md
docs/pg.md
packages/cli/CHANGELOG.md
packages/cli/src/commands/addons/create.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts

Revert "update 10.0 alpha"

---

cspell-dictionary.txt
packages/cli/src/commands/run/inside.ts

[Internal work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000025gXf8YAE/view)
Updates the the run:inside help text to match CX expectations (linked in the internal work item). Also adds named args so that they also appear in the documentation.
- Clone this branch and run `yarn` and `yarn build`
- Run `./bin/run run:inside --help` and verify that the help text matches CX expectations
- Using the dyno id from a fir app, run `./bin/run run:inside DYNO_ID bash -a APP_NAME` to run bash in a dyno
- You can find the dyno id by running `heroku ps -a APP_NAME`
- run `./bin/run run:inside bash -a APP_NAME` to validate that an error message tells the user that they are missing a required arg. It's going to say that you are missing the COMMAND arg because it's looking for the …

refactor: update run:inside help text and add named args

---

packages/cli/src/commands/telemetry/add.ts
packages/cli/src/commands/telemetry/update.ts
packages/cli/test/unit/commands/telemetry/add.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000026GoMVYA0/view)
This changes the interface to `telemetry` command in the following ways to improve usability:
1. In `telemetry:add`, moves `HEADERS` from an argument to a flag, and makes it not required
2. In `telemetry:add`, moves `endpoint` from a flag to an argument
3. In `telemetry:add`, makes `transport` not required and defaults to `http`
4. In `telemetry:update`, moves `HEADERS` from an argument to a flag

Move endpoint to ARG, headers to flag

---

cspell-dictionary.txt
packages/cli/src/commands/run/inside.ts
packages/cli/src/lib/run/helpers.ts
packages/cli/test/unit/lib/run/helpers.unit.test.ts

Changes implemented here are better described on [this Slack thread](https://salesforce-internal.slack.com/archives/C06NM9FFY57/p1731952194176329) (Heroku internal).
TL;DR we're providing `heroku run:inside` for customers on Fir Pilot to replace `heroku run` which isn't supported on Fir apps yet, to run arbitrary commands on a dyno. For CNB stack apps (all Fir apps, currently), commands provided by a buildpack or depending on configs set by a buildpack need to be run through an entrypoint script called `launcher`). Here we first check the app stack and if it's a CNB app, we prepend the string `launcher` to the command being invoked by default.
We also change some copy texts to the approved CX strings, remove the `hidden` property for this command to be exposed and add a `--no-launcher` …

Prepend 'launcher' to commands executed with 'heroku run:inside'

---

.github/workflows/create-cli-release.yml
.github/workflows/devcenter-doc-update.yml
.github/workflows/promote-release.yml
.github/workflows/start-gh-release.yml
.github/workflows/tps-check-lock.yml
.github/workflows/tps-record-release.yml

This PR updates our new change management workflows in a couple of ways:
- It moves the check-for-moratorium and change-management workflows to their own github workflow files
- This will make testing them easier and will enable to us to run them independently in case of a failure
- It updates the create-cli-release and start-gh-release workflows so that they require the moratorium check for all stable releases.
This PR also includes a small change that will hopefully fix the devcenter-doc-update workflow

chore: update moratorium check and change management workflows

---

.github/workflows/create-cli-release.yml
.github/workflows/start-gh-release.yml

Updates our release process to fix a problem with our prereleases.
Since our prod release process is controlled through two Github workflows, I had previously added the moratorium check as a required job for each workflow. However, the create-cli-release workflow is also used by our prerelease process, for which we do not need to check the moratorium status. Unfortunately, requiring the moratorium check in this workflow resulted in prereleases not being published because the check was not being run.
This PR, then removes that requirement from the create-cli-release workflow, meaning that we will have to depend on the moratorium check in the start-gh-release workflow to catch a moratorium as part of the stable release process.

chore: fix moratorium check process for prereleases

---

packages/cli/src/commands/addons/create.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000026JsgjYAC/view)
Updates the legal message for `ai:models:create` to match the desired message (see internal work item). When a user runs `ai:models:create`, they should get this message:
- Fetch this branch.
- Run ```yarn && yarn build```.
- Set the `HEROKU_INFERENCE_ADDON` to the production canary add-on via `export HEROKU_INFERENCE_ADDON="inference-staging"`
- Create a test app: ```heroku apps:create test-cli-plugin-ai``` 
- Run ```./bin/run addons:create heroku-inference-staging:claude-3-5-sonnet -s test-cli-plugin-ai -t test-cli-plugin-ai``` to create a provisioned model.
- Check that the legal message printed matches the message in the work item.
- NOTE: The message has been changed slightly to add links to …

chore: update legal message for addons:create and test

---

packages/cli/src/lib/spaces/spaces.ts
packages/cli/src/lib/types/fir.d.ts
packages/cli/test/fixtures/spaces/fixtures.ts
packages/cli/test/unit/commands/spaces/info.unit.test.ts
packages/cli/test/unit/commands/spaces/wait.unit.test.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000262f6QYAQ/view)
In the output of the `spaces:info` and `spaces:wait` commands, the "generation" field was showing the UUID and the name of the generation, instead of just the name. This was due to a change in the API. This PR updates the output to only show the name.
- Pull down this branch and run `yarn` and `yarn build`
- Run `./bin/run spaces:info -s FIR-SPACE-NAME`. Verify that the output shows only the name of the generation and not an object with the UUID.
- Run `./bin/run spaces:info -s CEDAR-SPACE-NAME`. Verify that the output shows only the name of the generation and not an object with the UUID
- Run `./bin/run spaces:wait -s FIR-SPACE-NAME`. Verify that the output shows only the name of the generation …

fix: show only generation name in spaces:info output

---

packages/cli/src/lib/run/dyno.ts

Fixes the hanging process when no SSH keys or invalid SSH keys are used to run a process inside a dyno
1. Move all keys from the default location `~/.ssh` to another directory
2. create another key `ssh-keygen`
3. Don't upload it to heroku
4. run inside `./bin run run:inside -a YOUR_APP YOUR_DYNO "node -v"
5. **OBSERVE**: The `Permission denied (publickey)` error is thrown and the process exits with exitcode 1

Fix: run:inside hangs (doesn't error) when no/invalid SSH key

---

packages/cli/package.json
yarn.lock

Upgrades the CLI to use v2.6.0 of ps-exec instead of v2.6.0-beta.

feat: upgrade ps-exec to v2.6.0

---

CODEOWNERS
cspell-dictionary.txt

Issues like this one should get routed to the Heroku CLI tag: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000026XxJ0YAK/view
This change should enable that routing.

Update CODEOWNERS to assign security issues to appropriate team

---

.github/workflows/cache-invalidation.yml
.github/workflows/pack-upload.yml
.github/workflows/promote-windows.yml
.github/workflows/promote.yml

awscli comes pre-installed on the [ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#cli-tools) runner. Installing this way was causing our builds to fail once ubuntu-latest updated to Ubuntu 22. This has been tested with the 10.0.1-beta release.
**EDIT**
I found a few more places where we are installing awscli in our workflows and removed them. However, I only removed them in workflows where we are running on the ubuntu-latest image. In a couple of other workflows we are using a Heroku private runner image and it appears that awscli is [not installed there](https://devcenter.heroku.com/articles/stack-packages).

chore: remove installation of awscli in workflows

---

packages/cli/src/commands/pipelines/diff.ts
packages/cli/src/lib/api.ts
packages/cli/src/lib/apps/generation.ts
packages/cli/src/lib/buildpacks/buildpacks.ts
packages/cli/src/lib/types/fir.d.ts
packages/cli/src/lib/types/github.d.ts
packages/cli/test/fixtures/apps/fixtures.ts
packages/cli/test/unit/commands/pipelines/diff.unit.test.ts
packages/cli/test/unit/lib/apps/generation.unit.test.ts

Fixes the problem with pipelines failing on v10
use `./bin/run pipelines:diff -a heroku-vscode-staging` to test - this pipeline and apps should be accessible to all heroku-dev-tools team members

fix: pipeline diff fails on v10

---

packages/cli/src/commands/drains/index.ts
packages/cli/src/commands/telemetry/index.ts

Fixes an issue with listing telemetry drains when a heroku remote exists and the `--team` flags is applied.
e.g. `heroku telemetry --space justins-dev-space` yields this error:
> ›  Error: The following error occurred:
> ›   --app cannot also be provided when using --space
> ›  See more help with --help
##To test 
1. build this branch and `./bin/run telemetry --space justins-dev-space`
[W-17568474](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027kJEmYAM/view)

fix: Unable to list drains for a space in fir

---

packages/cli/src/commands/spaces/destroy.ts
packages/cli/test/unit/commands/spaces/destroy.unit.test.ts

This PR provides an updated warning message to users that the ipv4 and ipv6 addresses previously associated with their soon to be destroyed space will be re-used and to take appropriate security precautions.
to test:
1. delete a space
2. observe warning message
[CX Review Request Link](https://salesforce-internal.slack.com/archives/C028EAW6SDB/p1736529165702709)

feature:  Update  command warning message for Fir spaces

---

CODEOWNERS

Updating the codeowners file to the correct team.

chore: set codeowners to dev tooling team

---

packages/cli/src/analytics.ts
packages/cli/src/hooks/postrun/performance_analytics.ts
packages/cli/src/hooks/prerun/analytics.ts

This PR boosts execution performance by 2x. 
Before: Analytics was run sequential to command execution.
After: Analytics runs parallel to command execution but is awaited if the command finishes first.
This give approx 100% increase in performance.

Updated analytics to be passive yet guaranteed to complete before exit

---

packages/cli/src/commands/telemetry/add.ts
packages/cli/test/fixtures/telemetry/fixtures.ts
packages/cli/test/unit/commands/telemetry/add.unit.test.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000282ViQYAU/view
Currently we are sending `otlpgrpc` as a value to API when creating a grpc telemetry drain. The correct value should be `otlp`.
1. Pull down this branch and yarn build
2. `./bin/run telemetry:add SOME_URL --app SOME_FIR_APP --transport grpc
3. See success

fix: send correct value to api for grpc telemetry drains

---

install-standalone.sh

This applies two changes from the community:
* https://github.com/heroku/cli/pull/3175 which loosens regex check to support $PATH check and resolves https://github.com/heroku/cli/issues/3166
* https://github.com/heroku/cli/pull/2205 which moves the path check to after the OS checks, as that check only makes sense for specific OSes, and as the author points out, it's certainly more helpful to know when the OS is not supported before knowing if you satisfy the $PATH check

Update install-standalone script

---

packages/cli/package.json
yarn.lock

Update resolution of `node-fetch` to just use 2.7. This should resolve a security vulnerability.

Update node-fetch to 2.7

---

yarn.lock

Should resolve a security vulnerability

chore: update cross-spawn 7

---

packages/cli/src/commands/addons/open.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000285wZdYAI/view
Web services is deprecating 3.add-ons-sso variant and has moved its functionality to 3.sdk. This updates our use of that variant.
Because of the interaction with `sudo`, it's a bit annoying to test this. Here's how I tested:
1. Pull down this branch
2. In `commands/addons/open.ts`, comment out lines 97 and 99. Also comment out lines 101-122.
3. `yarn build`
4. `./bin/run addons:open DATABASE_NAME --app APP_NAME

chore: switch from 3.add-ons-sso to 3.sdk

---

CODEOWNERS

Our CODEOWNERS file is using a shelved schema for setting up the required GUS information and the wrong team and product tags.
This PR just fixes that.
GUS WI: [W-17568080](https://gus.lightning.force.com/a07EE000027kEFKYA2)

Fix GUS-aware CODEOWNERS file

---

packages/cli/src/commands/apps/info.ts
packages/cli/src/commands/buildpacks/index.ts
packages/cli/src/commands/pipelines/diff.ts
packages/cli/src/commands/ps/autoscale/enable.ts
packages/cli/src/commands/spaces/create.ts
packages/cli/src/commands/spaces/destroy.ts
packages/cli/src/commands/spaces/index.ts
packages/cli/src/lib/apps/generation.ts
packages/cli/src/lib/run/log-displayer.ts
packages/cli/src/lib/spaces/spaces.ts
packages/cli/src/lib/types/fir.d.ts
packages/cli/test/fixtures/apps/fixtures.ts
packages/cli/test/fixtures/spaces/fixtures.ts
packages/cli/test/unit/commands/apps/info.unit.test.ts
packages/cli/test/unit/commands/spaces/create.unit.test.ts
packages/cli/test/unit/commands/spaces/destroy.unit.test.ts
packages/cli/test/unit/commands/spaces/info.unit.test.ts
packages/cli/test/unit/commands/spaces/wait.unit.test.ts
packages/cli/test/unit/lib/apps/generation.unit.test.ts

This PR provides the following:
1. partially updates interfaces to match the [3.sdk](https://github.com/heroku/api/blob/main/schema/variants/3.sdk/schema.json) schemas 
2. adds a utility function to get the generation kind from the various types.
Testing involves execution of commands where generation kinds are retrieved and ensuring they are correct. Please see commit for files affected.

feat(utils): add a getGeneration helper function

---

packages/cli/package.json
packages/cli/src/lib/run/log-displayer.ts
packages/cli/test/helpers/init.js
packages/cli/test/integration/logs.integration.test.ts
packages/cli/test/unit/lib/run/log-displayer.unit.test.ts
yarn.lock

This PR replaces [@heroku/eventsource](https://github.com/heroku/heroku-eventsource) with a modern `fetch` implementation.
1. Multiple reports of SSL errors have been seen. logplex urls sometimes use redirects on client machines with HTTP_PROXY.  Native fetch handles this for us.
1. The [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) API is now a widely available web standard but it is not available in Node. The `@heroku/eventsource` library was meant as a polyfill for Node however, Node is not adopting this API. Instead, fetch is commonly used for Server Side Events in node
1. `@heroku/eventsource` is very old and is no longer active in development (security fixes only)
1. run `bin/run logs -a <APP_NAME> --tail`

fix(W-17265927): SSL issues with heroku logs

---

packages/cli/src/commands/keys/add.ts
packages/cli/test/unit/commands/keys/add.unit.test.ts

This PR corrects the behavior of the `keys:add` command to match the [devcenter docs](https://devcenter.heroku.com/articles/keys) while maintaining full functionality. 
1. Rename or generate a key in `~/.ssh` that is *not* the default name of `id_rsa.pub`
2. run `bin/run keys:add`
3. *OBSERVE* The behavior in the devcenter docs is seen
4. Optionally Test other flows like one key with the default name of `id_rsa.pub` and multiple keys, etc.

fix(W-17544077): SSH key install via SSH happy path in docs didn't work

---

packages/cli/src/lib/addons/util.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts

This PR fixes a TypeError that occurred because no checks were made to inspect the error object before accessing it's properties. 
View Repro steps in the [GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027c6qEYAQ/view) ticked. Note these repo steps no longer yield the TypeError mentioned.

fix(W-17545010): Error when trying to clone a redis instance

---

packages/cli/src/commands/pg/wait.ts

This PR updates the message in pg:wait from "Addon not found" to "Waiting for provisioning to start..."
The start of the provisioning process can take 5-10 seconds in some cases. The "Addon not found" message is inaccurate and can confuse the user. 
Provision an add-on and use `pg:wait`
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027cHB5YAM/view)

fix(W-17544106): pg:wait command addon not found warning

---

.github/workflows/create-cli-release.yml
.github/workflows/promote-release.yml

Moves the `create-fig-autocomplete-pr` job out of the `promote-release` workflow so that if it fails it does not block the `publish-docs` job from running.

chore: move fig workflow to create-cli-release.yml

---

packages/cli/package.json
yarn.lock

bumps `@heroku-cli/command` to 11.5

bump heroku-cli-command

---

packages/cli/src/commands/buildpacks/index.ts
packages/cli/src/commands/logs.ts
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/unit/commands/buildpacks/index.unit.test.ts

This PR updates the `buildpacks` command to distinguish between classic and fir buildpacks
1. run `buildpacks --help` Note the updated help text
2. run `buildpacks -a <APP_NAME>` where APP_NAME is a Fir app and again for a cedar app.
3. Observe the new styled headers

chore(W-17237970): Improve buildpacks:index for fir apps

---

.github/workflows/devcenter-doc-update.yml

The last time we tried to run this workflow it [failed](https://github.com/heroku/cli/actions/runs/13423136770/job/37501302121) on the Ruby installation. However, since Ruby seems to be [preinstalled](https://github.com/actions/runner-images/blob/ubuntu24/20250209.1/images/ubuntu/Ubuntu2404-Readme.md) on the Ubuntu 24.04 image, we should be able to remove the installation entirely.
You can see this [workflow passing here](https://github.com/heroku/cli/actions/runs/13503469950/job/37727456975) (without pushing to devcenter).

chore: remove ruby install from devcenter-doc-update.yml

---

packages/cli/src/commands/pg/outliers.ts

Adds support for new column names in `pg_stat_statements` in Postgres v17.
Testing notes:
- `yarn`
- `yarn build`
- test on Postgres v16:
```
./bin/run pg:outliers HEROKU_POSTGRESQL_TCOLL_GRAY_URL -a tc-data-dev
total_exec_time | prop_exec_time | ncalls |  sync_io_time   |                                                              query                                                               
-----------------+----------------+--------+-----------------+----------------------------------------------------------------------------------------------------------------------------------
00:07:33.785423 | 97.9%          | 20,673 | 00:00:00        | SELECT queryid AS query_id, calls, total_time, blk_read_time, blk_write_time                                                    +
| …
```

feat: add support for new columns in PG17

---

packages/cli/src/commands/telemetry/index.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002AjtXwYAJ/view
Allows users to use `-a` instead of `--app` for the `heroku telemetry` command.
- Pull down this branch and run `yarn && yarn build`
- With any app (doesn't matter if it has any telemetry drains), run `./bin/run telemetry -a APP_NAME`
- You should see the command successfully run, without the error that tells you `-a` is a nonexistent flag.

fix: add shortcode for --app flag in telemetry command

---

packages/cli/src/commands/spaces/create.ts
packages/cli/test/unit/commands/spaces/create.unit.test.ts

Applies change originally from #3106. Removes limited GA language from price warning for `spaces:create` as it is no longer necessary.

fix: remove limited GA phrasing from spaces:create

---

packages/cli/src/commands/redis/credentials.ts
packages/cli/src/commands/redis/stats-reset.ts
packages/cli/src/commands/redis/wait.ts
packages/cli/src/lib/redis/api.ts

There's a bug in the `request` function from the shared Redis API lib file used for most of `redis:...` commands, where the default value for the request body is an empty object (`{}`). That makes all `GET` requests using that function to send that empty body when, according to standards, `GET` requests shouldn't send a body.
Here we change the default to a `null` value, so no body gets sent with `GET` requests and add an empty object body to all non-GET requests that would've inherited the previous default to avoid behavior changes.
Checkout this branch, ensure you're running Node 20.x and run `yarn && yarn build`. For the tests you will need access to a test app with a Redis database installed. If you don't have one at hand let me know and I can add you to one of my test apps.
There …

fix(redis): Remove empty object body from GET requests to Redis API

---

packages/cli/package.json

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000028zx82YAA/view)
Adds an alias for `heroku-repo` since the plugin was renamed to `@heroku-cli/plugin-heroku-repo`.

feat: add alias for heroku-sudo plugin

---

packages/cli/src/commands/addons/plans.ts
packages/cli/src/lib/addons/util.ts
packages/cli/test/fixtures/addons/fixtures.ts
packages/cli/test/integration/access.integration.test.ts
packages/cli/test/unit/commands/addons/plans.unit.test.ts

[W-18033523](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002B2sBeYAJ/view)
This adds support for displaying `metered` when a given addon's pricing plan is marked as metered. For example:
At the moment, we don't have testable metered plans in production or staging. We'll test once that's available.

If addon is metered, print metered label and link to elements page

---

.github/workflows/pack-upload.yml

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002ArwkCYAR/view)
Updates our pack-deb job to use ubuntu-latest rather than ubuntu-20.04, which is being deprecated.

chore: update pack-deb job to use ubuntu-latest

---

packages/cli/src/commands/usage/addons.ts
packages/cli/src/lib/addons/util.ts
packages/cli/test/unit/commands/usage/addons.unit.test.ts

[W-18033570](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002B2Q82YAF/view)
This adds a new command to display metered usage for addons associated with an app. It displays each token and its value for each metered addon of a given app. If no metered usage data is returned by the API, it displays a generic message indicating that.
Example output:
2. `./bin/run usage:addons --app APP` where APP has no attached metered addons
3. `/bin/run usage:addons --app APP` where APP is a personal app that has attached metered addons
4. `/bin/run usage:addons --app APP` where APP is a team app that has attached metered addons

Add new usage addons command

---

packages/cli/src/commands/pg/upgrade/cancel.ts
packages/cli/test/unit/commands/pg/upgrade/cancel.unit.test.ts

This PR creates the `pg:upgrade:cancel` command. 
Work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BNrJ4YAL/view
Please refer to [this doc](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing) for more information related to the new pg:upgrade:* commands
**Scenario 1:**
pg:upgrade:cancel on essential tier db
**Scenario 2:**
pg:upgrade:cancel on follower db
**Scenario 3:**
pg:upgrade:cancel on leader db with no upgrade scheduled
**Scenario 4:**
pg:upgrade:cancel on leader db with upgrade scheduled but not actively running
**Scenario 5:**
pg:upgrade:cancel on leader db with upgrade actively running
**Scenario 6:**
help on pg:upgrade:cancel

feat: create pg:upgrade:cancel command

---

cspell-dictionary.txt
packages/cli/src/commands/pg/upgrade/dryrun.ts
packages/cli/test/unit/commands/pg/upgrade/dryrun.unit.test.ts

This PR creates the pg:upgrade:dryrun command.
Work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BO2UbYAL/view
Please refer to [this doc](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing) for more information related to the new pg:upgrade:* commands
**pg:upgrade:dryrun on essential tier db**
**pg:upgrade:dryrun on follower db**
**pg:upgrade:dryrun on leader db with version flag**
**pg:upgrade:dryrun on leader db without version flag**
**pg:upgrade:dryrun on leader db when version upgrade is going on**
**pg:upgrade:dryrun help**

feat: create pg:upgrade:dryrun command

---

packages/cli/src/commands/pg/upgrade/index.ts
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/unit/commands/pg/upgrade/index.unit.test.ts

[Work item
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BNj79YAD/view)
This PR updates the `pg:upgrade` command. It also adds a couple of new error messages and formatting.
Please refer to [this doc](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing) for more information related to [pg:upgrade](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?tab=t.0).
Based from the [pg:upgrade:prepare PR](https://github.com/heroku/cli/pull/3265)
Check out this branch and run `yarn && yarn build`
1. Run `./bin/run pg:upgrade` on a Standard-Tier leader DB 
```
nmuthu@nmuthu-ltm8kcc cli % ./bin/run pg:upgrade DATABASE_URL -a pg-upgrade-test-app
›   Warning: We’re deprecating this command. To upgrade …
```

feat: updating pg:upgrade with deprecation warning

---

packages/cli/src/commands/telemetry/info.ts
packages/cli/src/commands/telemetry/update.ts
packages/cli/src/lib/telemetry/util.ts
packages/cli/src/lib/types/telemetry.d.ts
packages/cli/test/fixtures/telemetry/fixtures.ts
packages/cli/test/unit/commands/telemetry/info.unit.test.ts
packages/cli/test/unit/commands/telemetry/update.unit.test.ts

[W-17329013](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000265iheYAA/view)
This fixes a few issues with `telemetry:info` and `telemetry:update`
1. Fixes `telemetry:info` and `telemetry:update` so that it displays the `transport` attribute instead of `kind`, aligning with how our command flags are structured
2. `telemetry:info` and `telemetry:update` will now display the name of the app or space associated with a telemetry drain
3. `telemtry:info` and `telemetry:update` now display header data as a json structure surrounded by `{}` instead of just key/values
4. `telemetry:update` will now appropriately send `otlp` for grpc transport drains instead of `otlpgrpc`
1. Pull down branch and `yarn build`
2. Run `./bin/run telemetry:info TELEMETRY_ID` where TELEMETRY_ID is the …

Fix display and update of grpc vs httpc transport protocol

---

packages/cli/src/commands/usage/addons.ts
packages/cli/test/unit/commands/usage/addons.unit.test.ts

[W-18033605](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002B2o29YAB/view)
This adds the `--team` option to the `usage:addons` command. It will list all the apps and any metered addons with their values:
1. Pull down branch and `yarn build`
2. `./bin/run  usage:addons --team TEAM` where team is a heroku team that has metered addons in one or more of its apps
3. `./bin/run  usage:addons --team TEAM` where team is a heroku team that has no metered addons

feat: add team option to usage:addons command

---

packages/cli/src/commands/pg/upgrade/run.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/unit/commands/pg/upgrade/index.unit.test.ts
packages/cli/test/unit/commands/pg/upgrade/run.unit.test.ts

This PR creates the pg:upgrade:run command. This PR also includes some tiny cx changes to the pg/upgrade/index.ts file.
Work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BNfSLYA1/view
Please refer to [this doc](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing) for more information related to the new pg:upgrade:* commands
**pg:upgrade:run on essential tier with version flag**
**pg:upgrade:run on essential tier without version flag**
**pg:upgrade:run on follower db with version flag**
**pg:upgrade:run on follower db without version flag**
**pg:upgrade:run on leader db with no upgrade scheduled**
**pg:upgrade:run on leader db with upgrade not yet ready**
**pg:upgrade:run on leader db with upgrade scheduled and ready …

feat: create pg:upgrade:run command

---

packages/cli/src/commands/pg/upgrade/wait.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/unit/commands/pg/upgrade/wait.unit.test.ts
packages/cli/test/unit/commands/pg/wait.unit.test.ts

[Work item
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BO0O1YAL/view)
This PR creates the `pg:upgrade:wait` command.
Please refer to [this doc](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing) for more information related to [pg:upgrade:wait](https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?tab=t.0#bookmark=id.bww98j4t3jb1).
Check out this branch and run `yarn && yarn build`
1. Run `./bin/run pg:upgrade:prepare` on a Standard-Tier leader DB and then `pg:upgrade:wait` to see it prepare
```
nmuthu@nmuthu-ltm8kcc cli % ./bin/run pg:upgrade:prepare HEROKU_POSTGRESQL_PUCE_URL -a pg-upgrade-test-app
›   Warning: Destructive action
›   This command prepares the upgrade for …
```

feat: adding pg:upgrade:wait command

---

packages/cli/package.json
packages/cli/src/commands/accounts/add.ts
packages/cli/src/commands/accounts/current.ts
packages/cli/src/commands/accounts/index.ts
packages/cli/src/commands/accounts/remove.ts
packages/cli/src/commands/accounts/set.ts
packages/cli/src/lib/accounts/accounts.ts
packages/cli/test/integration/access.integration.test.ts
packages/cli/test/unit/commands/accounts/add.unit.test.ts
packages/cli/test/unit/commands/accounts/current.unit.test.ts
packages/cli/test/unit/commands/accounts/index.unit.test.ts
packages/cli/test/unit/commands/accounts/remove.unit.test.ts
packages/cli/test/unit/commands/accounts/set.unit.test.ts
packages/cli/test/unit/lib/accounts/accounts.unit.test.ts
yarn.lock

[Work item
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000290DPbYAM/view)
This PR moves the commands from [heroku/heroku-accounts](https://github.com/heroku/heroku-accounts) to the CLI core, migrates them to TypeScript and oclif/core v2, updates and adds descriptions and error text, and adds tests.
These commands made use of functionality from heroku-cli-utils that is implemented differently in heroku-cli/command and oclif. Because of this, the migrated commands may be implemented a little differently than the originals. The overall functionality should be roughly the same and should accomplish the same tasks.
1. Check out this branch and run `yarn && yarn build`
2. Sign into a Heroku account
3. Run `./bin/run accounts:add ACCOUNT_NAME` (the account name can be …

feat: add accounts commands

---

packages/cli/package.json
packages/cli/src/analytics.ts
packages/cli/src/global_telemetry.ts
packages/cli/test/unit/analytics.unit.test.ts
packages/cli/test/unit/global_telemetry.unit.test.ts

Here we change the CLI version string reported to our analytics (Backboard) and telemetry (Honeycomb) services to add the Heroku MCP Server version when running in MCP mode.
- Checkout this branch and run ```yarn && yarn build```.
- Verify you're logged-in to the Heroku CLI.
- Run the following command: ```HEROKU_MCP_MODE="true" HEROKU_MCP_SERVER_VERSION="1.2.3" DEBUG=http ./bin/run whoami```.
To check that the correct version is being sent to Backboard, copy the value assigned to the `data` query param on the request to Backboard (`GET https://backboard.heroku.com/hamurai?data=eyJzb3V...`) and decode the Base64 data with ```echo -n "eyJzb3V..." | base64 -d && echo```. In the decoded JSON data the `properties.version` value should be "10.4.1 (MCP 1.2.3)".
To check that the correct version …

Add MCP version to telemetry

---

packages/cli/src/commands/usage/addons.ts
packages/cli/test/unit/commands/usage/addons.unit.test.ts

[W-18240297](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CR1oSYAT/view)
This updates CLI copy based on cx feedback from https://github.com/heroku/cli/pull/3263. It also adds descriptions for the `--app` and `--team` flags.
1. Pull down and `yarn build`
2. Run `./bin/run usage:addons --help` and see the correct copy

fix: change addon text to add-on, add description to flags

---

packages/cli/src/commands/pg/upgrade/dryrun.ts
packages/cli/src/commands/pg/upgrade/prepare.ts
packages/cli/src/commands/pg/upgrade/run.ts

This PR makes some tiny changes to the messages displayed in the new pg:upgrade:* commands as recommended by the cx team.
Refer to https://docs.google.com/document/d/1FEIQPkWRggz_XWzU3PRI6pFg00TwUKIjqft4IGzCOsY/edit?usp=sharing for more info on the pg:upgrade:* commands.
```
kpremkumar@kpremku-ltm9a2z cli % ./bin/run pg:upgrade:dryrun --help                               
simulates a Postgres version upgrade on a Standard-tier and higher leader database by creating and upgrading a follower database. Heroku sends the results of the test upgrade via email.
USAGE
$ heroku pg:upgrade:dryrun [DATABASE] -a <value> [-c <value>] [-v <value>]
ARGUMENTS
DATABASE  config var containing the connection string, unique name, ID, or alias of the database. To access another app's database, prepend the app …
```

fix: cx updates for pg:upgrade:* commands

---

packages/cli/src/commands/addons/index.ts
packages/cli/src/lib/addons/resolve.ts
packages/cli/test/unit/commands/addons/index.unit.test.ts
packages/cli/test/unit/commands/addons/info.unit.test.ts

[W-18257668](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CaZ4lYAF/view)
Metered addons pricing currently shows as `free` in `addons:info` and `addons:index`. This corrects that behavior by switching to the `3.sdk` variant, which is necessary to get the additional `metered: true` data.
2. Run `./bin/run addons --app APP` where APP has a metered usage addon
3. Run `./bin/run addons:info ADDON --app APP` where ADDON is a metered usage addon that is owned by APP

fix: show metered for metered addons in addons:info and addons:index

---

.github/workflows/devcenter-doc-update.yml

[WI Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CUYuNYAX/view)
This PR fixes the currently failing `devcenter-doc-update` workflow by using a more conventional approach to Ruby installs.
[This passing workflow](https://github.com/heroku/cli/actions/runs/14742808689/job/41384378201) demonstrates the nature of the required script needed to update the devcenter documentation.

chore: update devcenter workflow

---

packages/cli/package.json
packages/cli/src/commands/spaces/create.ts
packages/cli/test/unit/commands/spaces/create.unit.test.ts

[W-18414050](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Dk2QRYAZ/view)
This does two things:
1. Remove the fir pilot warning language when a user creates a fir space. fir is now GA.
2. Slightly modifies the node engines definition in `package.json` to ensure we are asking for the latest `20.x` node version.
1. Pull this branch down and `yarn build`
2. `./bin/run spaces:create --space SPACE_NAME --team TEAM_NAME --generation fir`
3. See that no pilot warning message appears

remove fir pilot language, fix node engine definition

---

packages/cli/src/commands/keys/add.ts
packages/cli/src/lib/ci/source.ts

[W-18293488](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ctf1wYAB/view)
This replaces usage of `ux.info` with `ux.log` in the `keys:add` command. There is no functional difference in the case where we are using `ux.info`.
This also replaces our use of `ux.debug` with `debug` in a `ci` lib function when an expected error condition occurs. The impact here is that the debug output inside this error condition will show up when `DEBUG=*` (or whatever i set via https://github.com/debug-js/debug) rather than the `--debug` option. `--debug` is not used anywhere else in the CLI (we use the debug package instead) and is completely deprecated/removed in future versions of oclif.

refactor: Use ux.log instead of ux.info, replace ux.debug with debug

---

packages/cli/package.json
packages/cli/test/unit/commands/pg/pull.unit.test.ts
yarn.lock

Here we add `@heroku/plugin-ai` as a direct dependency for the Core CLI version we bundle on the MCP Server.
This is required for a new series of tools that need to be implemented over the plugin commands.
There's a weird error happening on a couple unit test for commands `pg:push` and `pg:pull` that needed to be tweaked in order for all tests to pass. I did check both commands still function properly. I haven't been able to detect where that test pollution came from, because doesn't seem related to the actual plugin being included, but maybe comes from some OClif initialization code when loading the plugins.
- If you have the AI plugin installed, uninstall it first with ```heroku plugins:uninstall @heroku/plugin-ai``` 
- Verify the following command fails: ```heroku ai:models:list```
- …

feat: update Add plugin AI as a dependency in MCP feature branch

---

packages/cli/package.json
yarn.lock

[W-18496992](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002EIH4EYAX/view)
This updates `heroku-cli-util` to 9.0.2, resolving some dependency issues. No functional changes.

fix: bump heroku-cli-util

---

install-ubuntu.sh

This PR updates the Heroku CLI installation process in `install-ubuntu.sh` to improve compatibility with newer versions of Ubuntu. It replaces the deprecated apt-key method with a conditional approach: if apt-key is available, it is used; otherwise, the script installs the GPG package, converts the release key to GPG format, and configures the repository to use the keyring method. This ensures the script works on both older and newer Ubuntu systems.
Low. The changes are limited to the Heroku CLI installation logic and add compatibility for newer systems while preserving support for older ones. Existing functionality is maintained, and no other parts of the script or project are affected.
[GUS Ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002DZQ33YAH/view)

fix: install cli on ubuntu 25.04 without using apt-key

---

packages/cli/src/commands/authorizations/create.ts
packages/cli/src/commands/authorizations/index.ts
packages/cli/src/commands/authorizations/info.ts
packages/cli/src/commands/authorizations/revoke.ts
packages/cli/src/commands/authorizations/rotate.ts
packages/cli/src/commands/authorizations/update.ts
packages/cli/src/lib/authorizations/authorizations.ts
packages/cli/test/unit/commands/authorizations/create.unit.test.ts
packages/cli/test/unit/commands/authorizations/index.unit.test.ts
packages/cli/test/unit/commands/authorizations/info.unit.test.ts
packages/cli/test/unit/commands/authorizations/revoke.unit.test.ts
packages/cli/test/unit/commands/authorizations/rotate.unit.test.ts
packages/cli/test/unit/commands/authorizations/update.unit.test.ts
packages/cli/test/unit/lib/authorizations/authorizations.unit.test.ts

[W-18575900](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002EkBPOYA3/view)
This uncomments authorizations commands and make them compatible with oclif/core v4, converting to esm.
1. Pull down branch and yarn build
2. `./bin/run authorizations`
3. `./bin/run authorizations:info AUTHORIZATION_ID`
5. test other authorizations commands as you see fit (bear in mind you will change your production authorizations through this)

refactor: convert authorizations esm

---

scripts/postrelease/test_release

Comments out a test that has been causing our pre-release test runs to fail. The Heroku account we use for these tests no longer has the access needed in order to run this test. Long-term we will need to figure out a better way of testing this command as part of our release process, but for now this should allow our release tests to pass.

chore: comment out heroku members test

---

packages/cli/src/commands/prompt.ts
packages/cli/src/commands/repl.ts

Hiding these commands temporarily until we can fix an issue with the custom docs created for them.

fix: hide repl and prompt commands temporarily

---

packages/cli/src/commands/clients/create.ts
packages/cli/src/commands/clients/destroy.ts
packages/cli/src/commands/clients/index.ts
packages/cli/src/commands/clients/info.ts
packages/cli/src/commands/clients/rotate.ts
packages/cli/src/commands/clients/update.ts
packages/cli/test/unit/commands/clients/create.unit.test.ts
packages/cli/test/unit/commands/clients/destroy.unit.test.ts
packages/cli/test/unit/commands/clients/index.unit.test.ts
packages/cli/test/unit/commands/clients/info.unit.test.ts
packages/cli/test/unit/commands/clients/rotate.unit.test.ts
packages/cli/test/unit/commands/clients/update.unit.test.ts

[W-18575907](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ek54BYAR/view)
This converts the `clients` commands to esm and makes them availabe in the v11 branch.
For destructive actions (e.g., `certs:add`) please make sure to use a test app. We don't want to make certs changes to production or staging apps.
2. `./bin/run clients:create "FAKE" fake-callback.com
3. `./bin/run clients
4. `./bin/run clients:destroy ID where ID is the ID of the fake oauth client you created in step 1

refactor: convert clients to esm

---

docs/pg.md
packages/cli/src/commands/pg/settings/data-connector-details-logs.ts
packages/cli/src/lib/pg/types.ts
packages/cli/test/unit/commands/pg/settings/data-connector-details-logs.unit.test.ts

This PR renames the pg:setting explain_data_connector_details to data_connector_details_logs
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002BpMjhYAF/view
related shogun backend PR: https://github.com/heroku/shogun/pull/20599
related staging doc updates: https://salesforce-internal.slack.com/archives/CCS6NJYG2/p1743180785156639?thread_ts=1742919403.551169&cid=CCS6NJYG2
we noticed that the Dev Center and our code are not aligned on the name of the PGSetting to enable emitting Streaming Data Connectors replication metrics to the Heroku Postgres metrics logs. We're not documenting the right name of the setting to be used.This feature was built for British Airways to have visibility on the spill files and disk usage caused by Streaming Data Connectors, and apparently hasn't …

chore: renaming setting explain_data_connector_details 

---

packages/cli/src/commands/container/push.ts
packages/cli/src/lib/container/docker_helper.ts
packages/cli/test/unit/lib/container/docker_helper.unit.test.ts

- disable attestations and SBOMs if the docker version is >= 24.0.0
- enforcing amd64 images coming from non-amd64 machines (aarch64)
- enforce amd64 on push in addition to build
[W-18012763](https://gus.lightning.force.com/a07EE00002Aut5yYAB)

fix: Disable attestations and SBOMs for Heroku's container registry

---

cspell-dictionary.txt
packages/cli/src/commands/status.ts
packages/cli/src/lib/status/util.ts
packages/cli/src/lib/types/status.d.ts
packages/cli/test/fixtures/status/fixtures.ts
packages/cli/test/unit/commands/status.unit.test.ts

Adds support for SF Trust API to the `heroku status` command.
- The SF Trust API will only be called if the Heroku Status API call fails
- The responses from the SF Trust API endpoints are formatted to fit the current structure of the command response
- The command will error (with an error message already approved by CX) if calls to both the Heroku Status API and SF Trust API fail
There is a lot of logic in here for formatting the responses from the SF Trust API endpoints. The basic outline of the logic is as follows:
- Retrieve data from the SF Trust API endpoints.
- Heroku instances, active incidents, upcoming Heroku maintenances, and localizations.
- Filter the array of active incidents by the array of Heroku instances to get an array of Heroku active incidents.
- Filter the array of …

feat(W-19005486): add support for SF Trust API to status command

---

packages/cli/package.json
yarn.lock

Bumps the version of `@heroku-cli/command` in order to apply domain name validation for Heroku API requests. Also bumps the version of `@heroku/http-call`.
- Check out this branch and run `yarn` and `yarn build`
- Run `HEROKU_HOST=bogus-domain.com ./bin/run whoami`
- You should see a string of warning messages indicating that you have provided an invalid domain and that the default domain is being used instead. We are aware that there are a lot of warning messages that are currently being printed. We will be improving that as part of some follow-up work.
[W-19386384](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002KS9klYAD/view)

feat(W-19386384): add domain name validation for Heroku API requests

---

packages/cli/package.json
yarn.lock

Bumps the version of `@heroku-cli/command` in order to update domain name validation for Heroku API requests. 
- Check out this branch and run 
- `yarn && yarn build`
Run commands 
```
HEROKU_HOST=heroku.com ./bin/run whoami
HEROKU_HOST=herokai.com ./bin/run whoami
HEROKU_HOST=bogus-domain.com ./bin/run whoami
```
You should see successful command run for heroku and heroku 
For bogus-domain.com, see a string of warning messages indicating that you have provided an invalid domain and that the default domain is being used instead. We are aware that there are a lot of warning messages that are currently being printed. We will be improving that as part of some follow-up work.
Gus Work Item: [W-19527406](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002LBNFaYAP/view)

fix(W-19527406): update domain name validation for Heroku API requests

---

packages/cli/src/commands/pg/upgrade/dryrun.ts
packages/cli/test/unit/commands/pg/upgrade/dryrun.unit.test.ts

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002LG2UYYA1/view)
This PR removes the destructive warning copy "Destructive action." This is to reduce confusion for the user when running the dryrun command to clarify that it's not destructive, given the nature of the command.
- pull down branch and `yarn && yarn build`
- run `./bin/run pg:upgrade:dryrun <DATABASE> -a <your-app>` and confirm that the destructive copy is no longer there

chore: remove destructive copy for pg:upgrade:dryrun

---

packages/cli/src/commands/run/detached.ts
packages/cli/src/commands/run/index.ts
packages/cli/src/commands/run/inside.ts
packages/cli/src/lib/run/helpers.ts
packages/cli/test/integration/run.integration.test.ts
packages/cli/test/unit/lib/run/helpers.unit.test.ts

In order to make `heroku run` commands more intuitive by ensuring that common/expected binaries are in the dyno's path, we need to add "-- launcher" to the beginning of every command that users want to run. For example, if the user runs the command `heroku run bash -a MY_APP`, the command should be called as "heroku run -- launcher bash -a MY_APP".
Since there may be cases where user want to run the command without using "launcher", this change includes a param `--no-launcher` which can be used to remove it from the command.
This change was previously introduced to the `heroku run:inside` command in #3116, so I refactored that command to use the shared helper that is used by `heroku run`.
[GUS work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002M2Ao0YAF/view) …

feat: Prepend launcher to `heroku run` commands for fir
