heroku/cli

cli.go
command.go
flag.go
flag_test.go
git.go
io.go

also cleaned up git error messages

improved arg parsing

---

cli.go
context.go
io.go
login.go
main.go
whoami.go

use v4 for login

---

plugins.go

once it is finished https://github.com/dickeyxxx/elephant

use custom npm server

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/franela/goreq/README.md
Godeps/_workspace/src/github.com/franela/goreq/goreq.go
Godeps/_workspace/src/github.com/franela/goreq/goreq_test.go
main.go
request.go
two_factor.go
update.go

fixes https://github.com/heroku/heroku-sudo/issues/137

added 2fa alias

---

gode/setup.go

do this by using goreq which is already properly configured

use custom root ssl certs for iojs download

---

plugins.go
update.go

only update plugins that are not symlinked

fix unlinking of plugins under update

---

gode/setup.go

Revert "use system tmp dir"

---

main.go
which.go

@jmccartie @dmathieu @ransombriggs

added hidden which command

---

io.go

but only inside of node, not with the go code that won't work under windows
ready for review @ransombriggs

enable color on windows

---

plugin_cache.go
plugins.go
update.go

skip looking up plugins by running ls ~/.heroku/node_modules instead
using plugin-cache.json as the canonical plugin source.

fix slow plugin reading

---

gode/exec.go
gode/exec_test.go
gode/vars.go
plugins.go

this is to avoid making the process title super long

remove script from process title

---

gode/exec.go
gode/exec_test.go
gode/vars.go
plugins.go

Revert "remove script from process title"

---

gode/exec.go
gode/exec_test.go
gode/vars.go
plugins.go

Revert "Revert "remove script from process title""

---

gode/README.md
gode/exec.go
gode/packages.go
gode/packages_test.go
io.go
plugins.go
update.go

clean up the retry logic around builtin npm failures and keep it from repeating endlessly

fix builtin package install retry logic

---

cli.go
command.go

improve no app found error

---

cli.go
command.go

improve unexpected arg help

---

cli.go
command.go

improve unexpected flag help

---

git.go
io.go

better multiple remote error message

---

Rakefile

This should hopefully fix heroku/heroku#1886 by removing a dependency on getaddrinfo (https://github.com/golang/go/issues/6336)

Add netgo tag to build flags

---

Rakefile

Remove netgo flag to try and fix DNS errors

---

command.go

change error text highlight to red

---

gode/packages.go
gode/packages_test.go
plugins.go

npm used to be idempotent, it isn't anymore
Fixes #204

skip removing plugins that are not already installed

---

gode/constants.go
gode/exec.go
gode/packages.go
gode/setup.go
gode/setup_test.go
gode/target.go
gode/vars.go
plugins.go
set-node-version
update.go

remove code allowing use of old node versions

---

update.go

ensure node is setup

---

request.go

Add SSL_CERT_DIR & SSL_CERT_FILE to trusted certs

---

npm.go

Add NPM_CONFIG_CAFILE=$SSL_CERT_FILE to npm cmd

---

package.json

Bringing https://github.com/heroku/heroku-orgs/pull/48
cc @ransombriggs

Bump up heroku-orgs to 1.1.3

---

package.json

Bringing https://github.com/heroku/heroku-orgs/pull/49 in.
cc @ransombriggs

Upgrade heroku-orgs

---

package.json

This picks up the new `spaces:wait` command
@dpiddy @amerine @tcrayford @archaelus

Upgrade to heroku-spaces@2.3.0

---

io.go

disable color in dumb terminals

---

plugins.go

Fixes https://github.com/heroku/toolbelt/issues/164

gracefully handle quitting after stdout closes

---

package.json

More info:  https://github.com/heroku/heroku-orgs/pull/59

Updates heroku-orgs

---

bin/lint
plugins.go

To support the migration of https://github.com/heroku/heroku-cli-deploy

Added heroku-cli-deploy to list of plugins

---

package.json

Bump to 2.3.3 to include https://github.com/heroku/heroku-spaces/pull/27
/cc @heroku/dogwood @dickeyxxx

Bump `heroku-spaces`

---

package.json

Pick up: https://github.com/heroku/heroku-spaces/pull/28
cc: @ricardochimal, @jingweno, @dickeyxxx

 Bump to heroku-spaces@2.3.4

---

package.json

@dickeyxxx Could you review?  Just merging in modules to get fixes all at once so that ACDX testing / release is simplified.
* heroku-run for spaces run fix
* heroku-cli-addons for confirm fix
* heroku-certs for null pointer fix

Update package.json with fixes

---

update.go

tested using the dev branch and it solves the issue on windows
https://rollbar.com/heroku-cli/cli/items/2559/

fix updates on windows

---

plugins.go

warn on plugin refresh errors

---

package.json

Includes a new command, heroku pipelines:setup

Update to the latest heroku pipelines version

---

Makefile

Use 32 bit git installer when 386

---

analytics.go
update.go

@dickeyxxx could you review?  this fixes the certificate error that the proxy user gets when trying to update

Use apiHTTPClient in analytics / update

---

package.json

/cc @heroku/dogwood @dickeyxxx  @ransombriggs

Bump `heroku-spaces` to 2.7.1

---

auth.go
circle.yml
plugins.go

@djcp could you review and test this installer on windows?  https://cli-assets.heroku.com/branches/dev/heroku-windows-amd64.exe

Build makensis from 16.10 source debs

---

package.json

Bump `heroku-spaces` to 2.7.3

---

package.json

We just pushed an update to the pipelines plugin.

Update heroku-pipelines to 1.4.0

---

plugins.go

Add plugins --json

---

.gitignore
README.md

added notes for required steps specific to the cli-engine dependency
also added node_modules to the .gitignore file

Boilerplate details

---

package.json

This includes https://github.com/heroku/heroku-pg/pull/106 and https://github.com/heroku/heroku-pg/pull/103

Update heroku-pg to 2.0.25

---

circle.yml

disable beta channel pushes

---

package.json

To support [Heroku Exec](https://devcenter.heroku.com/articles/heroku-exec).

Added heroku-ps-exec to core plugins

---

package.json

This will improve debug and error logging for the `ps:exec` command.

Upgrade heroku-ps-exec

---

package.json

The time is about to come to see Heroku CI as a GA product.
https://github.com/heroku/heroku-ci/blob/master/package.json
We should make it part of the core CLI.
cc @heroku/devex

Include heroku-ci as default plugin

---

package.json

See https://github.com/heroku/heroku-ci/pull/35

Fix bug in heroku ci:debug

---

Makefile

Fix AWS_PATH when not manually set

---

RELEASE.md

Making explicit that you should push changes

---

package.json

This includes a workaround for https://github.com/heroku/cli/issues/479

Update pipelines to the latest version

---

package.json

This ships the fix in https://github.com/heroku/heroku-ci/pull/42

Bump herkou-ci to 1.8.0

---

circle.yml

Only release stable when on master

---

resources/deb/install-ubuntu.sh

check for apt-transport-ssh

---

package.json
yarn.lock

For https://github.com/heroku/heroku-pg/pull/138

Bump heroku-pg to 2.2.3

---

snap/snapcraft.yaml

also need to remove the plugs, since they're for strict or dev mode

Snap classic confinement

---

package.json
yarn.lock

See changelog https://github.com/heroku/heroku-ci/blob/master/CHANGELOG.md#192---2017-07-21.

Update heroku-ci to v.1.9.2

---

resources/exe/heroku.cmd

Update heroku.cmd to check LOCALAPPDATA

---

package.json
yarn.lock

For some pg:credentials cleanup

Bump heroku-pg to 2.3.0

---

resources/exe/heroku.cmd
resources/exe/heroku.nsi
scripts/release-windows

@dickeyxxx could you review?  I did not want to pollute env, so I removed `CLI_LOCAL_BIN` and changed `cli` to `client` to match how the cli is installed in `LOCALAPPDATA`

Remove env var and move client to cli

---

.circleci/config.yml
resources/exe/heroku.nsi
scripts/release-windows

@dickeyxxx could you review?  While working on signing the uninstaller I noticed that we do not remove ourselves from add / remove programs and that we are listed with an "Unknown Publisher" so I fixed that as well.

Sign & remove from add / remove & fix publisher

---

.circleci/config.yml
scripts/release-windows

@dickeyxxx could you review?  I also filtered down the installer build to just tags

Upload windows installer to s3

---

scripts/release-wrapper

Only release stable when CIRCLE_TAG is set

---

.circleci/config.yml
scripts/lint

need to update heroku-ps-exec before this will pass

added lint script

---

package.json
yarn.lock

Add heroku-webhooks to core dependencies

---

package.json
yarn.lock

Resolves https://status.heroku.com/incidents/1276

Upgrade heroku-ps-exec to 2.2.0

---

package.json

Bring this one in https://github.com/heroku/heroku-pipelines/blob/master/CHANGELOG.md#220-2017-09-06.

Upgrade heroku-pipelines

---

package.json

Adds the new `heroku pipelines:transfer` command

Update heroku-pipelines to 2.4.0

---

package.json
yarn.lock

See https://github.com/heroku/heroku-redis-jsplugin/pull/41

Update heroku-redis for maintenance endpoint change

---

package.json

This brings in this change https://github.com/heroku/heroku-pipelines/pull/78

Bump heroku-pipelines

---

package.json
yarn.lock

@heroku/cli could you review / merge / release ?

yarn upgrade heroku-webhooks

---

package.json
src/analytics.test.js
yarn.lock

nock became more strict with bodies and now requires all bodies to be set

updated nock

---

package.json
yarn.lock

Includes upgrade to heroku-cli-util 7.0.0

Upgrade heroku-ps-exec to 2.3.0

---

package.json

Bump heroku-spaces to 2.11.0.
/cc @heroku/dogwood

Bump heroku-spaces to 2.11.0

---

package.json
yarn.lock

I think this is the right way to bump this, but I could use some guidance.

heroku-space v2.12.0

---

package.json
yarn.lock

Also pulls in heroku-exec-util 0.7.2

Upgrade heroku-ps-exec to 2.3.4

---

README.md

Fixed the URLs for the shields.io badge of npm package.

Update package name in npm badge

---

package.json
yarn.lock

Update `heroku-webhooks` to get https://github.com/heroku/heroku-webhooks/pull/10

Bring heroku-webhooks up to 1.2.0

---

snap/snapcraft.yaml

this makes it run the update command whenever the snap is refreshed

add configure step to snap

---

package.json
yarn.lock

The daily upgrade we have these days 😄

Container registry v4.4.17

---

packages/spaces/commands/vpn/destroy.js
packages/spaces/test/commands/vpn/destroy.js

Just making some tweaks for consistency and fixes based on new info I got around how CLI works.

spaces: tweaks to vpn:destroy

---

packages/spaces/commands/peering/info.js
packages/spaces/lib/peering.js
packages/spaces/test/commands/peering/info.js

`Dyno CIDRs` --> `Space CIDRs`
Follow up to https://github.com/heroku/api/pull/9680
Issue: https://github.com/heroku/dogwood/issues/1961

spaces: rename dyno cidrs to space cidrs

---

packages/spaces/index.js

not sure how the tests were passing before without this removed

fix(spaces): remove vpn:create reference

---

packages/apps-v5/src/commands/apps/favorites/add.js
packages/apps-v5/src/commands/apps/favorites/index.js
packages/apps-v5/src/commands/apps/favorites/remove.js
packages/apps-v5/src/commands/dashboard.js
packages/apps-v5/test/commands/apps/favorites/add.js
packages/apps-v5/test/commands/apps/favorites/index.js
packages/apps-v5/test/commands/apps/favorites/remove.js
packages/apps-v5/test/commands/dashboard.js

This changes `apps:favorites` to talk to the new service that we're migrating to for favorites.

Update host for app favorites

---

packages/cli/package.json
yarn.lock

This will fix https://github.com/heroku/heroku-ps-exec/issues/13
I'm not sure if all of these `yarn.lock` upgrades are supposed to be in there. Please review that.

Upgrade heroku-ps-exec to 2.3.5

---

packages/cli/package.json

if we want to do this we'll have to get everyone on the private npm

rm custom npm registry

---

packages/certs/test/commands/hello.test.ts
packages/ci/src/commands/ci/index.ts
packages/ci/src/utils/test-run.ts
packages/ci/test/commands/ci/index.test.ts

```shell
$ heroku ci --json -p my-pipeline
```

feat(ci): allow json format in ci index command

---

packages/cli/src/hooks/init/version.ts
packages/cli/test/hooks/version.test.ts

fix(cli): whitelist version env var warnings

---

packages/buildpacks/src/commands/buildpacks/clear.ts
packages/buildpacks/src/commands/buildpacks/index.ts

fix(buildpacks): support remote flag

---

packages/webhooks-v5/commands/webhooks/add.js
packages/webhooks-v5/commands/webhooks/deliveries/index.js
packages/webhooks-v5/commands/webhooks/deliveries/info.js
packages/webhooks-v5/commands/webhooks/events/index.js
packages/webhooks-v5/commands/webhooks/events/info.js
packages/webhooks-v5/commands/webhooks/index.js
packages/webhooks-v5/commands/webhooks/info.js
packages/webhooks-v5/commands/webhooks/remove.js
packages/webhooks-v5/commands/webhooks/update.js

fix(webhooks-v5): add remote flag

---

packages/ci/src/commands/ci/index.ts
packages/ci/src/commands/ci/info.ts
packages/ci/src/commands/ci/last.ts
packages/ci/src/commands/ci/rerun.ts
packages/ci/src/commands/ci/run.ts

fix(ci): remove unused app flag

---

packages/ps/src/commands/ps/autoscale/disable.ts
packages/ps/src/commands/ps/autoscale/enable.ts

fix(ps): add remote flag

---

packages/pipelines-v5/commands/review_apps/disable.js
packages/pipelines-v5/commands/review_apps/enable.js

fix(pipelines-v5): add remote flag

---

packages/autocomplete/src/completions.ts

fix(autocomplete): use lowercase dyno-sizes for completion

---

packages/auth/test/commands/2fa/index.test.ts

fix(auth): test typo

---

packages/pipelines-v5/commands/pipelines/promote.js
packages/pipelines-v5/test/commands/pipelines/promote.js

fix(pipelines-v5): handle 404 when pipeline does not yet exist

---

packages/pg-v5/lib/util.js

see https://heroku.support/680459

fix(pg): connection pooling must be last for bastion support

---

packages/cli/package.json

fix: blacklist ps-wait as it is in core now

---

packages/pg-v5/commands/psql.js

fix(pg-v5): update missing credential error

---

packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/index.js
packages/orgs-v5/commands/members/add.js
packages/orgs-v5/commands/members/index.js
packages/orgs-v5/commands/members/remove.js
packages/orgs-v5/commands/members/set.js
packages/orgs-v5/commands/orgs/open.js
packages/pipelines-v5/commands/pipelines/connect.js
packages/pipelines-v5/commands/pipelines/create.js
packages/pipelines-v5/commands/pipelines/setup.js
packages/pipelines-v5/commands/review_apps/disable.js
packages/pipelines-v5/commands/review_apps/enable.js
packages/spaces/commands/create.js
packages/spaces/commands/index.js

This reverts commit f6041dbaaf62724ae0a5ee37d05a0f4037cae7f4.

fix: revert "No more wantsOrg" commit

---

packages/cli/src/analytics.ts
packages/cli/test/analytics.test.ts

A little bit of oversight from the last PR (#1188) and a whole lot of testing.

fix(cli): Add cli name to analytics properties

---

packages/cli/src/analytics.ts
packages/cli/test/analytics.test.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006SAGYIA4/view
Do not display analytics errors to users

fix(cli): Do not display backboard errors

---

packages/container-registry-v5/commands/release.js
packages/container-registry-v5/test/commands/release.js

feat(container-registry-v5): error code on exit if container:release failed

---

package.json
packages/local/src/commands/local/index.ts

fix(local): fix foreman-procfile path

---

packages/pipelines/package.json
packages/pipelines/src/commands/reviewapps/enable.ts
yarn.lock

oclif conversion edits

---

packages/spaces/commands/transfer.js
packages/spaces/index.js
packages/spaces/test/commands/transfer.js

feat(spaces): add spaces:transfer command

---

packages/certs-v5/package.json

chore(certs-v5): bump lodash to ^4.17.13

---

packages/pipelines/src/api.ts
packages/pipelines/src/commands/pipelines/info.ts
packages/pipelines/src/ownership.ts
packages/pipelines/test/commands/pipelines/info.test.ts
packages/pipelines/test/commands/unwrap.ts

Converts `pipelines:info` to oclif

feat(pipelines): convert info command

---

packages/pipelines/src/api.ts
packages/pipelines/src/commands/pipelines/destroy.ts
packages/pipelines/test/commands/pipelines/destroy.test.ts

Converting pipelines:destroy command with new base

feat(pipelines): add pipelines:destroy cmd - NEW PR

---

packages/ps/src/commands/ps/autoscale/enable.ts
packages/ps/test/commands/enable.test.ts

fix(ps): Permit autoscaling of performance and private tier dynos

---

packages/pg-v5/lib/psql.js
packages/pg-v5/test/lib/psql.js

fix(pg-v5): exec psql with set sslmode=require

---

packages/pipelines/src/commands/pipelines/open.ts
packages/pipelines/src/commands/pipelines/update.ts

Checking all commands within pipelines for one more find combing.

last sweep of pipelines' commands

---

packages/pipelines/src/commands/reviewapps/enable.ts
packages/pipelines/test/commands/enable.test.ts

Revert "feat(pipelines): add RA 2.0 enable command"

---

packages/pipelines/src/commands/reviewapps/disable.ts
packages/pipelines/test/commands/disable.test.ts

Revert "feat(pipelines): add RA 2.0 disable command"

---

packages/cli/package.json

fix(cli): uninstall old autocomplete plugin

---

docs/ci.md
docs/pipelines.md

fix(cli): update docs

---

packages/cli/package.json
yarn.lock

`yarn add @heroku-cli/plugin-ps-exec@2.3.7`

chore(cli): upgrade ps-exec plugin to 2.3.7

---

.github/CODEOWNERS

Consolidating GitHub teams to only one: https://github.com/orgs/heroku/teams/front-end.

chore(cli) Update CODEOWNERS

---

packages/pipelines/src/commands/reviewapps/enable.ts
packages/pipelines/test/commands/enable.test.ts

**DO NOT MERGE UNTIL REVIEW APPS 2.0 PUBLIC BETA RELEASE**
Reverts heroku/cli#1336

feat(pipelines): add review apps 2 beta to pipelines:enable

---

packages/pipelines/src/commands/reviewapps/disable.ts
packages/pipelines/test/commands/disable.test.ts

**DO NOT MERGE UNTIL REVIEW APPS 2.0 PUBLIC BETA RELEASE**
Reverts heroku/cli#1337

feat(pipelines): add review apps 2 beta to pipelines:disable

---

packages/cli/package.json

This will uninstall user installed heroku-redis plugins as it is now in core.

fix(cli): remove heroku-redis user installs

---

packages/cli/package.json
yarn.lock

`yarn add @heroku-cli/plugin-ps-exec@2.3.8`

chore(cli): upgrade ps-exec plugin to 2.3.8

---

scripts/release/dev_center_docs

chore: exclude github links in devcenter release

---

packages/pipelines/src/ownership.ts

Reopening: https://github.com/heroku/cli/pull/1370

fix(pipelines): return type error

---

.circleci/config.yml
packages/buildpacks/test/commands/buildpacks/add.test.ts
packages/ci/src/utils/source.ts

chore: bump node versions in CI

---

packages/cli/package.json

chore(cli): bump node version for oclif.update.node.version to node 12

---

packages/ci-v5/lib/api.js
packages/ci-v5/lib/disambiguate.js
packages/ci-v5/lib/key-by.js
packages/ci-v5/lib/utils.js
packages/ci-v5/package.json
yarn.lock

also bump heroku-client to remove node 12 deprecation warning

chore: bump @heroku-cli/command in packages

---

packages/apps/src/lib/wait-for-domain.ts
packages/apps/test/commands/domains/wait.test.ts

wait had the wrong response type

fix(apps): domains:wait status fetch

---

packages/pipelines/src/commands/reviewapps/disable.ts
packages/pipelines/src/commands/reviewapps/enable.ts
packages/pipelines/test/commands/disable.test.ts
packages/pipelines/test/commands/enable.test.ts

Remove RA 1.0 path when RA 2.0 goes GA

feat(pipelines): remove RA 1.0 code when RA 2.0 goes GA

---

packages/status/.eslintrc
packages/status/package.json
packages/status/src/commands/status.ts
packages/status/src/util.ts
packages/status/test/status.test.ts
packages/status/tslint.json
yarn.lock

Upgrade `status` package from `tslint` to `eslint`

chore(status): upgrade to eslint

---

packages/ps/.eslintrc
packages/ps/package.json
packages/ps/src/commands/ps/autoscale/disable.ts
packages/ps/src/commands/ps/autoscale/enable.ts
packages/ps/src/commands/ps/wait.ts
packages/ps/src/commands/regions.ts
packages/ps/test/commands/disable.test.ts
packages/ps/test/commands/enable.test.ts
packages/ps/test/commands/regions.test.ts
packages/ps/test/commands/wait.test.ts
packages/ps/tslint.json
yarn.lock

Upgrade `ps` package from `tslint` to `eslint`

chore(ps): Upgrade spaces to eslint

---

packages/cli/.eslintrc
packages/cli/package.json
packages/cli/src/analytics.ts
packages/cli/src/deps.ts
packages/cli/src/file.ts
packages/cli/src/global.d.ts
packages/cli/src/hooks/init/version.ts
packages/cli/src/hooks/update/b.ts
packages/cli/src/hooks/update/brew.ts
packages/cli/src/hooks/update/plugin-migrate.ts
packages/cli/src/hooks/update/tidy.ts
packages/cli/src/user-config.ts
packages/cli/test/acceptance/plugin.test.ts
packages/cli/test/acceptance/smoke.test.ts
packages/cli/test/analytics.test.ts
packages/cli/tslint.json

Upgrade `cli` package from `tslint` to `eslint`

chore(cli): upgrade cli to eslint

---

packages/ci/.eslintrc
packages/ci/package.json
packages/ci/src/commands/ci/index.ts
packages/ci/src/commands/ci/info.ts
packages/ci/src/commands/ci/last.ts
packages/ci/src/commands/ci/rerun.ts
packages/ci/src/commands/ci/run.ts
packages/ci/src/interfaces/kolkrabbi.ts
packages/ci/src/utils/git.ts
packages/ci/src/utils/pipelines.ts
packages/ci/src/utils/source.ts
packages/ci/src/utils/test-run.ts
packages/ci/test/commands/ci/index.test.ts
packages/ci/test/commands/ci/info.test.ts
packages/ci/test/commands/ci/last.test.ts
packages/ci/test/commands/ci/rerun.test.ts
packages/ci/test/commands/ci/run.test.ts
packages/ci/tslint.json
yarn.lock

Upgrade `ci` package from `tslint` to `eslint`

chore(ci): upgrade ci to eslint

---

packages/apps/src/commands/domains/add.ts
packages/apps/src/commands/domains/clear.ts
packages/apps/src/commands/domains/index.ts
packages/apps/src/commands/domains/info.ts
packages/apps/src/commands/domains/remove.ts
packages/apps/src/commands/domains/update.ts
packages/apps/src/commands/domains/wait.ts
packages/apps/test/commands/domains/update.test.ts

Adds a domains:update command to allow for using different certs.
GUS item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007rFIsIAM/view

feat(apps): add domains:update command

---

packages/apps/README.md

This reverts commit d89f16cf98ebfb236d882859b3eb1f6adaa209da.
Reverts entire  #1407 PR
In ref to:
https://heroku.slack.com/archives/C1RU5S0G2/p1579576581000800

fix: clean up whitespace

---

packages/apps/package.json
packages/apps/src/commands/domains/add.ts
packages/apps/test/commands/domains/add.test.ts
yarn.lock

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007rFIYIA2/view

fix: Revert #1412

---

.circleci/config.yml
package.json
scripts/release/change_management
yarn.lock

Add release hook to update tps/change management log

chore(cli): add release change management hook

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/lib/match_domains.js
packages/certs-v5/test/commands/certs/add.js
packages/certs-v5/test/lib/match_domains.js

Adds the new domain configuration workflow when adding a certificate, allowing all associated domains to to use the new certificate.
GUS Work item: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007skh9IAA/view

feat(cert-v5): New certification configuration workflow for multi cert UI

---

.circleci/config.yml

Some of our CI jobs needed cleaned up

fix: node-10 & dev center & change management ci jobs

---

scripts/snap

chore(ci): Rename SNAPCRAFT_MACAROON to SNAPCRAFT_LOGIN_FILE

---

.circleci/config.yml
Dockerfile.devcenter

chore: use heroku docker images

---

package.json
packages/cli/package.json

This version/build is, in the parlance of Apple, `notarized`. https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

fix(security): update to a notarized version of node

---

packages/cli/README.md

Release steps workaround for compliance

docs: update release steps in README

---

.circleci/config.yml

remove duplicate brew release now that it's 👍 as expected

chore: rm test brew release

---

packages/cli/README.md

readme: link release steps doc

---

.github/PULL_REQUEST_TEMPLATE.md

adding a note to re-run tests on windows CI issues

docs: add windows CI note to PR template

---

packages/pg-v5/commands/pull.js
packages/pg-v5/test/commands/pull.js

chore(pg-v5): switch to the Node.js `process` global variable

---

CHANGELOG.md
packages/autocomplete/src/completions.ts
packages/autocomplete/test/completions.test.ts
packages/cli/CHANGELOG.md
packages/cli/src/hooks/init/version.ts
packages/spaces/commands/destroy.js

This pull request removes terms that are not inclusive.

fix: use inclusive terms

---

.circleci/config.yml

chore: use node CI images

---

.github/ISSUE_TEMPLATE.md

chore: update ISSUE_TEMPLATE.md

---

packages/spaces/commands/vpn/update.js
packages/spaces/lib/vpn-connections.js
packages/spaces/test/commands/vpn/update.js

We will soon have a way to update the VPN CIDRs and this is the command for it.

feat(spaces/vpn): Add an update VPN command

---

packages/pg-v5/commands/promote.js
packages/pg-v5/test/commands/promote.js

This PR attaches `DATABASE_CONNECTION_POOL` to the new leader if the old leader has a connection pooling attachment under the name `DATABASE_CONNECTION_POOL`. 
GUS card: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008J5MXIA0/view

fix(pg-v5) pgbouncer promote

---

packages/spaces/index.js

fix(spaces): Actually require the vpn update

---

CHANGELOG.md
docs/config.md
docs/spaces.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/config/CHANGELOG.md
packages/config/README.md
packages/config/package.json
packages/spaces/CHANGELOG.md
packages/spaces/README.md
packages/spaces/package.json

release v7.47.7

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.47.11

---

packages/pipelines/src/commands/pipelines/create.ts

This pull request is longer than the fix.
Credit: @ransombriggs https://heroku.slack.com/archives/C1RU5S0G2/p1611604251001100

Errant stray apostrophe

---

CHANGELOG.md
docs/auth.md
docs/labs.md
docs/pipelines.md
docs/reviewapps.md
lerna.json
packages/auth/CHANGELOG.md
packages/auth/README.md
packages/auth/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pipelines/CHANGELOG.md
packages/pipelines/README.md
packages/pipelines/package.json

release v7.47.12

---

CHANGELOG.md
docs/pg.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.48.0

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.50.0

---

packages/cli/package.json

GUS: [W-8984115][1]
[1]: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008xKCsIAM/view

feat: upgrade node to 12.21.0

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/redis-v5/CHANGELOG.md
packages/redis-v5/package.json

release v7.51.0

---

packages/apps-v5/src/commands/apps/errors.js

brings in https://github.com/heroku/cli/pull/1755; opening a new PR so CI will run

chore(apps-v5): remove unused variable

---

packages/auth/src/commands/auth/2fa/disable.ts

* Deprecation warning
* This has already been deprecated for anyone in the MFA beta, which
went to GA on April 5, 2021.
* Next step will be to remove entirely
* https://salesforce.quip.com/JYsuAbKPJa0W#UaWABAZB3C9

feat(auth): Update auth:2fa:disable

---

CHANGELOG.md
docs/apps.md
docs/auth.md
docs/certs.md
docs/labs.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/auth/CHANGELOG.md
packages/auth/README.md
packages/auth/package.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.52.0

---

packages/certs-v5/commands/certs/add.js
packages/certs-v5/test/commands/certs/add.js

Reverts heroku/cli#1781
Please see me in slack for more context. We will restore after the next release.

Revert "Remove old --domains flag from certs:add"

---

.circleci/config.yml

https://heroku.slack.com/archives/CANLMQU3F/p1620057873144500?thread_ts=1619725397.133700&cid=CANLMQU3F

ci: restore homebrew / change management jobs

---

install-standalone.sh

Reverts #1809 which reverted #1705

fix(cli): builds for arm (aarch) machines (#1705)

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.54.1

---

CHANGELOG.md
docs/certs.md
lerna.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.55.0

---

CHANGELOG.md
docs/logs.md
docs/redis.md
docs/run.md
lerna.json
packages/ci-v5/CHANGELOG.md
packages/ci-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/redis-v5/CHANGELOG.md
packages/redis-v5/README.md
packages/redis-v5/package.json
packages/run-v5/CHANGELOG.md
packages/run-v5/README.md
packages/run-v5/package.json
packages/run/CHANGELOG.md
packages/run/README.md
packages/run/package.json

release v7.56.0

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.56.1

---

CHANGELOG.md
docs/certs.md
lerna.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.57.0

---

CHANGELOG.md
docs/pg.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.58.0

---

CHANGELOG.md
docs/redis.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/redis-v5/CHANGELOG.md
packages/redis-v5/package.json

release v7.59.0

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.59.2

---

CHANGELOG.md
docs/certs.md
docs/pg.md
lerna.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/container-registry-v5/CHANGELOG.md
packages/container-registry-v5/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.59.3

---

packages/cli/package.json

GUS ticket: [W-10758034](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000reqEzYAI/view) [cli] Update heroku-cli to node 14

feat(cli): upgrade to node 14.19.0

---

.circleci/config.yml
package.json
packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/buildpacks/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/git/package.json
packages/local/package.json
packages/oauth/package.json
packages/oauth/test/lib/clients.test.ts
packages/ps/package.json
packages/run/package.json
packages/status/package.json
packages/webhooks/package.json

Finish update to node 14

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
yarn.lock

release v7.60.2

---

docs/git.md
packages/apps-v5/src/commands/apps/create.js
packages/apps-v5/src/commands/apps/rename.js
packages/git/src/commands/git/clone.ts
packages/git/src/commands/git/remote.ts
packages/git/src/git.ts

feat(git, apps)remove SSH Git support
*remove the `--ssh-git` flag
GUS ticket: [W-11469758](https://gus.lightning.force.com/lightning/r/a07EE000011zvlUYAQ/view)
Closes #2017

feat(git): remove git ssh

---

.circleci/config.yml

test: rm EOL node v12 testing

---

packages/certs-v5/package.json
packages/cli/package.json
packages/pg-v5/package.json

chore(cli): remove githead

---

CHANGELOG.md
docs/certs.md
lerna.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.63.4

---

packages/cli/package.json
yarn.lock

bump @heroku-cli/plugin-ps-exec to 2.4.0

chore(cli): bump @heroku-cli/plugin-ps-exec

---

CHANGELOG.md
docs/certs.md
lerna.json
packages/certs-v5/CHANGELOG.md
packages/certs-v5/README.md
packages/certs-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.64.0

---

docs/ps.md
packages/apps-v5/README.md
packages/apps-v5/src/commands/ps/index.js
packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/commands/ps/index.js
packages/apps-v5/test/commands/ps/type.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000014pUnGYAU/view)

chore(ps-v5): update heroku ps plans

---

packages/pg-v5/commands/connection_pooling.js
packages/pg-v5/commands/credentials/create.js
packages/pg-v5/commands/credentials/destroy.js
packages/pg-v5/commands/credentials/repair_default.js
packages/pg-v5/commands/credentials/rotate.js
packages/pg-v5/commands/credentials/url.js
packages/pg-v5/commands/diagnose.js
packages/pg-v5/commands/maintenance/index.js
packages/pg-v5/commands/maintenance/run.js
packages/pg-v5/commands/maintenance/window.js
packages/pg-v5/commands/repoint.js
packages/pg-v5/commands/settings/index.js
packages/pg-v5/commands/upgrade.js
packages/pg-v5/lib/host.js
packages/pg-v5/lib/setter.js
packages/pg-v5/lib/util.js
packages/pg-v5/test/commands/credentials/create.js
packages/pg-v5/test/commands/credentials/destroy.js
packages/pg-v5/test/commands/credentials/repair_default.js
packages/pg-v5/test/commands/credentials/rotate.js
packages/pg-v5/test/commands/credentials/url.js
packages/pg-v5/test/commands/repoint.js
packages/pg-v5/test/commands/upgrade.js
packages/pg-v5/test/lib/host.js

[Gus](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000017ovGJYAY/view)

feat(pg-v5): Support pg mini plans

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.65.0

---

.circleci/config.yml
.github/workflows/ci.yml
packages/cli/README.md

[W-11927260](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000019Ap1fYAC/view)
This PR creates a dummy CI job for Changeling to watch as our passing compliance check. It also comments out the circleci flow.

chore: update ci

---

CHANGELOG.md
docs/ps.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.66.0

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.66.1

---

CHANGELOG.md
lerna.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json

release v7.66.2

---

scripts/release/deb

[W-12049376](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001CS9owYAD/view)
Fix the release key path to match [the path in the signing step](https://github.com/heroku/cli/blob/bd32cdcee3a7a214b6aea6f309aae1a8ac2ae65e/scripts/sign/deb#L17).

fix(ci): Fix release key path

---

.github/workflows/ci.yml

Re-make of PR #2139 so we can run CI. H/T to @jaredallard

fix(ci): set HEROKU_AUTHOR

---

packages/status/package.json
packages/status/src/commands/status.ts
packages/status/test/status.test.ts
packages/status/tsconfig.json
yarn.lock

Migrates status package to oclif/core. Includes one test fix.

refactor(status): migrate status package to oclif/core

---

packages/apps-v5/README.md
packages/apps-v5/src/error_info.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000014pbT0YAI/view)

chore(apps-v5): remove free dyno quota exhaustion error & update apps readme

---

packages/addons-v5/index.js
packages/addons-v5/test/commands/addons.--all.js
packages/addons-v5/test/commands/addons.--app.js
packages/addons-v5/test/commands/addons/docs.js
packages/addons-v5/test/commands/addons/info.js
packages/addons-v5/test/fixtures.js

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001D6Cy2YAF/view)

chore(addons-v5): update addons copy to reflect new plans

---

docs/ps.md
packages/apps-v5/src/commands/ps/index.js
packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/commands/ps/index.js
packages/apps-v5/test/commands/ps/type.js

Removes references to `free` and replaces `hobby` with `basic` for dynos.
[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Cvh2qYAB/view)

chore(ps): remove free and add basic for dynos

---

packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/commands/ps/type.js
packages/run/src/commands/console.ts
packages/run/src/commands/rake.ts
packages/run/src/commands/run/detached.ts
packages/run/src/commands/run/index.ts
packages/run/test/commands/console.test.ts
packages/run/test/commands/rake.test.ts
packages/run/test/commands/run.test.ts
packages/run/test/commands/run/detached.test.ts

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000014pcNNYAY/view)

chore(cli): update size flags for free

---

packages/certs-v5/package.json
packages/pg-v5/package.json
packages/redis-v5/package.json

closes #2103
closes #2108 
closes #2106 
GUS tickets:
- https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BM7ayYAD/view
- https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BLA6KYAX/view

refactor: migrate pg-v5 certs-v5 redis-v5 to oclif/core

---

packages/cli/README.md

Adds some details about setting up and running the project.

docs: update cli readme

---

packages/container-registry-v5/package.json

[Gus item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BLPEgYAP/view)
Closes #2100

refactor(container-registry-v5): migrate to oclif/core

---

packages/oauth-v5/package.json

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BLXU1YAP/view)
closes #2110

refactor(oauth-v5): migrate to oclif/core

---

CHANGELOG.md
docs/logs.md
docs/run.md
lerna.json
packages/addons-v5/CHANGELOG.md
packages/addons-v5/package.json
packages/apps-v5/CHANGELOG.md
packages/apps-v5/README.md
packages/apps-v5/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/run/CHANGELOG.md
packages/run/README.md
packages/run/package.json

release v7.67.0

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/run-v5/CHANGELOG.md
packages/run-v5/README.md
packages/run-v5/package.json
packages/run/CHANGELOG.md
packages/run/README.md
packages/run/package.json

release v7.67.1

---

packages/local/.eslintrc
packages/local/package.json
packages/local/src/commands/local/index.ts
packages/local/src/commands/local/run.ts
packages/local/src/commands/local/version.ts
packages/local/test/commands/local/index.test.ts
packages/local/test/commands/local/run.test.ts
packages/local/test/commands/local/version.test.ts
packages/local/tsconfig.json
yarn.lock

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001G7dkkYAB/view
Upgrade local package to core.

feat(local): upgrade local package to core

---

packages/config/bin/run
packages/config/package.json
packages/config/src/commands/config/edit.ts
packages/config/src/commands/config/get.ts
packages/config/src/commands/config/index.ts
packages/config/src/commands/config/unset.ts
packages/config/test/commands/config/edit.test.ts
packages/config/test/commands/config/index.test.ts
packages/config/test/test.ts
packages/config/tsconfig.json
yarn.lock

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001G8MXvYAN/view

chore(config): upgrade config package to core

---

packages/git/package.json
packages/git/src/commands/git/clone.ts
packages/git/src/commands/git/credentials.ts
packages/git/src/commands/git/remote.ts
packages/git/src/git.ts
packages/git/tsconfig.json
yarn.lock

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BLPEgYAP/view)

refactor(git): update the git package to use oclif/core

---

packages/buildpacks/package.json
packages/buildpacks/src/buildpacks.ts
packages/buildpacks/src/commands/buildpacks/add.ts
packages/buildpacks/src/commands/buildpacks/clear.ts
packages/buildpacks/src/commands/buildpacks/index.ts
packages/buildpacks/src/commands/buildpacks/info.ts
packages/buildpacks/src/commands/buildpacks/remove.ts
packages/buildpacks/src/commands/buildpacks/search.ts
packages/buildpacks/src/commands/buildpacks/set.ts
packages/buildpacks/src/commands/buildpacks/versions.ts
packages/buildpacks/test/commands/buildpacks/add.test.ts
packages/buildpacks/test/commands/buildpacks/clear.test.ts
packages/buildpacks/test/commands/buildpacks/index.test.ts
packages/buildpacks/test/commands/buildpacks/info.test.ts
packages/buildpacks/test/commands/buildpacks/remove.test.ts
packages/buildpacks/test/commands/buildpacks/search.test.ts
packages/buildpacks/test/commands/buildpacks/set.test.ts
packages/buildpacks/test/commands/buildpacks/versions.test.ts
yarn.lock

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001G8BeQYAV/view)

refactor(buildpacks): migrate to oclif/core

---

packages/spaces/package.json
yarn.lock

**GUS Ticket:** [W-11999447](https://gus.lightning.force.com/lightning/r/a07EE00001BM7ayYAD/view)

refactor(spaces): upgrade spaces to oclif/core

---

packages/ci/bin/run
packages/ci/package.json
packages/ci/src/commands/ci/index.ts
packages/ci/src/commands/ci/info.ts
packages/ci/src/commands/ci/last.ts
packages/ci/src/commands/ci/rerun.ts
packages/ci/src/commands/ci/run.ts
packages/ci/src/utils/source.ts
packages/ci/src/utils/test-run.ts
packages/ci/test/commands/ci/index.test.ts
packages/ci/test/commands/ci/info.test.ts
packages/ci/test/commands/ci/last.test.ts
packages/ci/test/commands/ci/rerun.test.ts
packages/ci/test/commands/ci/run.test.ts
packages/ci/tsconfig.json
yarn.lock

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BLA6KYAX/view

chore(ci): migrate to oclif core

---

packages/ps/src/commands/ps/wait.ts
packages/ps/src/commands/regions.ts
packages/ps/test/commands/enable.test.ts
packages/ps/test/commands/regions.test.ts
packages/status/package.json

Remainder of [W-12363686](https://gus.lightning.force.com/lightning/r/a07EE00001J8DrvYAF/view)

fix: finish ps upgrade. tests passing.

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/redis-v5/CHANGELOG.md
packages/redis-v5/package.json

release v7.67.2

---

packages/buildpacks/tsconfig.json
packages/pipelines/tsconfig.json

This work is necessary to run the scripts to release v8 (oclif core migration) of this repo.
[GUS epic](https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QEE000000OzFF2A0/view)

chore: add skipLibCheck to tsconfig for buildpacks and pipelines

---

.github/workflows/snyk.yml

chore: fix snyk workflow

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v7.68.2

---

.github/workflows/ci.yml
package.json
packages/apps/package.json
packages/auth/package.json
packages/autocomplete/package.json
packages/buildpacks/package.json
packages/certs/package.json
packages/ci-v5/package.json
packages/ci/package.json
packages/cli/package.json
packages/config/package.json
packages/git/package.json
packages/local/package.json
packages/oauth/package.json
packages/pipelines/package.json
packages/ps/package.json
packages/run/package.json
packages/status/package.json
packages/webhooks/package.json
yarn.lock

Change all package.json engines.node versions
remove unneeded @types/node dependencies

fix: add node 14 to unit tests in CI

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/redis-v5/CHANGELOG.md
packages/redis-v5/package.json

release v7.68.3

---

CHANGELOG.md
docs/local.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/local/CHANGELOG.md
packages/local/README.md
packages/local/package.json

release v7.69.0

---

.github/workflows/promote-release.yml

Prefix `oclif promote` with `yarn` so it runs in CI.

fix: publish in CI

---

.github/workflows/promote-release.yml

Add `--root` flag to `oclif promote`

fix: publish ci round 3

---

packages/cli/package.json
yarn.lock

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OEEkbYAH/view
update @oclif/plugin-plugins version to beta bug fix to allow installing Legacy plugins.

fix: allow installing Legacy plugins

---

packages/cli/package.json
yarn.lock

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OEEkbYAH/view
Version bump from beta to latest @oclif/plugin-plugins

fix: update to latest @oclif/plugin-plugins to allow Legacy plugin installs

---

CHANGELOG.md
docs/plugins.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/ps/CHANGELOG.md
packages/ps/README.md
packages/ps/package.json

release v8.0.3

---

packages/cli/package.json
yarn.lock

WSL portion of this ticket: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OEEkbYAH/view
[Support ticket: https://heroku.support/1236488](https://heroku.support/1232002)

fix: update plugin-update bump for WSL fix.

---

.github/workflows/pack-and-release.yml

Continuation of https://github.com/heroku/cli/pull/2288 & [GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001OgQdAYAV/view)

fix: use correct logic for running if inputs.commitSHA

---

.github/workflows/pack-and-release.yml
scripts/postrelease/install_scripts.js

use path.join for accurate path to install scripts.
better name for promote job

fix: ensure correct path to install scripts.

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json

release v8.1.1

---

.github/workflows/full-release-pipeline.yml
.github/workflows/promote-release.yml
.github/workflows/promote.yml
.github/workflows/publish-npm-gh.yml
.github/workflows/watch-for-prerelease.yml
.github/workflows/watch-for-release.yml
scripts/publish-npm-prerelease

Bug fix follow up for recent CD refactor.
Mostly working around GHA converting all boolean inputs to strings.
Fixes here led to successful beta release: https://github.com/heroku/cli/actions/runs/5135729493/jobs/9241972627

fix: GHA release pipeline bugs

---

.github/workflows/tag-create-github-release.yml
scripts/postrelease/change_management

import path in change_management. filter out current tag that was just created for generating change log

fix: change log generation and change_management

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/notifications.md
docs/pipelines.md
docs/ps.md
docs/psql.md
docs/regions.md
docs/releases.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/README.md
packages/cli/package.json

release v8.3.0

---

packages/cli/src/global_telemetry.ts

Updates path when pulling `version` out of package.json

fix(cli): fix path issue for package.json

---

packages/addons-v5/commands/addons/index.js
packages/addons-v5/commands/addons/info.js
packages/addons-v5/commands/addons/plans.js
packages/addons-v5/commands/addons/upgrade.js
packages/addons-v5/lib/create_addon.js
packages/addons-v5/lib/util.js
packages/addons-v5/test/unit/commands/addons.--all.unit.test.js
packages/addons-v5/test/unit/commands/addons.--app.unit.test.js
packages/addons-v5/test/unit/commands/addons/create.unit.test.js
packages/addons-v5/test/unit/commands/addons/info.unit.test.js
packages/addons-v5/test/unit/commands/addons/plans.unit.test.js
packages/addons-v5/test/unit/commands/addons/upgrade.unit.test.js
packages/addons-v5/test/unit/lib/util.unit.test.js
packages/apps-v5/src/commands/ps/type.js
packages/apps-v5/test/unit/commands/ps/type.unit.test.js
packages/spaces/commands/create.js
packages/spaces/test/unit/commands/create.unit.test.js

Revert "refactor: add per hour and max price per month to pricing displays"

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/pipelines.md
docs/ps.md
docs/regions.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/README.md
packages/cli/package.json

release v8.3.1

---

packages/cli/package.json

Should resolve a couple of descriptions that were not being generated correctly in our docs files and the packages/cli README.
[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001VoACPYA3/view)

chore(docs): add descriptions for pipelines and reviewapps commands

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/pipelines.md
docs/ps.md
docs/regions.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/README.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json
yarn.lock

release v8.4.1

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/pipelines.md
docs/ps.md
docs/regions.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/README.md
packages/cli/package.json
packages/pg-v5/CHANGELOG.md
packages/pg-v5/package.json
yarn.lock

release v8.4.2
Beta release tests passing: https://github.com/heroku/cli/actions/runs/6029599831/job/16360746979

release v8.4.2

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/pipelines.md
docs/ps.md
docs/regions.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/README.md
packages/cli/package.json

release v8.4.3
Same as 8.4.3-beta.0.

release v8.4.3

---

packages/cli/src/global_telemetry.ts

[GUS ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001aLzOjYAK/view)
Updates our Rollbar post token

chore: update rollbar token

---

packages/pg-v5/lib/host.js
packages/pg-v5/lib/util.js
packages/pg-v5/test/unit/lib/host.unit.test.js
packages/pg-v5/test/unit/lib/util.unit.test.js

Ensure that essential addons are being directed to the correct host.

feature(pg-v5) Updates pg commands to route to essential plans to correct host

---

.github/workflows/rollback.yml
scripts/rollback/homebrew.js

[GUS Ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001YfsJ3YAJ/view)
This should allow us to easily rollback both releases and pre-releases. Since it is a manual-only workflow, I can't test it until we merge to main. Any suggestions for how to do so before merging would be most welcome.

chore: automate rollback procedure

---

.github/workflows/rollback.yml

fix: update if statements in rollback workflow

---

CHANGELOG.md
docs/auth.md
docs/authorizations.md
docs/autocomplete.md
docs/buildpacks.md
docs/ci.md
docs/clients.md
docs/config.md
docs/domains.md
docs/git.md
docs/labs.md
docs/local.md
docs/logs.md
docs/pipelines.md
docs/ps.md
docs/regions.md
docs/reviewapps.md
docs/run.md
docs/sessions.md
docs/status.md
docs/webhooks.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/spaces/CHANGELOG.md
packages/spaces/package.json
yarn.lock

release v8.7.1

---

CONTRIBUTING.md
SECURITY.md

Added CONTRIBUTORS and SECURITY files. These are items in the GitHub Maintenance tasks for the Baseline Processes Optimization epic.
[W-12338106](https://gus.lightning.force.com/lightning/r/a07EE00001IodPzYAJ/view)
https://salesforce.quip.com/Rf58AQg13k6u

chore(cli): repo maintenance

---

.github/workflows/promote-release.yml
.github/workflows/rollback.yml
scripts/postrelease/change_management
scripts/release/homebrew.js
scripts/rollback/homebrew.js

Issues here: https://github.com/heroku/cli/actions/runs/6776026744
Account for TPS api change.
Account for https://github.com/heroku/homebrew-brew changing from master to main.

fix: release bugs due to external changes

---

.github/workflows/promote.yml
scripts/release/validate-prerelease

Small tweaks for allowing dev channel releases.

fix: dev channel releases

---

packages/cli/package.json

[work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001g3w3kYAA/view)
This PR updates the node version distributed with the cli to `v16.20.2`

Updates to node v16.20.2 to resolve a high priority vulnerability

---

packages/orgs-v5/commands/members/add.js
packages/orgs-v5/commands/members/set.js
packages/orgs-v5/lib/utils.js
packages/orgs-v5/test/unit/commands/members/add.unit.test.js
packages/orgs-v5/test/unit/commands/members/set.unit.test.js

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001dS5EUYA0/view)
This logic was overlooked when we made the initial change to how we charge for teams.

fix: remove unneeded pricing language for teams

---

packages/cli/package.json

Quality of life improvement -- add local test option so we can use .only

chore(cli): Add local test option

---

packages/container-registry-v5/package.json
yarn.lock

resolves https://github.com/heroku/cli/pull/2601

chore(deps) Update depcheck to 1.4.7

---

.github/workflows/ci.yml
.github/workflows/empty-stampy-buckets.yml
.github/workflows/promote-release.yml
.github/workflows/publish-to-fig-autocomplete.yml
packages/certs-v5/package.json
packages/certs-v5/test/mocha.opts
packages/cli/package.json
packages/cli/test/acceptance/commands-output.ts
packages/cli/test/acceptance/smoke.acceptance.test.ts
packages/cli/test/mocha.opts
packages/container-registry-v5/package.json
packages/container-registry-v5/test/mocha.opts
packages/oauth-v5/package.json
packages/oauth-v5/test/mocha.opts
packages/orgs-v5/package.json
packages/orgs-v5/test/mocha.opts
packages/pg-v5/commands/upgrade.js
packages/pg-v5/package.json
packages/pg-v5/test/mocha.opts
packages/pg-v5/test/unit/commands/upgrade.unit.test.js
packages/redis-v5/package.json
packages/redis-v5/test/mocha.opts
packages/run-v5/package.json
packages/run-v5/test/mocha.opts
packages/spaces/package.json
packages/spaces/test/mocha.opts
scripts/create-release-pr
scripts/stampy/empty-stampy-buckets.js
yarn.lock

This pulls in all the latest changes from `main` to `prerelease/9.0.0-alpha`

Merge updates from main

---

scripts/postrelease/test_release

Due to an [error in our test-installed-cli workflow](https://github.com/heroku/cli/actions/runs/8270465686/job/22686290701), this PR updates some app and pipeline names in the commands to satisfy the test.

fix(workflow): update test_release commands

---

packages/cli/src/global_telemetry.ts
packages/cli/src/hooks/postrun/performance_analytics.ts
packages/cli/src/hooks/prerun/analytics.ts
packages/cli/test/acceptance/smoke.acceptance.test.ts
packages/cli/test/helpers/init.js

cherry-pick from #2716 (improve unit test performance)

chore(W-15263489): improve unit test performance (#2716)

---

packages/cli/test/unit/commands/dashboard.unit.test.ts

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001mmFfiYAE/view
The dashboard tests fail 100% of the time when run locally. TBH, I don't know why it passes at all in CI. There are a couple issues I can verify locally and are fixed in this:
1) A timing issue with `Date.now()` which is fixed via sinon's `useFakeTimers`
2) There is extra content in `stdout.output`, which I think is some nice ascii art. The failures are resolved by switching to `includes` instead of `equals` to search for the expected text

chore(dashboard): Fix timing and other issues with dashboard tests

---

packages/addons-v5/package.json
packages/apps-v5/package.json
packages/certs-v5/package.json
packages/ci-v5/package.json
packages/cli/package.json
packages/container-registry-v5/package.json
packages/oauth-v5/package.json
packages/orgs-v5/package.json
packages/pg-v5/package.json
yarn.lock

bringing https://github.com/heroku/cli/pull/2715 to `main`

Update mocha and timeout

---

.github/workflows/ctc.yml

Need to add this environment to the job so that it can get the `ChangeManagement` secrets from GH actions

chore(cli) add ChangeManagement environment to CTC check

---

.github/workflows/ctc.yml

missed in the copied code that they were using vars instead of secrets. This should work this time 🤞

rename vars to secrets in ctc workflow

---

packages/cli/README.md
packages/cli/package.json

https://github.com/heroku/cli/issues/1998
This updates the description of the `auth` topic to more generally describe managing authentication for your Heroku account
1) Pull down branch
2) `yarn build`
3) `./bin/run help auth`
4) See updated description

Update description of auth topic

---

.github/workflows/ci.yml

[Work Item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001tdelwYAA/view)
This PR enables the ability to manually trigger the CI workflow for Tests on any branch pushed to Heroku CLI repo.

chore(ci): update ci workflow

---

packages/cli/src/commands/addons/create.ts
packages/cli/test/acceptance/commands-output.ts

[Work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001vp8xpYAA/view)
This PR just adds some documentation on how to add config items for the `addons:create` command, since the v9 version is different from the v8 version and this isn't well-documented.

docs: add documentation on how to add config items for addons:create

---

.github/workflows/ci.yml
packages/cli/package.json
packages/cli/src/commands/apps/info.ts
yarn.lock

Merge main into prerelease branch.

chore: merge main into prerelease branch

---

packages/cli/src/lib/pg/fetcher.ts

Verified fix locally using the app and addon that were triggering the issue.

fix: second attempt at fixing the error handling in matchesHelper

---

packages/cli/src/lib/pg/fetcher.ts

I noticed some noisy debugging in the latest version of the CLI for some `pg` commands. I think this line is the source.
```
$ heroku --version
heroku/9.0.0 darwin-arm64 node-v16.20.2
```
```
jwadsworth@jwadswo-ltm7hqp: ~/Code/heroku/dns feat-herokudev-jwadsworth
$ heroku plugins
@heroku/event-log 0.5.0
@heroku/heroku-dux-admin 1.12.0
@heroku/splunk 1.3.6
@heroku/sudo 5.3.2
addons-admin 2.2.1
api 2.2.0
data 1.3.1
data-maintenance 0.3.0
data-privatelink 1.3.1
heroku-2fa 1.0.5
heroku-data-admin 1.0.0 (link) /Users/jwadsworth/Code/heroku/heroku-data-admin
heroku-data-api 0.2.4
heroku-kafka 2.12.0
mtls 0.9.1
pg-extras 0.0.4
└─ @oclif/plugin-help 1.2.11
write-only-config-vars 0.0.11
├─ @oclif/plugin-plugins 2.4.7
└─ @oclif/plugin-help 5.2.20
```
```
jwadsworth@jwadswo-ltm7hqp: …
```

fix: removes debugging statement from CLI plugin

---

packages/cli/test/unit/commands/container/push.unit.test.ts

Recent merge flubbed an existing test. This fixes it.

chore(cli): Fix container push test.

---

packages/cli/src/commands/spaces/index.ts
packages/cli/src/commands/telemetry/index.ts
packages/cli/src/commands/telemetry/info.ts
packages/cli/test/unit/commands/telemetry/index.unit.test.ts
packages/cli/test/unit/commands/telemetry/info.unit.test.ts

[GUS WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000023YlPsYAK/view)
This moves uses of `3.fir` variant to `3.sdk`.

Switch variant usage from 3.fir to 3.sdk

---

packages/cli/src/commands/telemetry/add.ts
packages/cli/test/unit/commands/telemetry/add.unit.test.ts

A few updates to help and error text.

chore: help and error text updates for telemetry:add

---

.github/workflows/create-cli-release.yml
.github/workflows/ctc.yml
cspell-dictionary.txt
packages/cli/package.json
packages/cli/src/hooks/plugins/preinstall/disclaimers.ts
packages/cli/test/unit/hooks/disclaimers.unit.test.ts
scripts/postrelease/change_management

Jw/update prerelease 10.0

---

packages/cli/src/commands/access/index.ts

recreation of https://github.com/heroku/cli/pull/3055

fix: access command error handling

---

.github/workflows/create-cli-release.yml
.github/workflows/devcenter-doc-update.yml
.github/workflows/pack-upload.yml
CHANGELOG.md
docs/addons.md
docs/pg.md
docs/ps.md
packages/cli/CHANGELOG.md
packages/cli/src/commands/addons/create.ts
packages/cli/test/unit/commands/addons/create.unit.test.ts

update 10.0 alpha

---

packages/cli/src/commands/git/remote.ts

Fixes #1246 
Updates the git:remote example documentation to reflect staging app.

fix(git:remote): update example text to reflect staging app

---

packages/cli/src/global_telemetry.ts
packages/cli/test/unit/global_telemetry.unit.test.ts

Update staging URL for OpenTelemetry.

Staging telemetry hostname

---

.github/workflows/promote-release.yml
.github/workflows/tps-record-release.yml

Add missing closing bracket, fix input name mismatch

---

.github/workflows/promote-release.yml
.github/workflows/tps-record-release.yml

update 10.0 alpha again

---

.github/workflows/create-cli-release.yml
.github/workflows/start-gh-release.yml

update 10.0 alpha again again

---

package.json
yarn.lock

Removing this unused library I think will resolve https://github.com/heroku/cli/security/dependabot/91

Remove unused promise retry library

---

.github/CODEOWNERS
CODEOWNERS

Clean up content of `CODEOWNERS`, remove old one.

chore: update CODEOWNERS file content, remove old one

---

yarn.lock

chore: Update debug to latest versions

---

yarn.lock

This updates socks to a more recent minor version, resolving a security vuln

chore: update socks

---

.github/workflows/direwolf.yml
.github/workflows/release-homebrew.yml

Use more recent runners, stop trying to install awscli

---

packages/cli/package.json
packages/cli/src/lib/run/log-displayer.ts
packages/cli/test/helpers/init.js
packages/cli/test/integration/logs.integration.test.ts
packages/cli/test/unit/lib/run/log-displayer.unit.test.ts
yarn.lock

Reverts heroku/cli#3209 since some regressions were seen with this PR. We will circle back and investigate the RCA a bit further.

Revert "fix(W-17265927): SSL issues with heroku logs"

---

scripts/update-tool-versions-file

Add script to update tool versions file to latest node 20

---

packages/cli/src/commands/logs.ts

This PR updates help text for the logs command
[W-17857872](https://gus.lightning.force.com/a07EE000029zqoQYAQ)

chore(W-17857872): update help text for logs command

---

.github/workflows/ci.yml
.github/workflows/pr-title-conventional-commit.yml
cspell-dictionary.txt

add workflow to validate pr title title

---

cspell.json

Since the changelogs are generated, we should exclude them from cspell checks.

chore: add changelogs to ignorePaths for cspell
